### ISSUE TITLE
Session caching Work In Progress [Technical]

### ISSUE THREAD

**Issue by ZizzyDizzyMC** [ORelio/Minecraft-Console-Client#101]
Looking into letting the client soft-save session ID's to reduce login attempts to mojang.

These login attempts are normally ok. If you're already pushing the limits of your allowed logins per hour a single disconnect-reconnect might get you temp-banned by IP from mojang's auth services.

Currently inspecting the client-flow of how and when session ID's are used so I can put a toggle in all the places I need to disable / override the session ID get() method. *not actual method name*

Doing such a soft-save would only mean reusing the session ID's till they eventually return "Failed to login: Invalid Session" as an error then call the method to get a new session ID.  If using limited proxy bandwidth I expect to save about 2400% of bandwidth used by logins only.  Considering a session ID for me seems to last for about a day before returning "Invalid Session" error.  (Reconnect a client to a server once an hour, only logging in 1 per 24 hours instead of 24 times in 24 hours.)

If anyone has a suggestion on how to accomplish this without much pain for ORelio to go though my code and clean it up.

Till next update - ZizzyDizzyMC

**Comment by ORelio** [comment]
Hello,

In fact, session tokens will expire (not sure of the timeout) unless being refreshed using an access token given by the API while performing the login step: http://wiki.vg/Authentication#Refresh. Initially, MCC was performing login on each server connection because it wasn't really rate limited as long as the password was correct, and session needed to be refreshed every 10 minutes: http://wiki.vg/Legacy_Authentication

So, we _may_ implement smarter session handling to limit authentication requests, however this will _not_ save any bandwidth, there would be even more requests instead.

**Comment by ZizzyDizzyMC** [comment]
That's just weird and obnoxious courtesy of Mojang.  I can't find much documentation on the timeout like you said.  I removed internet from my PC overnight (7 hours) and my session is still valid.  So it looks like refreshing it may not have to be using more bandwidth afterall.

Perhaps these session tokens actually refresh on each connect / disconnect? (I'm not sure I can't code java.)

**Comment by ORelio** [comment]
Logging in with a password invalidates access tokens from other computers, in my case. Maybe we can detect when the session is expired and re-perform a minecraft login in that case, that's indeed an option if the token does not expire as fast as before.

**Comment by initsuj** [comment]
I have this working, roughly. From what I'm seeing, the access token does not expire unless you sign it out or login from another pc. This would mean that we have to blindly attempt login and handle the condition of renewing the cached token.

My questions? I assume we want the file to be in the executable directory or have a setting for cache location? Should the file be human readable (we already store the user name and password as human readable, so I would say yes)?

possible settings:

1. cache file location
2. disable

I don't see the need for either. The cache is global - it is used for all MinecraftClient.ini files. The only reason I could see for having the location as a user setting would be in the case they do not have write privileges in the app location.

**Comment by ORelio** [comment]
We could add a setting for choosing between
 - No caching (as currently)
 - Session caching (in-memory)
 - Disk caching (a local file seems fine eg Session.db)

**Comment by initsuj** [comment]
Can do. For testing, I've serialized to XML. However, it is possible for multiple clients to have the cache in memory. We can lock the file before update, compare, update memory-object,  write file and release.

**Comment by ORelio** [comment]
A lock will obviously be needed.
MCC uses INI files, that seems more appropriate to use a similar format?
(or maybe something like accounts file)

**Comment by initsuj** [comment]
INI is friendly for user configuration, but is difficult to serialize into and out of. The benefit is lost since the cache should not be user edited.

This is essentially reading/writing a dictionary<username, session> to a file. I would vote for JSON or XML serialization to use C# builtin serialization.

**Comment by ORelio** [comment]
If you need it I already wrote a INI handling class:
https://github.com/ORelio/Sharp-Tools/blob/master/Utility/INIFile.cs

Code sample:
````C#
//private static Dictionary<string, string> sessionCache; // login/email -> sessionId
//[...]

//Load
sessionCache = INIFile.ParseFile(filename)["sessioncache"];

//Save
var toSave = new Dictionary<string, Dictionary<string, string>>();
toSave["sessioncache"] = sessionCache;
INIFile.WriteFile(filename, toSave);

````

**Comment by initsuj** [comment]
Initially, the idea is to create a token class that holds the UserName, ID and UUID and have the cache based on a dictionary<UserLoginString, Token>. Not going through the Login method, so we need to store everything that would give us.

With that model, INI becomes more difficult because of the relational data. Parsing is easy, but having a list of data groups is more difficult. I'll play with it a bit.

**Comment by ORelio** [comment]
Well indeed that seems less convenient if we need to store 3 fields.
How about storing only login & authentication token and using
http://wiki.vg/Authentication#Refresh to make sure the session is still valid?

**Comment by initsuj** [comment]
According to the behavior of the official client, it does a Validate (http://wiki.vg/Authentication#Validate) to check the state of the current token and if it is invalid, then it does a refresh. However, there is nothing that I see that would have negative behavior if we jumped straight to a Refresh even if not required other than rotating tokens more frequently.

**Comment by ORelio** [comment]
Both approaches seems valid, well, since you are working on it and the database seems indeed unlikely to be modified feel free to use the approach you prefer. The only guideline I'd recommend is avoiding using a library if possible. Also not sure of how you started it but maybe implementing that in the login method could be interesting since then it would the the login method that determines the best way to get a valid session token?

**Comment by initsuj** [comment]
On implementing it in the login method - I agree. If a non-empty accessToken and clientToken are passed, it should Validate, then, if necessary, Refresh.

Another question: Are you avoiding the json serializer for any particular reason? No problem following suit on hand writing the json, but seems "easier" to create request and response models and serialize/deserialize, though I'd imagine it is slightly heavier and has repercussions on backwards .net/mono compatibility. I believe the serializer goes back to .net 3.5.

**Comment by ORelio** [comment]
Yes or it's the login method itself that checks the cache, both are valid anyway.

Mono on Linux had very few features in the past (I must recognize that writing a JSON parser myself was a bit crazy but hey it works well and it's... faaast ^^) but that shouldn't really be the case anymore. So if there is a built-in serializer in .NET feel free to use it (MCC requires .NET 4+ anyway). In the worst case the cache (and so the use of the serializer) can be disabled in app config so that should be okay.

You can install Mono for Windows in case you want to test Linux compatibility without actually using Linux.

**Comment by initsuj** [comment]
Yeah. I was wondering. I've already implemented the underlying refresh and validate calls with static json and found the following: blindly calling refresh on a valid token returns an error. No problem, because the validation method is simple and works, but I'm having problem invalidating the token so that a refresh will work without requiring a full login. I've invalidated it to the point of requiring a new login. 

We could skip a refresh all together and just fall back to full login on an invalid token.

I'm going to assume the refresh works on success. The parsing is close enough to a full login according to the documentation, it should be good. (famous last words)

At this point, I think I'm just going to keep all of the authentication control in the InitializeClient.

I looked more closely at the json serialization and it would require the project to target .Net 4.0 full, not Client Profile. Since it's already done and nothing is really gained at this point, I see no point. 

Oh, I run xamarin studio targeting mono for verification that everything remains cross-platform as a final step.

**Comment by initsuj** [comment]
pull request is sent for this issue. I would consider this feature in beta - more graceful handling of file access collision is needed, but currently the request to write new/updated tokens to the disk will fail with a notice in the console and continue. On next use of the old token, a full login may be required.

**Comment by Aragas** [comment]
Why not use json.net? Big overhead? It runs on everything.

And, actually, always crossed my mind. The whole console realization is using mostly raw classes and data. There are some minecraft implementations like mine, and they even run on android. What about switching to it? 
Btw, I can also add lua support if ya wanna.

**Comment by ORelio** [comment]
Built-in serialization works fine so no need for an additional library, I guess. Libraries are cool; but that makes the app heavier that's why when a library is needed I only pick the necessary classes from them, that ensure we only take what we need and we are sure it will work even on linux (no native code, so Mono can handle it).

**Comment by Aragas** [comment]
I think at some point of extending MCC those class overheads will be useful. Right now they aren't, guess. 
But I'll be always waiting for your call

**Comment by ORelio** [comment]
Just for reference: here is a bug with disk cache that was reported to me some months ago, most likely by @TNTUP (but not sure). Cache is constantly reloaded from disk after first load. Here is an illustration using additional debug messages:

![disk-session-cache-load-bug](https://cloud.githubusercontent.com/assets/1128206/19215102/0af0325e-8d95-11e6-80ee-00e66fec1c68.png)

This is now fixed (see commit above) :wink:

We should be done with this feature now, so closing the issue.
Thanks everyone for your involvement and feel free to reopen if needed.
