### ISSUE TITLE
Modchecker Plugin Compatibility

### ISSUE THREAD

**Issue by ituitis-durmusy18** [ORelio/Minecraft-Console-Client#1056]
Hello,

Whenever I try to login to a server with this plugin I get kicked out. Could you be able to fix it so program is compatible with ModChecker plugin.

Also I should mention that this plugin checks your files in ./minecraft and compares it to a blacklist but when the blacklist is empty the plugin still kicks you out.

https://github.com/Confuser2188/ModChecker

**Comment by ReinforceZwei** [comment]
The `ModChecker` send a [Resource Pack Send](https://wiki.vg/Protocol#Resource_Pack_Send) packet to client and check the response packet [Resource Pack Status](https://wiki.vg/Protocol#Resource_Pack_Status) to see if the client accepted it or not. If client accepted, player will be kicked out.

Since MCC always response `accepted/successfully loaded` regardless the packet content ([Protocol18.cs#L580](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/Protocol/Handlers/Protocol18.cs#L580)) , so the client will always get kicked out.

As checking the code of `ModChecker`, I found that the hash value sent is a fixed value "MC", but the hash should be a 40 character hexadecimal string. We could fix this issue by checking the hash value received.

**Comment by ituitis-durmusy18** [comment]
It does work. Thank you very much.

**Comment by ORelio** [comment]
Oh, that kind of plugin is evil. Using an exploit in vanilla Minecraft to check for local files... 🤦
Well, since MCC sends fake resource pack acceptance, it will indeed trigger a false positive on the plugin.
@ReinforceZwei's fix seems appropriate, adding in into the repository.
