### ISSUE TITLE
AutoEat crash

### ISSUE THREAD

**Issue by Nekiplay** [ORelio/Minecraft-Console-Client#1060]
**Prerequisites**
 - [x] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
 - [x] I tried to [look for similar issues](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
 - [ ] I have set `debugmessages=true` in config to diagnose my issue
 - [x] I have redacted session tokens and passwords before attaching screenshots

**Bug description**
I think the error occurred during the attack or death
![image](https://user-images.githubusercontent.com/35975332/84571794-216e9a00-adaf-11ea-8818-01ffa44f8709.png)
version: 1.15.2

**Comment by ORelio** [comment]
Hi,
Looks like a bug in AutoEat.
Additionally, seems like the error handling is not correctly implemented in some ChatBot API events.

**Comment by Nekiplay** [comment]
> Hi,
> Looks like a bug in AutoEat.
> Additionally, seems like the error handling is not correctly implemented in some ChatBot API events.

Yes, AutoEat is on.

**Comment by ReinforceZwei** [comment]
I think the cause is [this line](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/ChatBot.cs#L999). For some reason after the player dead, the inventory was gone and `Handler.GetPlayerInventory()` return `null` and hence cause the NullReference. _(but why would the inventory be gone?)_

`AutoEat` has its own fault too. It didn't check the health is zero or not and keep trying to eat after player dead.

Actually, all `ChatBot` method call after [line 1600 of McTcpClient.cs](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/McTcpClient.cs#L1601) haven't implemented any error handling.

**Comment by ORelio** [comment]
@Nekiplay Don't forget the error handling code when adding new ChatBot events 😉

**Comment by ORelio** [comment]
Should be resolved as per #1068, I'll let you check if it works.
