### ISSUE TITLE
How do I auto relog my Minecraft alts on Mac?

### ISSUE THREAD

**Issue by Whereismycantaloupe** [ORelio/Minecraft-Console-Client#1063]
Is anyone able to teach me how to have my alts relog when they're disconnected from a server? I have tried checking online and on YouTube for tutorials but everything is for PC, not Mac. Any help is much appreciated! (Sorry, you may need to bear with me since I am pretty bad with technology)

**Comment by ORelio** [comment]
https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config#using-the-autorelog-bot

**Comment by Whereismycantaloupe** [comment]
How do I get to the place to enable bots, such as autorelog, on Mac? When I downloaded the client I only saw 2 .exe files and nothing else.

**Comment by ORelio** [comment]
Run it once to generate the configuration file.

**Comment by Whereismycantaloupe** [comment]
Ive since figured out how to open the .ini file and adjusted the auto relog and anti afk sections, but now I cannot find the kick messages.txt file on my Mac. Is there any way to find this?

**Comment by ReinforceZwei** [comment]
@Whereismycantaloupe  You can create one yourself.

**Comment by Whereismycantaloupe** [comment]
@ReinforceZwei Can you give a brief description of how?

**Comment by ReinforceZwei** [comment]
https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/config/kickmessages.txt

This is an example of the kickmessage.txt file. You can create the kickmessage.txt file and copy the content from above to your file.

If you want to ask how to create a file on macOS, sorry I don’t know how to do that because I don’t have a Mac :P
