### ISSUE TITLE
Add plugin messages / Transfer large amount of data

### ISSUE THREAD

**Issue by ZizzyDizzyMC** [ORelio/Minecraft-Console-Client#108]
I have a very special need of a client to handle HUGE packets from a server.  These packets are chat packets that contain so much information per packet that all other clients I've tried simply crash. Including Console Client.

This is the error all clients get in some form or another,
[http://zizzydizzymc.info/s/Q%20%282%29.png](url)
Basically I'm trying to dump config files from a server by chat line. It's not working so well.  I thought just maybe someone here would be able to make this client capable of doing this very thing.

These packets are 1514 in length... (From Wireshark.)  There are hundreds of these packets after performing the dump command on the server.

For the record, I don't have VS installed right now and I don't have access to the physical server files.  Physical files would be so much easier but I can't do that at this time.

**Comment by Pokechu22** [comment]
Are you able to control how the data is being sent from the server?  Because in that case, it would be easier to use a [plugin channel message](http://wiki.vg/Plugin_channel) to send the data, which supports arbitrary data (and is built-in on bukkit).

In any case, the [chat packet's max length is 32767 bytes](http://wiki.vg/Protocol#Chat_Message) (and this is part of the game's protocol).  That number does includes a bit of JSON overhead, I think, so in practice you get even fewer bytes.

I've tried sending some long chat messages (20000 characters of random numbers) and the client doesn't disconnect, but 40000 does crash it (since it's greater than that cap):

![Unhandled Exception: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.readNextVarInt(Byte[]& cache)
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.readNextString(Byte[]& cache)
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.handlePacket(Int32 packetID, Byte[] packetData)
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.Update()
   at MinecraftClient.Protocol.Handlers.Protocol18Handler.Updater()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()](https://cloud.githubusercontent.com/assets/8334194/12870596/5b943034-cd01-11e5-8b5c-0de96e649310.PNG)

If you look in your server console, you'll probably see something like this:

>     io.netty.handler.codec.EncoderException: String too big (was 40024 bytes encoded, max 32767)

FYI, sending data via chat in spigot will take even longer since it'll try to convert to the new format and that took like 45 seconds for a single message for me.

-----

Right now MCC doesn't support reading arbitrary plugin channels with a chatbot, but that seems like something that would be easy to add and would be highly useful.  I might write that up.

[Here's the reference on plugin channels](http://dinnerbone.com/blog/2012/01/13/minecraft-plugin-channels-messaging/).  Note that the length info there is out of date - as of Minecraft 1.8 plugin channel packets being sent from the server to the client have a max length of **1048576 bytes** (of whatever data you want!), although ones sent from the client are still limited to 32767 bytes.

**Comment by ORelio** [comment]
Well, plugin messages could indeed be useful, good idea!
Meanwhile, you may try to send your text part by parts eg 1000 characters by 1000 characters.
Although I'm not sure that so much text would be really readable for for debug purposes anyway.

**Comment by ZizzyDizzyMC** [comment]
It's okay. Turns out the server went corrupt and then shutdown forever. All good issue can be closed safely.

**Comment by ORelio** [comment]
Implemented in #109
