### ISSUE TITLE
Error on joining server: System.InvalidOperationException: Queue empty.

### ISSUE THREAD

**Issue by nowifi4u** [ORelio/Minecraft-Console-Client#1092]
**Prerequisites**
 - I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
 - I tried to [look for similar issues](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one
 - I have set `debugmessages=true` in config to diagnose my issue
 - I have redacted session tokens and passwords before attaching screenshots

An error on joining this particular server: inf.craftersland.net

[Log (click me)](https://pastebin.com/zbKftcL1)

**Comment by ORelio** [comment]
Maybe MCC is using an incorrect Minecraft version to join your server
`forge 1.7.10 (protocol v5, with Forge)` => Is your server actually running MC 1.7.10?
If not, set `mcversion=1.X.X` with the correct version in your configuration file.

**Comment by nowifi4u** [comment]
> Maybe MCC is using an incorrect Minecraft version to join your server

In logs in line 186: Server version : kcauldron,cauldron,craftbukkit,mcpc,fml,forge 1.7.10 (protocol v5, with Forge).

> `forge 1.7.10 (protocol v5, with Forge)` => Is your server actually running MC 1.7.10?

Yes, it is 1.7.10 with forge

**Comment by ORelio** [comment]
The Chat Message packet, which crashes on your side, has not changed since Minecraft 1.7 all the way to Minecraft 1.16. So my guess here is that some Forge mod is altering chat message packets, but since MCC does not actually implement all Forge mods, it does not handle that modified packet properly. I'm not sure we can fix this except by ignoring chat messages entierely 🤔

**Comment by ORelio** [comment]
Currently it is not possible to disable chat messages, but a suggestion exists in #1085
