### ISSUE TITLE
Credentials Issue

### ISSUE THREAD

**Issue by KohGeek** [ORelio/Minecraft-Console-Client#110]
Password with symbols and 25 characters long are apparently unusable in this program.
I'm not sure but
&!$* <--- these few symbols seems to cause problems.

**Comment by KohGeek** [comment]
Tested latest build, no avail.

**Comment by ORelio** [comment]
Which keyboard layout do you have, and which operating system & language?
Meanwhile you may specify password in command line, INI file, and using the GUI.

**Comment by KohGeek** [comment]
My keyboard layout is US, since I have a laptop I normally use another keyboard with keypads on it, but still US.

I'm on Windows 10 Build 10586 English (Malaysia).

I've typed in password in all three different input and none works.

**Comment by ORelio** [comment]
Okay, so if it doesn't work on all of the possible inputs that's not caused by the interactive password prompt not behaving the same depending on the keyboard layout, as I previously guessed.

In that case, it must be caused by the login attempt itself not encoding properly the password. Currently I can't reproduce your issue and that's strange because the authentication requests should properly encode the password :hushed:

**Comment by ORelio** [comment]
Oh, maybe that's because [json_encode](https://github.com/ORelio/Minecraft-Console-Client/blob/e4916033fa2c4d46891bf5241e0eee792d89455b/MinecraftClient/Protocol/ProtocolHandler.cs#L273) relies on `char.IsLetterOrDigit` which might behave differently for your language... except than it seems unlikely that `&!$*` whould be considered as letters or digits even in your configuration... well, I'll try changing that anyway to see if it helps.

**Comment by KohGeek** [comment]
Hmm... btw I do paste my password because it's quite long for me to remember it.
I figure maybe pasting ruined something.

**Comment by ORelio** [comment]
If you past it in the configuration file that should work :/

**Comment by KohGeek** [comment]
I will try again in the config.

**Comment by KohGeek** [comment]
Oh wait I'm stupid. I used username instead of email.
I am really sorry. ._.

**Comment by ORelio** [comment]
Oh. There should have been a better error message for this case. Will take a look.
