### ISSUE TITLE
How to connect multiple account at the same time

### ISSUE THREAD

**Issue by Stymix** [ORelio/Minecraft-Console-Client#1126]
Hi, I have to connect 30 accounts and I want to know if that's possible to connect all acounts at the same time and not to type account 1 by 1.

thanks.

**Comment by Daenges** [comment]
So basically you can work with a batch file and write "START [PATH OF CLIENT] [ACCOUNT] [PASSWORD] [SERVER IP]" for each account you want, start a new line in the file. Safe it as ".bat"-File and it will start the client 30 times (one account each).

Although I don't know what you are planing to do with 30 accounts on a server, I really disadvice you to try this on servers other than your own. This could cause huge lag and many trouble for any server staff!
If they interpret it as a DOS attack they may even sue you or something! So, whatever you do with it, be careful!

**Comment by Stymix** [comment]
Ahah don't worry I'm allowed to use 30 alt account on this server for being afk :)

I'm gonna try your method in 3/4 hours thanks you !

**Comment by CrewParzi** [comment]
Its better you add a wait time between each alt because Mojang can blacklist you for logging in too many accounts at once.

So make a folder and keep MinecraftClient.exe and MinecraftClient.ini in it

Now open a notepad and enter this:

start /min MinecraftClient.exe Email Pass ServerIP
timeout 5

start /min MinecraftClient.exe Email Pass ServerIP
timeout 5

Just repeat it for as many alts as you want, and save this notepad file as start.bat and keep it in the same folder.

**Comment by Daenges** [comment]
Maybe this video helps:
https://youtu.be/HglFM8GRzZA

**Comment by ORelio** [comment]
Currently each MCC instance can log only 1 account at a time. You may use a tabbed console for convenience. See #986
