### ISSUE TITLE
ArgumentOutOfRangeException with terrain/movements

### ISSUE THREAD

**Issue by Awpocalypse** [ORelio/Minecraft-Console-Client#114]
When i ran console client with terrain movements on this happend...

https://gyazo.com/39cc4aff1594fec21663f478bcb88c3d

**Comment by initsuj** [comment]
was /server jurassic the last command in the script file?

**Comment by ORelio** [comment]
Oops, forgot to respond to your issue... Seems like the issue is in the `1.8.X` packet parser, but unfortunately the error stack trace does not tells the exact line. Does your issue appears every time you go to that server? If so it may be possible to try again with a debug build with exact line numbers in error messages.

**Comment by Awpocalypse** [comment]
Initsuj it was the only command and i also tried it without a script

**Comment by Awpocalypse** [comment]
Orelio yes it does but ill attempt it other ways when i get the time if you wanna test the ip is play.opticcraft.tv

**Comment by initsuj** [comment]
I can't reproduce with the latest version - I have  terrainandmovements=true and use /server jurassic. Test with the latest version? https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts

**Comment by Pokechu22** [comment]
By chance, is this a 1.7.10 server?  I think I know what's causing this, and it doesn't relate to terrain here.

Instead, it seems to be a result of the change in cb00c28b - since `List<byte>` is being used instead of `byte[]`, an `ArgumentOutOfRangeException` is thrown instead of an `IndexOutOfRangeException`.  And since only `IndexOutOfRangeException` is caught when checking the message type, that exception now makes it through instead of getting caught.

**Comment by Awpocalypse** [comment]
1.7 n 1.8

**Comment by Awpocalypse** [comment]
Sorry i havent had the time to investigate buzy with school

**Comment by ORelio** [comment]
Please retry with the latest development build :)

**Comment by Awpocalypse** [comment]
It has been fixed :)

**Comment by ORelio** [comment]
Great! :)
