### ISSUE TITLE
Vulnerability concerning nickname changes

### ISSUE THREAD

**Issue by f2hafner** [ORelio/Minecraft-Console-Client#1142]
Vulnerability Report
==================================================================================
_Technically this is not a Bug, because the code works like intended. But maybe a "Vulnerability" Label should be added.
I didn't want to write a full CvE for it so I'm just wanna let you all know of this attack vector this way._

**There is a vulnerability where attackers could execute code without being authorized to do so.**

### THE PROBLEM
In the File *MinecraftClient.ini* there is the line:
```
botowners=  # Use name list or myfile.txt with one name per line
```
It allows specifying owners of the bot. This way only players mentioned in this line or the *myfile.txt (if specified)* can execute certain commands. But, since the commonly used essentials plugin adds the */nick* command, players can change their player name into any name. Therefore a player changing their nickname to any name of the bot owners can execute the same code, which was only intended for authenticated usage.

***This could not only damage vital parts of a server's infrastructure but is also in contradiction with the basic principles of the CIA+ key concepts for Information security.***

### PROBLEM LOCATION

Since ChatBot.cs takes the sender and text of a message through a RegEx directly out of the chat. It will just match the nickname. Therefore it's really easy to just choose the same name as the bot owner and issue commands with their *permissions*.
```
ChatBot.cs:
protected static bool IsPrivateMessage(string text, ref string message, ref string sender)
        {
            if (String.IsNullOrEmpty(text))
                return false;

            text = GetVerbatim(text);

            //User-defined regex for private chat messages
            if (Settings.ChatFormat_Private != null)
            {
                Match regexMatch = Settings.ChatFormat_Private.Match(text);
                if (regexMatch.Success && regexMatch.Groups.Count >= 3)
                {
                    sender = regexMatch.Groups[1].Value;
                    message = regexMatch.Groups[2].Value;
                    return IsValidName(sender);
                }
            }
```

### EXAMINATIONS
I and [@andreasgrafen](https://github.com/andreasgrafen) tested it. He created a bot where *botowners=lowo* and I tried to message it in public chat. *(He used RegEx to get rid of the symbols in front of our names)*
The bot should respond to the word "bot" in chat. But only if the owner *(lowo)* initially sent it.
![image](https://user-images.githubusercontent.com/58081895/87888308-7f387680-ca2c-11ea-838b-e52178020238.png)
Here you can see the bot responding when my name is "lowo" and it not responding when my name is "yuki".

### MITIGATIONS
Now how could we resolve the issue?

- ChatBot.cs could use the */realname* command provided by essentials (if available) which returns the real username of a player's nickname. This could get rid of this issue on servers running essentials*(which causes the issue in the first place)*

- This issue doesn't exist on servers without a /nick function. Therefore no mitigations needed.

**Comment by ORelio** [comment]
Hi @f2hafner and thanks for this detailed report. I'll handle it and provide a response as this project's owner.

_**Abstract:**_ Basically, Minecraft Chat is user input. As a consequence, we should not trust it. But in order to process chat messages, tell apart usernames, write bots with bot owners, we need to trust it to a certain extent. So yes, this is a vulnerability, and unfortunately, as you noticed, there is very little we can do about this because it's somewhat by design. At the client level, we have very few details about who is talking in chat, at the opposite of server-side where we can just call the appropriate Bukkit API method to get either the username, display name or UUID of the player sending commands or messages. So it's not wise to write complex and powerful bots that will for instance run system commands on your operating systems based on chat messages. Use server plugins when you can, and only harmless moderation commands for bot owners, such as launching a new hangman game. Please.

## Chat messages at the network level

I'll speak about the initial chat implementation in Minecraft. That is, Minecraft 1.4.X which is still supported in Minecraft Console Client. At that time, everyone had a fixed username, that is, a username you choose when you purchase the game, and that you can't change afterwards. The Chat format was very simple, here is an example of [MC 1.4.4 Chat Message](https://wiki.vg/index.php?title=Protocol&oldid=1007#Chat_Message_.280x03.29) sent by the server to the client:

Packet ID | Field Name | Field Type | Example | Notes
-- | -- | -- | -- | --
0x03 | Message | string | <Bob> Hello World! | User input must be sanitized server-side
Total Size: | 3 bytes + length of strings

Yes, the server only sends a string. No additional metadata besides optional `§c` [formatting codes](https://minecraft.gamepedia.com/Formatting_codes#Color_codes) for colors, bold, italic, etc. So the client chat is like a terminal. It can display text with formatting, but has no idea of what is being shown. It's up to the user to interpret the data being displayed in the chat. Chat messages can be player chat, server announcements, command results, and so on.

The Nickname feature from server plugins has the exact goal of hiding your actual username from users and showing another name instead. The same way you'll trick actual users into believing you are who you pretend to be, well, of course you'll trick Minecraft Console Client as well. You cannot protect yourself from server owners and VIPs having that powerful `/nick` command.

## How MCC handles chat messages

In Minecraft Console Client, we want to automate things. So we need to process chat messages. Chat messages are intended for human users, yet we want to process them automatically. Our first approach is to use parsing code to tell apart common message formats for public messages ([IsChatMessage](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/ChatBot.cs#L510)), private messages ([IsPrivateMessage](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/ChatBot.cs#L399)), teleport requests ([IsTeleportRequest](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/ChatBot.cs#L613)) and anything else. Our job is made hard by just about every server having its own chat format, so we can only support Vanilla chat format as well as popular chat formats from Essentials, Factions, and that's it.

Minecraft Console Client's built-in code is not made of regular expressions for performance reasons. The code is both faster and safer if we explicitly write down how we want the string to be parsed rather than throwing a regular expression. However, users can define custom regular expressions to tune Minecraft Console Client to their own server chat format.

Regular expressions provided as an example are the following:
````ini
public=^<([a-zA-Z0-9_]+)> (.+)$
private=^([a-zA-Z0-9_]+) whispers to you: (.+)$
tprequest=^([a-zA-Z0-9_]+) has requested (?:to|that you) teleport to (?:you|them)\\.$
````
They provide a base including both `^` and `$` characters to prevent trivial bypass like the following one where `EvilUser` sends a message containing the exact chat format for tricking the bot into believing it's from `BotOwner`:
````
<EvilUser> <BotOwner> Hey, I'm the bot owner!
````
Regex are user-defined, so we can't really help here besides helping users in [chat-format-regex](https://github.com/ORelio/Minecraft-Console-Client/issues?q=label%3Ain%3Achat-format-regex+) issues such as #712.

If your server owner is nice enough for leaving the leading `~` in front of nicknames, you can easily ignore them by using or tuning the example regex which does not include the `~` character, and setting `builtins=false`. By default, Minecraft Console Client accepts nicknames for convenience, because usually if you can rename yourself you are the server admin, so you might want to use your nickname as bot owner for your client monitoring chat 24:7. And you can't protect yourself from server admins, chat format is user input from server admins anyway. They can make you send anything with `/sudo` and see what PMs you send to your bot, so you should rather trust them or not enable remote commands at all.

## JSON chat messages

Since Minecraft 1.6, chat messages are [in the JSON format](https://wiki.vg/index.php?title=Protocol&oldid=1096#Chat_Message_.280x03.29):
```json
{"translate":"chat.type.announcement","using":["Server","hi"]}
{"color":"gray","italic":true,"translate":"chat.type.admin","using":["Server",{"translate":"commands.save.success"}]}
{"text":"§aOld style chat"}
````
This, at first, seems very interesting because of the `printf`-like feature used by Minecraft 1.6 for chat messages:
````
chat.type.text: <%s> %s
````
Finally, we have a way of easily telling apart usernames and chat messages... or so we thought. Turns out that due to the existing code on Bukkit and all its plugins, almost all servers are sending messages in the following fashion:
````json
{"text":"§aOld style chat"}
````
So actually we are still stuck with the classic messages that we need to parse with a variable success rate.

## UUID attached to chat messages

So now it's 2020, it's been more than 5 years that we can change our usernames in Minecraft and everyone has a UUID that never changes. And guess what, in the recently released Minecraft 1.16, a new field is finally present in the [MC 1.16 Chat Message](https://wiki.vg/index.php?title=Pre-release_protocol&oldid=15931#Chat_Message_.28clientbound.29): UUID.

Packet ID | State | Bound To | Field Name | Field Type | Notes
-- | -- | -- | -- | -- | --
0x0E | Play | Client | JSON Data | Chat | Limited to 32767 bytes
Position | Byte | 0: chat (chat box), 1: system message (chat box), 2: game info (above hotbar).
Sender | UUID | Used by the Notchian client for the disableChat launch option.  Setting both longs to 0 will always display the message regardless of  the setting.

I have not tested this in real life yet, however I fear that servers with plugins will either leave it all-zero or with some dummy UUID. On the other hand, if servers implement it properly, we should be able to define UUIDs as bot owners in config, and benefit from a much more reliable way of telling apart bot owners from other players, regardless of their display name. Wait and see.

**Comment by Nekiplay** [comment]
> # Vulnerability Report
> _Technically this is not a Bug, because the code works like intended. But maybe a "Vulnerability" Label should be added. I didn't want to write a full CvE for it so I'm just wanna let you all know of this attack vector this way._
> 
> **There is a vulnerability where attackers could execute code without being authorized to do so.**
> 
> ### THE PROBLEM
> In the File _MinecraftClient.ini_ there is the line:
> 
> ```
> botowners=  # Use name list or myfile.txt with one name per line
> ```
> 
> It allows specifying owners of the bot. This way only players mentioned in this line or the _myfile.txt (if specified)_ can execute certain commands. But, since the commonly used essentials plugin adds the _/nick_ command, players can change their player name into any name. Therefore a player changing their nickname to any name of the bot owners can execute the same code, which was only intended for authenticated usage.
> 
> _**This could not only damage vital parts of a server's infrastructure but is also in contradiction with the basic principles of the CIA+ key concepts for Information security.**_
> 
> ### PROBLEM LOCATION
> Since ChatBot.cs takes the sender and text of a message through a RegEx directly out of the chat. It will just match the nickname. Therefore it's really easy to just choose the same name as the bot owner and issue commands with their _permissions_.
> 
> ```
> ChatBot.cs:
> protected static bool IsPrivateMessage(string text, ref string message, ref string sender)
>         {
>             if (String.IsNullOrEmpty(text))
>                 return false;
> 
>             text = GetVerbatim(text);
> 
>             //User-defined regex for private chat messages
>             if (Settings.ChatFormat_Private != null)
>             {
>                 Match regexMatch = Settings.ChatFormat_Private.Match(text);
>                 if (regexMatch.Success && regexMatch.Groups.Count >= 3)
>                 {
>                     sender = regexMatch.Groups[1].Value;
>                     message = regexMatch.Groups[2].Value;
>                     return IsValidName(sender);
>                 }
>             }
> ```
> 
> ### EXAMINATIONS
> I and [@andreasgrafen](https://github.com/andreasgrafen) tested it. He created a bot where _botowners=lowo_ and I tried to message it in public chat. _(He used RegEx to get rid of the symbols in front of our names)_
> The bot should respond to the word "bot" in chat. But only if the owner _(lowo)_ initially sent it.
> ![image](https://user-images.githubusercontent.com/58081895/87888308-7f387680-ca2c-11ea-838b-e52178020238.png)
> Here you can see the bot responding when my name is "lowo" and it not responding when my name is "yuki".
> 
> ### MITIGATIONS
> Now how could we resolve the issue?
> 
> * ChatBot.cs could use the _/realname_ command provided by essentials (if available) which returns the real username of a player's nickname. This could get rid of this issue on servers running essentials*(which causes the issue in the first place)*
> * This issue doesn't exist on servers without a /nick function. Therefore no mitigations needed.

Delete Essentials )

**Comment by Nekiplay** [comment]
> # Vulnerability Report
> _Technically this is not a Bug, because the code works like intended. But maybe a "Vulnerability" Label should be added. I didn't want to write a full CvE for it so I'm just wanna let you all know of this attack vector this way._
> 
> **There is a vulnerability where attackers could execute code without being authorized to do so.**
> 
> ### THE PROBLEM
> In the File _MinecraftClient.ini_ there is the line:
> 
> ```
> botowners=  # Use name list or myfile.txt with one name per line
> ```
> 
> It allows specifying owners of the bot. This way only players mentioned in this line or the _myfile.txt (if specified)_ can execute certain commands. But, since the commonly used essentials plugin adds the _/nick_ command, players can change their player name into any name. Therefore a player changing their nickname to any name of the bot owners can execute the same code, which was only intended for authenticated usage.
> 
> _**This could not only damage vital parts of a server's infrastructure but is also in contradiction with the basic principles of the CIA+ key concepts for Information security.**_
> 
> ### PROBLEM LOCATION
> Since ChatBot.cs takes the sender and text of a message through a RegEx directly out of the chat. It will just match the nickname. Therefore it's really easy to just choose the same name as the bot owner and issue commands with their _permissions_.
> 
> ```
> ChatBot.cs:
> protected static bool IsPrivateMessage(string text, ref string message, ref string sender)
>         {
>             if (String.IsNullOrEmpty(text))
>                 return false;
> 
>             text = GetVerbatim(text);
> 
>             //User-defined regex for private chat messages
>             if (Settings.ChatFormat_Private != null)
>             {
>                 Match regexMatch = Settings.ChatFormat_Private.Match(text);
>                 if (regexMatch.Success && regexMatch.Groups.Count >= 3)
>                 {
>                     sender = regexMatch.Groups[1].Value;
>                     message = regexMatch.Groups[2].Value;
>                     return IsValidName(sender);
>                 }
>             }
> ```
> 
> ### EXAMINATIONS
> I and [@andreasgrafen](https://github.com/andreasgrafen) tested it. He created a bot where _botowners=lowo_ and I tried to message it in public chat. _(He used RegEx to get rid of the symbols in front of our names)_
> The bot should respond to the word "bot" in chat. But only if the owner _(lowo)_ initially sent it.
> ![image](https://user-images.githubusercontent.com/58081895/87888308-7f387680-ca2c-11ea-838b-e52178020238.png)
> Here you can see the bot responding when my name is "lowo" and it not responding when my name is "yuki".
> 
> ### MITIGATIONS
> Now how could we resolve the issue?
> 
> * ChatBot.cs could use the _/realname_ command provided by essentials (if available) which returns the real username of a player's nickname. This could get rid of this issue on servers running essentials*(which causes the issue in the first place)*
> * This issue doesn't exist on servers without a /nick function. Therefore no mitigations needed.


As far as I know Essentials / nick does not allow you to change your game nickname to the existing one, but this seems to have a workaround

**Comment by f2hafner** [comment]
> As far as I know Essentials /nick does not allow you to change your game nickname to the existing one, but this seems to have a workaround

A nickname can also use colors in most cases and that is why it's possible to choose the same name as someone else.
For Instance:
```
/nick &2Player
```
![image](https://user-images.githubusercontent.com/58081895/88048048-e6e8e180-cb52-11ea-9db7-6e9ccec7a894.png)
```
/nick &0Player
```
![image](https://user-images.githubusercontent.com/58081895/88048115-04b64680-cb53-11ea-91bb-022f8da6c1e9.png)

Both get you the same names (which MCC then gets as sender).

Now that Minecraft also supports colors outside the 16 color spectrum. It will get even more confusing.

**Comment by Nekiplay** [comment]
> > As far as I know Essentials /nick does not allow you to change your game nickname to the existing one, but this seems to have a workaround
> 
> A nickname can also use colors in most cases and that is why it's possible to choose the same name as someone else.
> For Instance:
> 
> ```
> /nick &2Player
> ```
> 
> ![image](https://user-images.githubusercontent.com/58081895/88048048-e6e8e180-cb52-11ea-9db7-6e9ccec7a894.png)
> 
> ```
> /nick &0Player
> ```
> 
> ![image](https://user-images.githubusercontent.com/58081895/88048115-04b64680-cb53-11ea-91bb-022f8da6c1e9.png)
> 
> Both get you the same names (which MCC then gets as sender).
> 
> Now that Minecraft also supports colors outside the 16 color spectrum. It will get even more confusing.

To get the exact nickname, I would make a plugin that would send the player's nickname to json, but it would not be visible to ordinary minecraft

**Comment by ORelio** [comment]
Installing a plugin would solve the issue only on your server.
