### ISSUE TITLE
Improvement of inventory command?

### ISSUE THREAD

**Issue by ReinforceZwei** [ORelio/Minecraft-Console-Client#1166]
The current inventory command syntax is pretty complex and do not have much instruction. I would like to improve it by:
 - changing it's syntax to `/inventory <sub-command> <args...>`
 - accessing opened container without knowing the ID
 - also adding more information/help

The only concern about changing command syntax is that might break everyone's script that uses this command. Should we do that then?

**Comment by ORelio** [comment]
FYI it is already possible to access container without the ID, just put `container` in place of the ID.
Yes, the command has become more complex than initially thought and could be reworked.
It _might_ be possible to rewrite old-style commands into new-style commands for backwards compatibility (if not too complicated to do, otherwise, well, don't bother).

**Comment by ReinforceZwei** [comment]
@ORelio Do you mean "keep" the old-style command syntax for backwards compatibility while adding new-style syntax?

**Comment by ReinforceZwei** [comment]
Okay, all sub-commands need the `inventoryId` parameter. Putting it at the first position is the best (which is current implementation). But still, the command description is a mess. I think I will change the command description part only and adding a help command.

**Comment by ORelio** [comment]
Either 1) keep old style but do not document it anymore or 2) "rewrite" the command to new format and pass it to the new handling code. Might be complicated to do, if its too complicated it's better to drop support for old style commands rather than introducing bugs.
