### ISSUE TITLE
Network Error / HTTPS connection to login server is blocked

### ISSUE THREAD

**Issue by boramtek05vng** [ORelio/Minecraft-Console-Client#1188]
Hi,
I have this problem when trying to login to MCS, I have tried to disable window firewall, change to a different wifi, use a different versions of MCS. It works when I open it on another laptop with the same wifi but does not work on my PC. Please help me!
![1](https://user-images.githubusercontent.com/69407233/89722779-b6f76600-d9bb-11ea-9b6d-11bf41623aca.jpg)

**Comment by ORelio** [comment]
You are not using the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts).

**Comment by boramtek05vng** [comment]
I did use it but it did not work so I tried a different version.
![1](https://user-images.githubusercontent.com/69407233/89737944-02088c00-da43-11ea-9eab-ee2c9e0ee245.jpg)

**Comment by ORelio** [comment]
Thanks for your report with the latest version. Your original screenshot contains your email and password. I redacted them, but recommend you to change your password immediately since other people may have it.

Regarding the issue, it seems like some software like antivirus software or firewall between you and the login servers are blocking the login attempt from Minecraft Console Client. What happens if you open https://authserver.mojang.com/ from your web browser on the same computer?

**Comment by boramtek05vng** [comment]
![image](https://user-images.githubusercontent.com/69407233/89741165-06da3980-da5d-11ea-8147-e6069df1e245.png)
I received this message! Thanks for redacting my email and password!

**Comment by ORelio** [comment]
Ok, seems like some software is definitely not properly intercepting your requests. Try disabling the feature in your antivirus that intercepts HTTPS requests. See example below for Avast, where the check box to disable is `Enable HTTPS scanning`:

![v2_configure](https://user-images.githubusercontent.com/1128206/89741337-b7adfc00-da90-11ea-9e6c-8ca3c93cbc67.png)

If that works and your Antivirus software allows it, I recommend to disable that feature for Minecraft Console Client only (i.e. allow Minecraft Console Client not to be scanned while still scanning your web browser for malicious sites), rather than disabling the setting globaly (less secure).

**Comment by boramtek05vng** [comment]
I don't have any Antivirus software installed, could you tell me how to do that for Window Defender?

**Comment by ORelio** [comment]
AFAIK Windows Defender does not cause this issue. Here are a few hints to help you solve your issue:
https://www.xtremerain.com/fix-err-cert-common-name-invalid/
If nothing works, I'm out of suggestions. This is not an issue with MCC but your computer's configuration 😕
