### ISSUE TITLE
Player entity distance trigger command

### ISSUE THREAD

**Issue by Voltikenzi** [ORelio/Minecraft-Console-Client#1202]
Any way to trigger your bot to run a script or cmd such as saying something when a player is withing a specific range?

**Comment by ORelio** [comment]
Currently, no. I think this could be done by taking [AutoAttack](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/ChatBots/AutoAttack.cs), making it track Player entities, and making it perform a command instead of attacking. But that's only a suggestion if you wish to implement that as a chatbot in a C# script.
