### ISSUE TITLE
terrainmovement crash due to Forge mod on server

### ISSUE THREAD

**Issue by interesting-233** [ORelio/Minecraft-Console-Client#1212]
when i enabled terrainandmovements, there's a chance will crash the application in some chunks in a modded server.
![image](https://user-images.githubusercontent.com/61296195/90333789-2f34db80-dffb-11ea-9196-a8b65bd1dd58.png)
Translate: Can't print exception string because failed to execute Exception.ToString()

**Comment by ReinforceZwei** [comment]
You are not posting the actual error message. 
真實的錯誤信息無法正確打印出來，所以你需要提供伺服器地址和位置，我們才能進行修復

**Comment by interesting-233** [comment]
> You are not posting the actual error message.
> 真實的錯誤信息無法正確打印出來，所以你需要提供伺服器地址和位置，我們才能進行修復

cn-zz-bgp.sakurafrp.com:33612 离线(盗版)服务器

**Comment by ReinforceZwei** [comment]
I can't even get any message, only a line of unhandled exception.
![image](https://user-images.githubusercontent.com/39955851/90334176-432e0c80-dffe-11ea-88d6-567f27a8609d.png)

**Comment by interesting-233** [comment]
![image](https://user-images.githubusercontent.com/61296195/90334328-8177fb80-dfff-11ea-87ec-bad177522c70.png)

**Comment by ReinforceZwei** [comment]
Sorry, I am not familiar with terrainmovement so I can't really help anything :cry:

**Comment by ORelio** [comment]
Glad to see that MCC is getting popular in China but it makes harder for me to read the error messages 😅

@interesting-233 Try removing the try/catch block so that your Visual Studio shows the exact place the exception is happening. I guess that some mod on the server is changing the terrain layout, it might not be fixable.

**Comment by interesting-233** [comment]
> Glad to see that MCC is getting popular in China but it makes harder for me to read the error messages 😅
> 
> @interesting-233 Try removing the try/catch block so that your Visual Studio shows the exact place the exception is happening. I guess that some mod on the server is changing the terrain layout, it might not be fixable.

![image](https://user-images.githubusercontent.com/61296195/90336959-c73dbf80-e011-11ea-84ea-1a8b02011934.png)

**Comment by ReinforceZwei** [comment]
The caller is:
![image](https://user-images.githubusercontent.com/39955851/90337185-6c0ccc80-e013-11ea-99a0-15b7179644f2.png)

**Comment by ReinforceZwei** [comment]
> Glad to see that MCC is getting popular in China but it makes harder for me to read the error messages 
> ...

@ORelio I could help reading and translating them anytime if you need :wink:

**Comment by ORelio** [comment]
Ok, so given the exact location of the error, my guess is that a mod on the server altered the chunk format, e.g. by adding some custom fields so that MCC tries to read the wrong field as a VarInt. Unfortunately, that makes it incompatible with the processing code in MCC that expects vanilla chunks. Although MCC is compatible with the Forge handshake protocol, it is not actually compatible with every mod out there because it stills behave as a vanilla client, so it might not work with some mods.

If you really want to make it compatible, you could list all mods installed on the server, guess which one is the culprit, find its source code, and determine how it affects the chunk structure, and finally accommodate these changes into a custom build of MCC.
