### ISSUE TITLE
Timeout detector is not working

### ISSUE THREAD

**Issue by ReinforceZwei** [ORelio/Minecraft-Console-Client#1219]
Platform: Windows 10 1803

I unplugged the network cable and plug it back while connected to a server. The client didn't detect this and show nothing (just like the linux mono disconnect issue, but I am on windows platform instead). _The client reacted after trying to type and send message._

Maybe the timeout detector is not even working at all?

**Comment by ReinforceZwei** [comment]
OMG maybe I just solved (work-around?) the silent disconnect issue. I was able to detect the connection lost I described above and auto-reconnect to the server. :tada::tada::tada: 
Now the question is, do my work-around also solve the mono silent disconnect issue? Since the silent disconnect issue takes some hours to be happened, I will do a overnight AFK with my fix on linux platform and we will see tomorrow.

**Comment by ORelio** [comment]
Weird, so the timeout detector was broken? 😮
If you manage to fix silent disconnects, that would be awesome 🥇

**Comment by ReinforceZwei** [comment]
The bot AFK over 14 hours and haven't lost connection. Usually it would be silent disconnected after 9-12 hours. I will keep AFK.

**Comment by ReinforceZwei** [comment]
> Weird, so the timeout detector was broken? 

I guess yes.
I have been testing the timeout detector by using a software to drop all packet between the client and server to simulate the connection timeout. And indeed, the timeout detector can't detect the timeout.

**Comment by ReinforceZwei** [comment]
@ORelio I have found the reason why the timeout detector is not working!! Calling `Abort()` instantly terminated the thread and the remaining code are not ran. I removed the `Abort()` and the client is able to detect the connection lost.
![image](https://user-images.githubusercontent.com/39955851/90642082-87bae180-e264-11ea-93ad-c9b2112ef1ea.png)

_But I don't know how to fix this since I have never touch threading before :(_

**Comment by ORelio** [comment]
[`OnConnectionLost()`](https://github.com/ORelio/Minecraft-Console-Client/blob/3adf7c44681897b172f51839e1dff3611ac97e93/MinecraftClient/McClient.cs#L478) is called when connection is lost, so it should print `Connection has been lost` and call each bot's `OnDisconnect()` method, that's why it stops the timeout detector: it should not be necessary anymore since connection lost is already detected... But I think I found what's wrong with it: When the timeout detector detects a timeout, it invokes `OnConnectionLost()`... from within the `timeoutdetector` thread. So, calling `timeoutdetector.Abort()` will instantly kill the thread: that's equivalent to doing a `return` statement: the rest of the method is not executed.

**Comment by ReinforceZwei** [comment]
We can set a flag when a timeout detector detected a connection lost and check the flag in the McClient OnUpdate event. Or we don't even need a new thread for detecting timeout. Just do what I had do in the Checker ChatBot.

**Comment by ORelio** [comment]
Added a check to prevent the timeout detector thread from killing itself.
