### ISSUE TITLE
IP blacklisted, incorrect password, or too many logins

### ISSUE THREAD

**Issue by ivanpro229** [ORelio/Minecraft-Console-Client#1234]
Ive been using the console client to afk on factions, but also to afk vote keys on there. When my wi fi router resets, all alts instead of just logging back in like theyre supposed to, they "crash", well i mean "IP blacklisted, incorrect password or too many logins" pops up.

**Comment by ZizzyDizzyMC** [comment]
This is likely because they all try to login again at one time.  You can solve this by creating a script to delay their login from one another.  
My recommendation is having them not try to log themselves in, and when they crash that's when you have 1 of them activate the script.  The script should make sure the rest of them are closed, then begin the process of starting each one up with a delay between each one.

**Comment by ivanpro229** [comment]
Im not really into coding, could someone maybe help me out and explain me what to do

**Comment by ORelio** [comment]
Example of .bat file (create it with notepad and give it .bat extension)
```batch
start /min MinecraftClient.exe Login1 Password1 Server1
timeout 10
start /min MinecraftClient.exe Login2 Password2 Server2
timeout 10
start /min MinecraftClient.exe Login3 Password3 Server3
timeout 10
```
And so on.
