### ISSUE TITLE
No movement on a server.

### ISSUE THREAD

**Issue by HLG42** [ORelio/Minecraft-Console-Client#126]
Hello ORelio! I have recently found the MCC and have been getting it to work on CosmicPvP. Currently, I have finished the whisper system, and added a quick command system (with plans to edit it more for greater use). But the issue that I have ran into is that on the server, the MCC does not move the characters at all. They are floating in lobbies, and refuse to move from anything in game (ie combat, explosion, water, lava, or falling). Any idea what could cause this? Attached is the cosmic whisper system, the rough keywords code, and a video demonstrating some of the issues.

[MinecraftClient.zip](https://github.com/ORelio/Minecraft-Console-Client/files/158114/MinecraftClient.zip)

[https://youtu.be/0rN-vjG9rPM](url)

**Comment by initsuj** [comment]
I believe that terrain movement is still in early development. Are you using the latest dev build with terrainandmovements=true set in the ini file? Falling to the ground should work, but I don't know on the water pushing.

Additionally, you should be able to use a custom regex in the ini to parse the messages on CosmicPVP rather than adjust source code.

**Comment by ORelio** [comment]
Hello,

The stable release of MCC is quite outdated, another one is planned once `1.9` support is added. Stable version cannot know what is surrounding it, so it cannot determine if it should move, because yes, it's the client that move by itself, the server won't tell it to move.

![noautorespond](https://cloud.githubusercontent.com/assets/1128206/13523346/34b6af56-e1f5-11e5-9c93-b70b48163eac.png)

As you do not have the `AutoRespond.cs` source file I guess you are using code from the `master` branch of the repository, or zipfile for stable release from the forum thread. I'd advise you to use [development builds](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts) and/or code from the `Indev` branch. Development builds have basic movement handling as @initsuj pointed out (no water pushing at the moment), and moreover you can handle custom chat formats simply by specifying a regex in the configuration file.

So except for `RemoteControl` shortcuts you should not need to edit the code. And even for that, you could make a `.cs` script containing a fork of `RemoteControl.cs`, allowing to use your custom bot with development builds without changes to the core app's code :)

You can find Indev documentation in this [config](https://github.com/ORelio/Minecraft-Console-Client/tree/Indev/MinecraftClient/config) directory ;)
