### ISSUE TITLE
AppVeyor build triggers Windows Defender

### ISSUE THREAD

**Issue by iBossMind** [ORelio/Minecraft-Console-Client#1267]
Windows Defender detect that MCC has this virus:
 - Trojan:Win32/Fuery.C!cl
 - Trojan:Win32/Wacatac.D2!ml
 - Program:Win32/Wacapew.C!ml
Please give a feedback if this is normal, thank you

**Comment by ReinforceZwei** [comment]
Hi, MCC does not contain any trojan. You may check the source code to verify it. Also please make sure you download the MCC from a trusted sources, i.e. GitHub.

May I ask where did you download the MCC?

**Comment by iBossMind** [comment]
from here, i just did the virustotal thing
https://www.virustotal.com/gui/url/e8769d877fc80f6bf20db32532bd6b1589c8ce4109330afd792a54a6d3969c98/detection
its totally safe using this?

**Comment by ReinforceZwei** [comment]
Indeed the newest build of MCC did triggered Windows Defender, and only occurs with that build (after commit [a38c9dd0](https://github.com/ORelio/Minecraft-Console-Client/commit/a38c9dd0004112e14334349f2afaac9ea6ee8eff)). That commit didn't add any new code to the program itself, so it should be totally safe to use. If you still feeling worried, you may download the previous build from the download page https://ci.appveyor.com/project/ORelio/minecraft-console-client/history . My Windows Defender reported the previous build is safe.

@ORelio Do you have any idea what is going on?

**Comment by ORelio** [comment]
We had this once before: #707 - Seems like on rare occasions AppVeyor builds can get infected for some reasons.
I'd happily switch MCC builds to another, safer build service if you can suggest one that is free to use.
Meanwhile, I triggered a new build by merging a pull request, the newer build should be safe to use.

**Comment by Mhowser** [comment]
Is Github CI good enough?

**Comment by ORelio** [comment]
It might, if there is a way to keep the `exe` file and make it available for download.

**Comment by TheSnoozer** [comment]
I did some experimenting with github actions. In summary it is certainly possible to build the Minecraft client with github actions (see [here](https://github.com/TheSnoozer/Minecraft-Console-Client/blob/github-actions/.github/workflows/build.yml)). 

I somewhat find it cumbersome that
- it feels cumbersome to test the build script definition locally (which is IMHO honestly the case for all build script definitions; a way around seems [act](https://github.com/nektos/act) but that comes with limitations)
- it is currently impossible to provide hard-links to the 'latest' release ([tracked here](https://github.com/actions/upload-artifact/issues/52)). In specific that makes the entire github action feeling not very integrated. If a user wants to download the latest build one need to open the [actions](https://github.com/TheSnoozer/Minecraft-Console-Client/actions)-Tab  and from there click on the latest build (e.g. [this](https://github.com/TheSnoozer/Minecraft-Console-Client/actions/runs/283222187)). A potential other way would be by clicking on the green checkmark on the latest commit that is almost invisible if one doesn't know about it.
- Artifact download may only work for registered users ([tracked here](https://github.com/actions/upload-artifact/issues/51))

As a side-note: With gitlab action the process could also create a release that comes with artifacts (e.g. [see here](https://github.com/marketplace/actions/upload-a-release-asset)). However creating a release for very commit somewhat feels overkill. Deleting old releases also sounds like a hack, since this would throw away a git-tag.

**Comment by ORelio** [comment]
Hi @TheSnoozer, thanks for investigating GitHub actions, the result looks very nice, it's too bad that guest users cannot download  the build (and no direct link to latest build job) because it indeed makes it unusable for casual users 😦

**Comment by ORelio** [comment]
Hi @TheSnoozer just to let you know that the missing piece in the workflow you worked on (auto-publishing in releases) was found in #1854 so from now on GitHub actions for releasing MCC are a thing! Thanks for your help 👍

**Comment by ORelio** [comment]
@iBossMind Just for your information, we have now switched to releases built through GitHub Actions, which completely circumvents AppVeyor and its unreliability regarding viruses 😉

**Comment by TheSnoozer** [comment]
Cool stuff, glad you got it working and found a viable solution!
