### ISSUE TITLE
Add keyboard for special actions

### ISSUE THREAD

**Issue by Chtholly** [ORelio/Minecraft-Console-Client#1270]
On some Servers there you have to press special Keys, like press letters or letters + mouse for some actions like when need to click multiple keys in an inventory.

Would be nice if we can write in a config file the keys, that should be defined and use this than via command
- Command **/key <>** and **/key <> + <>**
- Keys: a-z, 0-9,  Lclick,  Rclick 

Should also work:
-  when inventories opened
(Would make drop items which are in the hand easier)

**Comment by ReinforceZwei** [comment]
Actually server doesn't know what key client had pressed if the key doesn't have any functionality. The key must have some related actions (i.e. pressing key 1-9 for switching slots, pressing F for switching off-hand item) so that the server can listen and catch the corresponding packet.

As we can send whatever packet we want, there is no point making a command for inputting vanilla raw key press then translate them back to an action using vanilla logic. We could just make a command for that action directly.
