### ISSUE TITLE
Add support for translating MCC to other languages

### ISSUE THREAD

**Issue by XIAYM-gh** [ORelio/Minecraft-Console-Client#1272]
**Prerequisites**
 - [Yes] I have read and understood the [user manual](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config)
 - [Yes] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
 - [Yes] I tried to [look for similar questions](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before creating a new one

(Sorry my English is not good)
I really like this program because it brings me a lot of fun :)
I translated this program with my friend and I want to post it on MCBBS(From China's Minecraft Forum)..

(I will post it with your github&AppVayor link)
(It may be late because my friend was sent the same issuse..)
Agree it please..

**Comment by XIAYM-gh** [comment]
and the project link is:
github.com/XIAYM-gh/Minecraft-Console-Client-ChineseTranslate

**Comment by ReinforceZwei** [comment]
Replying your question about sharing MCC on other forum, you can. See #1039
> Feel free to share MCC with anyone you want, please link to the repository as source

**Comment by XIAYM-gh** [comment]
oh thx

**Comment by XIAYM-gh** [comment]
oh thanks

**Comment by ORelio** [comment]
Quoting https://github.com/ORelio/Minecraft-Console-Client/issues/1271#issuecomment-704468232
> It would be best to implement translation support and add Chinese translation. Less work for you in the long run 😉
> Here's a sample class I wrote in the past for that:
> https://github.com/ORelio/Sharp-Tools/blob/master/Utility/Translations.cs
> Also you're fine to post your modified version as long as you provide source code and link to this project. See [license](https://github.com/ORelio/Minecraft-Console-Client#license).

**Comment by ReinforceZwei** [comment]
@ORelio I like the idea using a translation file for MCC messages and I am willing to take the job. I may add the translation handler in `ConsoleIO` and listen for specific string combination (e.g. `{{MSG}}`) to translate messages so that we don't need to call `Translations.Get()` method for every log line manually. Is that okay?

**Comment by XIAYM-gh** [comment]
> Quoting [#1271 (comment)](https://github.com/ORelio/Minecraft-Console-Client/issues/1271#issuecomment-704468232)
> 
> > It would be best to implement translation support and add Chinese translation. Less work for you in the long run 😉
> > Here's a sample class I wrote in the past for that:
> > https://github.com/ORelio/Sharp-Tools/blob/master/Utility/Translations.cs
> > Also you're fine to post your modified version as long as you provide source code and link to this project. See [license](https://github.com/ORelio/Minecraft-Console-Client#license).

Oh yes,but I need an example translate file because I can't understand them.
I really hope you can tell me how to custom them..
Do them like Minecraft's translate file?

**Comment by ORelio** [comment]
@XIAYM-gh Just wait for now because Minecraft Console Client does **not** have support for translation files **yet** 😄

> @ORelio I like the idea using a translation file for MCC messages and I am willing to take the job. I may add the translation handler in `ConsoleIO` and listen for specific string combination (e.g. `{{MSG}}`) to translate messages so that we don't need to call `Translations.Get()` method for every log line manually. Is that okay?

Thanks for offering your help, I'll reopen this issue then. However, the approach you are suggesting will likely pose an issue because chat messages are also printed using `ConsoleIO` so a player could put `{{MSG}}` in chat and have it translated in MCC while it should not happen. I would suggest something like this instead:

```C#
Translations.WriteLine("some_message", <optional arguments here>)
```
Then `Translations` would format the message and pass it to `ConsoleIO`.
Formatting the message could work by taking the optional arguments and calling `String.Format` when optional args are present
Then translation messages can use `{0}`, `{1}` and so on for placeholders.
Untranslated messages would be printed using `ConsoleIO` directly.

If you need help getting started, I can adapt the `Translations` class for you and then let you handle the translation stuff 😉

**Comment by ORelio** [comment]
Continued in pull request: #1273

**Comment by XIAYM-gh** [comment]
Humm.. Can I have a question?
Can I use color code in translate files? Can I use the old ConsoleIO's "WriteLineFormatted" in some text?

**Comment by ReinforceZwei** [comment]
@XIAYM-gh Hmm...不如我用中文回答。翻譯文件中，有些句子裡已經有顏色碼，就可以再加顏色。原本沒有顏色碼的，就不能自己加上去，會沒效果。

**Comment by ORelio** [comment]
You may respond in Chinese, please also include an English version for anyone else.
> 不如我用中文回答。翻譯文件中，有些句子裡已經有顏色碼，就可以再加顏色。原本沒有顏色碼的，就不能自己加上去，會沒效果。

_Google Translated:_
> Why don't I answer in Chinese. In the translation file, some sentences already have color codes, you can add colors. If there is no color code, you can't add it yourself, it will be useless.

Yes, you will be able to use `§c` color codes in translations.

**Comment by ReinforceZwei** [comment]
Sorry :P
I will do it next time.

**Comment by XIAYM-gh** [comment]
I usually make "Console.WriteLine" to "ConsoleIO.WriteLineFromatted" , but I can't change the color in some text..
(e.g. "Username:", If I use CIO.WLF,I type some text in it,it will show the text in next line.)
How can I change their color?

Chinese ver:
我经常让"Console.WriteLine"变为"ConsoleIO.WLF",但是我在一些文本里不能更改颜色..
(就像启动时的 "账号:" ,如果我改变了它为ConsoleIO.WLF,输入用户名时会在下一行显示，输入密码也是这样)
我该如何改变他们的颜色?

**Comment by ReinforceZwei** [comment]
I don't think you could change the text color of user input. WriteLineFormatted only handles text output.

**Comment by ORelio** [comment]
Why would you need colors in user input?

**Comment by XIAYM-gh** [comment]
humm ok..
