### ISSUE TITLE
What version of the raspberry pi is recommended for MCC

### ISSUE THREAD

**Issue by several5** [ORelio/Minecraft-Console-Client#1306]
I've been looking to buy a raspberry pi but i'm not sure which model is easy to setup & won't cause problems running 4+ clients.

What raspberry pi's do you use or recommend?

Would a Raspberry pi zero w be enough to run multiple clients?

**Comment by ORelio** [comment]
I would not recommend a Pi Zero for now due to #1303 and [many other issues](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue+pi). Actually, the Mono framework seems unreliable on the Pi. However I was able to run MCC without terrain handling on a model B+ (first gen, similar CPU as Pi Zero) running Raspbian without GUI in the past so you should be able to use almost any Raspberry Pi: https://en.wikipedia.org/wiki/Raspberry_Pi#Specifications provided it has 512MB RAM at least.

If you want to run MCC 24/7, for now I'd suggest to recycle an old PC or Laptop which can run Windows and the original .NET framework 4.0 or greater, it's the most reliable option at the moment.

However this may change in the near future since .NET 5 is getting released for Linux: https://dotnet.microsoft.com/download/dotnet/5.0 - maybe this will work on Raspberry Pi and allow to reliably run MCC on Linux but this is pretty new and untested yet.

**Comment by OverHash** [comment]
I've ran off a 3B+ for the past few months, not a problem.

**Comment by mexiscool** [comment]
For me, it works pretty well on my pi 4B 2gb with only chat enabled (and a passive heatsink), using screens too. Can confirm it times out if connecting with terrain or entity handling. I do think it can handle 4 chat clients if you don't have them join at the same time. When I used entity and terrain handling for a gold farm I used a vps for 4 euro per month with 2 amd epyc cores and 4gb ram.

**Comment by several5** [comment]
@ORelio Have you had any experience/knowledge about running windows10 on a raspberry with mcc.

Would that be a relevant option?

**Comment by several5** [comment]
@mexiscool What vps hosting did you use? and was it easy to setup?

**Comment by ReinforceZwei** [comment]
> Have you had any experience/knowledge about running windows10 on a raspberry with mcc.
I don't think it is a good idea to install Windows 10 on a raspberry pi since ARM version of Windows doesn't perform well, nearly unusable.

**Comment by mexiscool** [comment]
I used Hetzner cloud it's pretty nice you pay per hour with a monthly maximum. I find it pretty easy to setup. If you try it, don't forget to first run 'sudo apt update' otherwise nothing works. You would need to move or download the .exe with Filezilla or download it with commands instead of putting it on an sd card. But from that, it's the same as a pi. What I would do if you try it this way is test if the cheapest one for 3 euro per month is fast enough and otherwise upgrade/delete and try a little faster one.

**Comment by ORelio** [comment]
> @ORelio Have you had any experience/knowledge about running windows10 on a raspberry with mcc.

No, since you can't do that on a first-gen Pi.

**Comment by several5** [comment]
Thanks to everyone for responding! I appreciate it.
