### ISSUE TITLE
Server matches regex ?

### ISSUE THREAD

**Issue by jpruezkiez** [ORelio/Minecraft-Console-Client#1314]
Hello, sorry for bothering with this easy questions.

I tried to use matches.ini, but the console isn't detecting the chat.

i would like some help with the regex or what to do. 
![image](https://user-images.githubusercontent.com/49831707/98243699-50db9a00-1f3c-11eb-99ca-b717ecf7b68d.png)

server chat looks like this, i tried with the match: 
[Match]
match=**Prohibited [Warlord] Raphtalia [KoTH]: wawie
action=send shut up cita

i would appreciate any help.

**Comment by several5** [comment]
Try this:

[Match]
match=**Prohibited [Warlord] Raphtalia [KoTH]: wawie
actionother=send shut up cita
ownersonly=false

**Comment by ORelio** [comment]
As per [detecting chat messages](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config#detecting-chat-messages) you need to make sure MCC properly detects the chat messages or AutoRespond won't work as intended. Of course ActionOther might do what you want but it's less reliable because this means MCC is not considering the message as a chat message. You won't be able to watch the bot owner or extract the username.

**Comment by jpruezkiez** [comment]
still not detecting my messages ;(

**Comment by ReinforceZwei** [comment]
I saw some words were bolded. Could it be the problem?

**Comment by jpruezkiez** [comment]
> I saw some words were bolded. Could it be the problem?

maybe it's i mananged to get basic message, but how to i set owners ?

**Comment by ORelio** [comment]
As I said in my link, you need to define a custom regular expression in MCC settings to properly decode chat messages.
Test your regex on https://regex101.com/
