### ISSUE TITLE
How to disable AutoRespond message delay

### ISSUE THREAD

**Issue by EchoesNetwork** [ORelio/Minecraft-Console-Client#1317]
Hi, after the latest build of MCC for 1.16.4, i've noticed that theres a delay between when commands are executed if i have multiple matches in the `matches.ini` file for the same string of text. For example, if i have the following:

```
[Match]
regex=^.*\G!help\z.*$
action=send Click this link to view my commands:

[Match]
regex=^.*\G!help\z.*$
action=send /tellraw @a ["",{"text":"https://echoes.fun/commands","color":"blue","underlined":true,"clickEvent":{"action":"open_url","value":"https://echoes.fun/commands"}}]

[Match]
regex=^.*\G!help\z.*$
action=send And click this link to view a list of recently-added server features:

[Match]
regex=^.*\G!help\z.*$
action=send /tellraw @a ["",{"text":"https://echoes.fun/blog","color":"blue","underlined":true,"clickEvent":{"action":"open_url","value":"https://echoes.fun/blog"}}]
```

before 1.16.4, all these commands would be executed simultaneously. Now, there's a 1-2 second delay between each message. Sometimes the delay is exacerbated if the bot hasn't restarted in a long time. I thought maybe it could be a new setting in `MinecraftClient.ini`, so I set both `splitmessagedelay=` and `botmessagedelay=` to 0, but the delay persists. I'm not sure if I'm missing something, but if there's a way to fix this or if anyone knows what's causing it, please let me know. Thanks!

**Comment by ReinforceZwei** [comment]
The key name for setting message delay was changed to `messagecooldown`. You can add `messagecooldown=0` to the `[Main]` section of your original config file.

**Comment by ORelio** [comment]
Hi @EchoesNetwork,

The `botmessagedelay` and `splitmessagedelay` were merged into a global `messagecooldown` setting exactly because AutoRespond was bypassing the bot message delay, causing people to get kicked. Of course, if you will never get kicked for spamming you can disable the delay as instructed by @ReinforceZwei, see also the newest [MinecraftClient.ini](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/Resources/config/MinecraftClient.ini).

Related issue: #661
Related commit: 916903689346f4878c5409e8c2ee1b183638fb52
