### ISSUE TITLE
Upgrade to 1.9.2

### ISSUE THREAD

**Issue by Cat7373** [ORelio/Minecraft-Console-Client#135]
protocol v107 can be directly used by the test Spigot 1.9.2

**Comment by Pokechu22** [comment]
Actually, there is a minute change between them: [join game now uses an int instead of a byte for dimension](http://wiki.vg/index.php?title=Pre-release_protocol&oldid=7552#Join_Game).  That said, this change doesn't seem to affect MCC from what I can tell.

**Comment by ORelio** [comment]
Indeed, there is only that change network-side, and although the `Join Game` packet is handled, its contents are ignored because we don't need them, so MCC isn't affected by the change. Protocol v108 can therefore be safely added to the handled protocol list. Just added that in development builds :)

**Comment by Pokechu22** [comment]
FYI, 1.9.2 actually uses protocol v109 instead of v108 (probably to force realms users to update since realms was broken in 1.9.1).

I can verify using Burger that there weren't any protocol changes between 1.9.1 and 1.9.2 other than protocol versions.

**Comment by ORelio** [comment]
Oh, that wasn't mentioned on the wiki. Updated. Thanks ;)
