### ISSUE TITLE
Mojang/Microsoft Account Transition

### ISSUE THREAD

**Issue by JacksonWillford** [ORelio/Minecraft-Console-Client#1379]
**Prerequisites**
 - [x] I have read and understood the [user manual](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config)
 - [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
 - [X] I tried to [look for similar questions](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before creating a new one

Good evening,

Mojang will be migrating its existing accounts to Microsoft accounts in the near future. I wanted to pose the question to you on whether Minecraft Console Client will support the new accounts after the migration. Thank you for your time.

**Comment by tunkusalim** [comment]
I have related question too, since new account creation is using microsoft accounts instead of mojang account, i cant connect my new account using console client.
i tried using the microsoft account as login but its shows error
```
Resolving someserver.com...
Connecting to Minecraft.net...
Minecraft Login failed : Incorrect password, blacklisted IP or too many logins.
12:59:59 Not connected to any server. Use '/help' for help.
12:59:59 Or press Enter to exit Minecraft Console Client.
```

with the same config
```
[Main]
# General settings
# Leave blank to prompt user on startup
# Use "-" as password for offline mode
login=micosoftaccount@outlook.com
password=microsoftpassword
serverip=someserver.com
```

**Comment by Mhowser** [comment]
They haven't started the migration yet, login with your standard mojang
account.

**Comment by ReinforceZwei** [comment]
Since https://wiki.vg/Microsoft_Authentication_Scheme told us to create a Microsoft Azure application but I don't want to do that. I followed https://github.com/XboxReplay/xboxlive-auth/ s'steps so that we can skip the Microsoft Azure application part. Also this method doesn't require browser/webview.


User-Agent: `Mozilla/5.0 (XboxReplay; XboxLiveAuth/3.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36`

Step 1
---

GET `https://login.live.com/oauth20_authorize.srf?client_id=000000004C12AE6F&redirect_uri=https://login.live.com/oauth20_desktop.srf&scope=service::user.auth.xboxlive.com::MBI_SSL&display=touch&response_type=token&locale=en`

Will return a HTML. Extract urlPost and PPFT value from it and save them.
See https://github.com/XboxReplay/xboxlive-auth/blob/1ae09c0257f05a0b14559f7559cf04ec49b42f4c/src/core/live/index.ts#L54-L55 for regex

Example values:
    PPFT: `DVCSVDkO0Rp3uJ*sEwr7OG*JLpsqU7Wo3RR79vhBxJFEe007jwbwJc*wH95AqyUzlwhUxS*a4v5Z35V9xrnbu7P76yVQgdXidAiJ93*hgwhY7OExVGKqMMX9yQYAY8QHDqai0CTc9hzhsGFbY4FuVLibQWcoyv0d3iuW2kXU9REcVi7UHcDFeR4zP2fhO6ue*cNp5*F!yfp**yVlHxcT*Ok$`
    

    urlPost: https://login.live.com/ppsecure/post.srf?client_id=000000004C12AE6F&redirect_uri=https://login.live.com/oauth20_desktop.srf&scope=service::user.auth.xboxlive.com::MBI_SSL&display=touch&response_type=token&locale=en&contextid=B28190952B682909&bk=1608642121&uaid=722f98363efc4cfe9ebb90750e488d11&pid=15216




Also save the cookies from header

Step 2
---

POST `urlPost` (url obtained in step 1)

Headers
Content-Type: application/x-www-form-urlencoded
Cookie: (cookies saved in step 1)

Body
login=(email)
loginfmt=(email)
passwd=(password)
PPFT=(value obtained in step 1)

Will return 302 redirect. Save the redirect URL and follow the redirect.

Step 3
---

Extract access token (and refresh token) from the saved URL in step 2.
They are in the url hash part and in query string format
```
i.e. http://someurl.net/somepath#access_token=mytoken&refresh_token=sometoken
                                ^
                                (after the hash)
```
Save those token

Step 4
---

Follow https://wiki.vg/Microsoft_Authentication_Scheme#Authenticate_with_XBL . All steps afterward will be the same.

**Comment by ReinforceZwei** [comment]
I have made a basic implementation of the scheme. All the code are in https://github.com/ReinforceZwei/minecraft-msa
I haven't fully test it as I don't have a Microsoft account of Minecraft. Any help would be appreciated.

**Comment by Mhowser** [comment]
@ReinforceZwei is this msa version feature complete enough for what we need? 

https://github.com/minecraft-linux/msa-daemon

From the discussion in #1286

**Comment by ReinforceZwei** [comment]
@Mhowser  Except there's few bugs and I haven't fully tested it, it is barely completed. The final output of the program would be the player name and player UUID.

**Comment by Mhowser** [comment]
Sorry, I was asking if the msa component from the Minecraft-linux project would be suitable to use for this repository.

**Comment by ReinforceZwei** [comment]
I don't think so. That project is written in C++.

**Comment by Mhowser** [comment]
C# and C++ are too different?

**Comment by ReinforceZwei** [comment]
They are two different language.

**Comment by ReinforceZwei** [comment]
If someone own a Microsoft Minecraft account and willing to help me test my program, please tell me :smile:

**Comment by ORelio** [comment]
Currently I do not own any either 😕

**Comment by NovaDragonYT** [comment]
> Currently I do not own any either 😕



> If someone owns a Microsoft Minecraft account and willing to help me test my program, please tell me 😄

Hello, I just got an account hopping it would work and then ran into this exact problem I would love to help out I'm not active on here nearly ever so if you want to talk and figure this thing out feel free to add my discord. NovaDragonYT#2141

**Comment by TheRainbowMtnDew** [comment]
i have a microsoft minecraft account, and am willing to help if needed
add me on discord TheRainbow#1033

**Comment by ReinforceZwei** [comment]
Thanks for @TheRainbowMtnDew giving his/her help. My [`basic implementation of the scheme`](https://github.com/ReinforceZwei/minecraft-msa) did work. We can integrate the scheme into MCC now.
