### ISSUE TITLE
Please continue updating github releases.

### ISSUE THREAD

**Issue by boehs** [ORelio/Minecraft-Console-Client#1388]
Its pretty confusing having a releases page on github but not leaving it up to date. could you guys try and add releases to it? 

cheers
Evan

**Comment by ORelio** [comment]
Given the amount of development builts it is simply too much work to manually post builds on the Releases section. There is already a message stating that on the latest release, just added some colorful emojis so you can see the message better.

**Comment by ReinforceZwei** [comment]
I remember that Github action is able to create a release. Maybe we could use Github action to build the project instead of Appveyor?

**Comment by ORelio** [comment]
@TheSnoozer [worked on implementing GitHub actions](https://github.com/ORelio/Minecraft-Console-Client/issues/1267#issuecomment-702435013) but unfortunately you need a GitHub account to download the actifact.

**Comment by ReinforceZwei** [comment]
It is not the case when using Github release. People without account can still download artifact from release.

**Comment by ReinforceZwei** [comment]
I made a [test release](https://github.com/ReinforceZwei/Minecraft-Console-Client/releases/tag/3efdf4c) and I am able to download the `MinecraftClient.exe` using browser incognito mode (simulate no account). Would you consider using Github action?

**Comment by TheSnoozer** [comment]
Certainly github action would be able to create releases (e.g. [via](https://github.com/actions/create-release) or [via](https://github.com/marketplace/actions/automatic-releases)). The downside would be that a release is ultimately a tag. IMHO creating a tag for every commit somewhat feels overkill. Deleting old releases also sounds like a hack, since this would throw away a git-tag.

Perhaps this project could get away with https://nightly.link/that is mentioned as workaround in https://github.com/actions/upload-artifact/issues/51#issuecomment-735989475.
However all this feels very very annoying and I personally would rather wait until such feature is available in github action.

**Comment by boehs** [comment]
three ideas

* building automatically after 25 commits
* build when a commit with a commit message containing `MAJOR` is pushed
* Leave a human in charge of commiting major changes. I dont have any experience with this project, but if you wanted to I could try to handle it
