### ISSUE TITLE
Chunk loading server-side?

### ISSUE THREAD

**Issue by marklai1998** [ORelio/Minecraft-Console-Client#140]
I'm going to use it for afking a server for my iron farm
just want to see if it can load any chunk because it is a fake player
if so, how much chunk will load

**Comment by ORelio** [comment]
Not sure of what do you mean but yes if you connect using this program the server will load surrounding chunks in its own memory like with any player connecting to the server.

**Comment by marklai1998** [comment]
cuz i'm having a iron farm on the server, which is 50 block radius
in order to make it running, i nee to load all thhe chunks
but it depends on the player's render distance
the further it is, the more chunk load 
so can you searching up for me??
cuz i know many people use it to afk farm etc.

**Comment by ORelio** [comment]
The server has its own render distance setting, it does not depend on yours. Default `view-distance` is 10 chunk radius. http://minecraft-fr.gamepedia.com/Server.properties

**Comment by marklai1998** [comment]
but i can still load more chunks on server by turning up the render distance
up to 32~
Y

**Comment by ORelio** [comment]
The server will only load and _update_ a radius of 10 chunks around you, but if you raise view distance to far, already loaded chunks will stay visible until they get out of range of _your_ view distance.

**Comment by Pokechu22** [comment]
The client does tell the server its render distance, though, in the [client settings](http://wiki.vg/Protocol#Client_Settings) packet.  It doesn't look like MCC sends that packet.  However, I'm not sure what the server's default behavior is; I _think_ it defaults to 10 chunks when the client settings packet is not sent.

**Comment by ORelio** [comment]
Strange, the wiki states for `view-distance` that it determines the server-side viewing distance:
 > Sets the amount of world data the server sends the client, measured in chunks in each direction of the player (radius, not diameter). It determines the server-side viewing distance.
> _10 is the default/recommended. If you have major lag, reduce this value._

As it is lag-related, if the client-side value was used, a client could purposefully cause lags by setting it to 255. However maybe the server takes into account the client settings in order to adapt [chunk unloads](http://wiki.vg/Protocol#Unload_Chunk)?
> **Unload Chunk**
> Tells the client to unload a chunk column.

Seems like the client waits for this message from the server and don't unload chunks on its own, so the server needs the viewing distance to know which distance from the chunk should trigger a chunk unload.

**Comment by marklai1998** [comment]
so can anyone figure it out what's going on?

**Comment by ORelio** [comment]
1) client logs in
2) server loads 10-chunk radius server-side (or other value defined in server.properties)
3) client tells server its own render distance (else server assumes a default value)
4) server sends 10-chunk radius around the client so that you can see them and walk around
5) client moves around, sends updated location to the server
6) server loads 10-chunk radius server-side around the client, unloads the rest
7) server sends 10-chunk radius around the client, and tells it to unload chunks that are too far based on client render distance.

So even if you can _view_ the whole farm, only 10 chunks around you actually get updated unless some other player is present near them. If you could force the server to update more chunks, that would be a flaw allowing to purposefully cause server lag so even if I didn't dig the server's source code to verify this, I'm pretty sure that the above mechanism is what happens. Render distance is sent to the server because the client cannot request chuks, the server automatically determines if chunks should be sent to you, or unloaded, so the server needs your render distance to manage chunk unloading (else, if your render distance is set to far, the server would unload chunks that are not far enough, and if the client automatically handled chunk unloadings, the server wouldn't know that you need them to be sent again if you walk toward them again).

**Comment by marklai1998** [comment]
i see, that mean tune up the client side view distance will create non update chunks/fake chunks

**Comment by ORelio** [comment]
That issue seems solved, feel free to reopen if needed.
