### ISSUE TITLE
Unused parameter

### ISSUE THREAD

**Issue by 8cw** [ORelio/Minecraft-Console-Client#1465]
**Prerequisites**
 - [X] I have read and understood the [user manual](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config)
 - [X] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
 - [X] I tried to [look for similar questions](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before creating a new one

---
## Description of the Question
https://github.com/ORelio/Minecraft-Console-Client/blob/9d41e2223dba453864a481eb1f433e4b90d96e47/MinecraftClient/ChatBot.cs#L361

Why is the parameter `SendImmediately` unused here?

**Comment by ORelio** [comment]
To avoid being kicked for spamming, the ChatBot API contained a message queue, which could be bypassed using the `SendImmediately` parameter if needed. But it did not work well because some built-in bots such as AutoRespond were not compatible with it (#661) so the message queue was reworked in commit 916903689346f4878c5409e8c2ee1b183638fb52 to implement a program-wide message queue instead. The `SendImmediately` parameter has no effect anymore and is only there to avoid breaking existing scripts.

**Comment by ORelio** [comment]
I'll close the issue as resolved but feel free to reopen if you still have questions about this.
