### ISSUE TITLE
System.OverflowException: Value was either too large or too small for an Int32.

### ISSUE THREAD

**Issue by pxrnz** [ORelio/Minecraft-Console-Client#1507]
I can't connect to the server

Output:
`Using Minecraft version 1.7.10 (protocol v5)
Checking if server is running Forge...
System.OverflowException: Value was either too large or too small for an Int32.
Server reports a different version than manually set. Login may not work.
Failed to ping this IP.`

I've tried a couple things and the new version of "MinecraftClient.exe" seems to be the problem.
Because it works fine with the old version.

**Comment by pxrnz** [comment]
With a little more troubleshooting i found out it's the ServerAutodetectForge Function.

By disabling this it works perfect :)

**Comment by ORelio** [comment]
Indeed, thanks to your report, I just noticed that Minecraft Console Client attempts an old-gen server check first (Minecraft 1.6 and lower) and then the newer check (Minecraft 1.7+). Since Minecraft 1.6 is now very old and that may prevent Forge detection from working properly, I just changed the behaviour to use the newer ping by default, and the older one as fallback. Hope this helps.
