### ISSUE TITLE
Minecraft Error

### ISSUE THREAD

**Issue by D4niele-git** [ORelio/Minecraft-Console-Client#1509]
After a day / two days that the consoleclient is switched on, this error appears to me, can you tell me why and how can I solve it? I have seen the discussions of other users and tried to follow the guides as well, but the problem persists.

Restarting Minecraft Console Client... Performing request to authserver.mojang.com Cached session is invalid or expired. Connecting to Minecraft.net...

---
## Specifications

  - Console Client version: 
  - Device: (Desktop, Laptop, VPS, Raspberry Pi, etc) VPS
  - Operating System: Linux - Centos 7.9
  - Minecraft version: 1.8.0
  - Server address (If applicable):

**Comment by Kevqn11** [comment]
It's like having to restart minecraft when the server won't let you in because "Your session expired. Try restarting" or something along those lines. MCC should just restart and sort it out on its own. It's not a bug, just the cost of running your client for extending periods of time. If it is happening very frequently, a possible cause might be that the account which you are using is being accessed by other users (like shared alt accounts). in that case the new user is able to log on to servers and the old one cant and has to restart.

**Comment by ORelio** [comment]
This seems normal. MCC checks if the session is still valid. If not it re-perform login instead of session refresh.
