### ISSUE TITLE
regex not working

### ISSUE THREAD

**Issue by WolfgamingWG** [ORelio/Minecraft-Console-Client#1524]
I am trying to make a regex work but it's not working, this is what i have right now:

[Match]
regex=\[\[rankhere\] usernamehere\b(?:\(?([A-Za-z0-9]+)\)|\((hub-[0-9])\)|) -> me] gamemode\b
actionother=script gamemode

(script gamemode is for making it type either /server hub-1 or the game mode like creative)

and I am trying to detect:
[[rankhere] usernamehere(creative) -> me] gamemode

Why I am doing this is easy, I want it to go to whatever game mode I am in by just giving it the msg "gamemode". the thing is it doesn't even recognize it even though I tested it through regex101.com.

**Comment by ORelio** [comment]
Hi,
You need to properly escape all characters having a meaning in regex, e.g. `]` => `\]` and so on.
Here is a regex that matches the username in case you need it:
```
^\[\[[^]]+\] ([A-Za-z0-9]+)\([^)]+\) -> me\] gamemode$
```
Try it at https://regex101.com/r/hwsLt9/1

**Comment by WolfgamingWG** [comment]
I just now realized that I typed the regex in my example wrong, but I tried what you gave and it didn't work either, here is what I am using now:
[Match]
regex=^\[\[[^]]+\] usernamehere\(([^)]+)\) -> me\] gamemode$
actionother=script gamemode
again i am trying to detect: "[[rankhere] usernamehere(creative) -> me] gamemode" and i want it to match "Creative" without the ()
You can see here: https://regex101.com/r/a2g8Rl/1 that it does work properly.

**Comment by ORelio** [comment]
Oh, OK. Best thing is to change the regex for private messages in MinecraftClient.ini
```ini
[ChatFormat]
builtins=false
public=^<([a-zA-Z0-9_]+)> (.+)$ # TODO update if you have something else
private=^\[\[[^]]+\] ([A-Za-z0-9]+)\([^)]+\) -> me\] (.*)$
tprequest=^([a-zA-Z0-9_]+) has requested (?:to|that you) teleport to (?:you|them)\.$ # TODO update if necessary
```
(Test private regex here: https://regex101.com/r/EWi0x7/1)

... Then use actionprivate instead of actionother:
```ini
[Match]
match=gamemode
actionprivate=script gamemode
```
On public and private messages, the match and regex is only checked against the message, not the username and ->me part

**Comment by WolfgamingWG** [comment]
I changed the private chat format in the minecraftclient.ini to what was recommended but I changed it up a little so there would be a match for the game mode I am in (the one between the hooks) but now it detects every msg I send to it as the game mode I am in. I assume it has something to do with that the 2nd match always has to be the actual msg instead of something else, i changed the chat format to this:
```
[ChatFormat]
builtins=true
public=^\[\] \[[^]]+\] ([A-Za-z0-9_]+) > (.+)$
private=^\[\[[^]]+\] ([A-Za-z0-9]+)\(([^)]+)\) \-\> me\] (.*)$
tprequest=^([a-zA-Z0-9_]+) has requested (?:to|that you) teleport to (?:you|them)\.$
```
(regex here: https://regex101.com/r/BhIjz8/1)

and the match to this: 
```
[Match]
match=gamemode
actionprivate=send /server $2
ownersonly=true
```
any help on to getting it to detect the (gamemode) part in chat format will be helpful :)

**Comment by ORelio** [comment]
That's interesting.

Indeed, MCC expects a regex where group `1` is username and group `2` is chat message, and does not work if you put another group in between. But even if group `2` was gamemode and group `3` chat message, the gamemode would not be available in your `AutoRespond` action. That's because the match is run against the contents of the chat message, not the whole line.

E.g. with private chat message regex:
```
private=^\[\[[^]]+\] ([A-Za-z0-9]+)(?:\(([^)]+)\)|) \-\> me\] (.*)$
```
You get `1` with username, `2` with gamemode, `3` with message. AutoRespond would take `3` (message) and run your match and regex against it and only it. It takes the username as well so that you can have it in `$u` but not other parts of your regex so other capture groups are ignored. Which means the contents of any other match in the global regex in config would be lost anyway.

Two options would be available for you:
1. Purposefully misconfigure MCC to consider all chat messages as `other` i.e. by not providing the correct regex in config
    Advantages: Easy to do, and works for your use case: specify the regex as match and use $1 $2 $3 in `actionother`
    Disadvantages: Breaks any other ChatBot that relies on public/private chat message detection

2. Write a ChatBot in C# distinct from `AutoRespond` and extract the custom field you want with `gamemode` inside
    Advantages: Does not break any other ChatBot since your bot will itself process every line that appears in chat
    Disadvantages: Need to code your own C# bot. You can use [sample-script-with-chatbot.cs](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/config/sample-script-with-chatbot.cs) and [AutoRespond.cs](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/ChatBots/AutoRespond.cs) as examples

**Comment by WolfgamingWG** [comment]
Hhm, i see i will look into making a cs chatbot for sure since the first option isnt an option for me since i use the other stuff more often then im gonna use the gamemode command, thx for the advice i am gonna look into making my own chatbot! Feel free to mark this as solved
