### ISSUE TITLE
can it be used in hypixel ?

### ISSUE THREAD

**Issue by SsValor** [ORelio/Minecraft-Console-Client#1545]
so hypixel has a strong rule for scripts and they are not allowed.
i don't have a alt to take the risk of ban in hypixel and i don't want to use any scripts or auto movement options ,
i just want to use it in hypixel - skyblock , to afk on my island... ( im not gonna use the anti afk option ). 
this program is perfect for this as it uses almost no resources to run and its perfect for just running it in the background for hours and doing other stuff.

if someone have tried this in hypixel please let me know

**Comment by ORelio** [comment]
My advice is to comply with server rules: You should avoid using third party clients if they forbid it.

But if they allow chat apps such as Minechat, then you should be safe because MCC works in chat-only mode with no automation by default, it just logs on and shows the chat, allowing you to chat and type commands. Automation stuff is opt-in and you need to manually enable terrain, entities, anti afk, auto relog and so on.

If you want, you can also set `brandinfo=vanilla` in `MinecraftClient.ini` to make MCC identify itself as Vanilla Minecraft.
