### ISSUE TITLE
Dumb AutoAttack option

### ISSUE THREAD

**Issue by BRCDel** [ORelio/Minecraft-Console-Client#1604]
**Prerequisites**
 - [+] I have read and understood the [user manual](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config)
 - [+] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
 - [+] I tried to [look for similar feature requests](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before opening a new one

---
## Describe your problem
Server rules for a server I want to use MCC in allow bots that are NOT aware of their surroundings and only do simple actions.
With that in mind, the current AutoAttack implementation is too intelligent to obey server rules.
Is it possible to develop a variant of AutoAttack that just blindly attacks at a set interval?

---
## Suggest a possible solution
I'd like there to be a "DumbAutoAttack.cs" ChatBot file which simply left-clicks at a set interval. 
This might be possible through a new EntityActionType for SendEntityAction.

---
## Screenshot to help explain your request (If applicable)

**Comment by ORelio** [comment]
Hi @BRCDel,

Just so that you know, there is no dumb "left click/right click" in the Minecraft protocol.
When you do that in the game, Minecraft automatically determines what you want to do.
If there is a block in front of you, it understands you want to break the block.
If there is an entity in front of you, it understands you want to attack or interact with it.
If there is nothing, it understands you just want to play the "swing arm" animation.
Then, the game performs the relevant action.

So actually, to fit your need, the bot would need to be _smarter_ and only attack entities right in front of it, or do the "swing arm" animation, all at a set interval. In any case, it needs to be aware of it surroundings to properly perform the task you want to do. So it might not obey your server's rule anyway.

**Comment by BRCDel** [comment]
I see, thank you very much! I'll consider my options again.
