### ISSUE TITLE
question about the mailer network feature 

### ISSUE THREAD

**Issue by Netherite2** [ORelio/Minecraft-Console-Client#1625]
**Prerequisites**
 - [. ] I have read and understood the [user manual](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config)
 - [ .] I made sure I am running the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts)
 - [. ] I tried to [look for similar questions](https://github.com/ORelio/Minecraft-Console-Client/issues?q=is%3Aissue) before creating a new one

---
## Description of the Question
so how do i have the same database in multiple folders? since different servers may have different /msg and normal chat messages
if i cant do this, consider this a suggestion

**Comment by Daenges** [comment]
Help is coming!

This feature is already integrated. At best you create two folders and copy the MCC executable in each of them. Execute both, so a ``MinecraftClient.ini`` is created. ``database=MailderDatabase.ini`` (l. 164) and ``ignorelist=MailerIgnoreList.ini`` (l. 165) are just paths to the file and due to the fact, that the files are in the same folder as the executable, no full path is required. 

If you have both executables in seperate folders, activate the mailer in one of them, so that the database and ignoreList files are created. Then you go to the second folder and change the database path 
(e.g. ``database=C:\Path\To\First\Folder\MailerDatabase.ini``).
Same can be applied if you want to sync the ignoreList.

Now you have two instances with different configuration and the same database.

**Comment by Daenges** [comment]
@Netherite2 does this answer satisfy your question? If yes, remember to close the issue. ;D

**Comment by ORelio** [comment]
For your information, you can also set `database=..\MailerDatabase.ini` (relative path) if using the following architecture:
```
Folder
 +- MailerDatabase.ini
 +- Client1
  |     +- MinecraftClient.exe
  |     `- MinecraftClient.ini
  `- Client2
        +- MinecraftClient.exe
        `- MinecraftClient.ini
```

**Comment by Daenges** [comment]
Same approach, better visualization. :)
