### ISSUE TITLE
Running it 24/7

### ISSUE THREAD

**Issue by zacsta13** [ORelio/Minecraft-Console-Client#163]
Hi ORelio,

I love what you have created here, but im sure some of us consider running the program 24/7 do you have any idea if we can run an exe file from a hosting company or from like a rasberry pi of some sort?

Thank you so much for reading :+1:

**Comment by ORelio** [comment]
You can run it on Linux with mono as this exe is a .NET app.
See README file for more info :)
It works on a VPS or Raspberry Pi.

**Comment by zacsta13** [comment]
This might sound stupid but are you able to show me on a video or step by step would really help me out thank you so much

**Comment by ORelio** [comment]
As stated in the [README](https://github.com/ORelio/Minecraft-Console-Client/blob/67fc431d4a053fa09f67e754224d9ba4850ef735/MinecraftClient/config/README.txt#L17) file:
> On Mac or Linux, open a terminal in this folder and run "mono MinecraftClient.exe".

This means you need to install Mono : `sudo apt-get install mono-complete`
then use `mono MinecraftClient.exe` while being in the right directory in order to launch it.
> If you cannot authenticate on Mono, you'll need to run "mozroots --import --ask-remove" once.

Seems self explaining, this command needs to be run only once after installing Mono if you plan to use online-mode ie official credentials for a Mojang account, in order to install HTTPS certificates.
> If Mono crashes, retry with mono-complete, not mono-runtime. Mono v4.0 to 4.2 is recommended.

There are some issues depending on your `mono --version`, v4.0-4.2 seems to work well.
Never had to install a specific version myself, you may use a search engine for more info.

**Comment by zacsta13** [comment]
Oh okay awesome, Im still new to all of this but there isnt a website to like upload an exe file and then just double click it so its always online is there?

**Comment by ORelio** [comment]
You need at least a VPS to run a custom app un background.
Regular web hosts only allow PHP (or so), with no background tasks.

**Comment by zacsta13** [comment]
So how does one get one of these? I am speaking for all as they might want to AFK their spawners :D

**Comment by ZizzyDizzyMC** [comment]
If ORelio doesn't mind it would take me a few days to push out a current update but I used to release the client with self-made scripts that made afking spawners quite easy complete with Anti-afk measures as needed.  With his permission I'll create another release based on the current stable indev release.

**Comment by ORelio** [comment]
What do you mean by "a current update"? Yes, feel free to submit scripts to be included with MCC releases if you feel it would help others :)

**Comment by ORelio** [comment]
Initial question has been answered, feel free to reopen if needed.

**Comment by BlueDemonic** [comment]
did this work for you

**Comment by LloydPlayzHD** [comment]
Centos?
