### ISSUE TITLE
Implement right click on sign blocks

### ISSUE THREAD

**Issue by Megaeloelo** [ORelio/Minecraft-Console-Client#171]
I have to click the right mouse button and select , for example: skyblock. How can I do this on lobby servers?
PS: Sorry for bad english.

**Comment by Pokechu22** [comment]
On many of those servers you can use `/server skyblock` to also switch servers, though not all allow it.  Maybe that'll work for you?

**Comment by ORelio** [comment]
If that doesn't, well, clicking on singns is not implemented yet.

**Comment by TheSnoozer** [comment]
Hi, since I think this would be tracked within https://github.com/ORelio/Minecraft-Console-Client/issues/205 I'm closing this as 'duplicate'.
Feel free to subscribe to the other issue or subscribe to the other one for any updates. besides that feel free to open a new issue, with any other problem/issue you encounter.
