### ISSUE TITLE
24/7 Console Client on a VPS

### ISSUE THREAD

**Issue by BlueDemonic** [ORelio/Minecraft-Console-Client#174]
Hi ORelio,

I love what you have created here, but im sure some of us consider running the program 24/7 could you help me setup console cleint on a vps like step by step because im ever new to vps and i just bought it 

Thanks for reading

**Comment by TNTUP** [comment]
Try running in a SCREEN using (screen -D -R -S mccclient mono MinecraftConsole.exe user@user.tld mypwdhehehhe myserverIP) or else run without email/pwc and type manually :) Hope it helps you :D

**Comment by BlueDemonic** [comment]
@ORelio i setup console cleint on my vps but every time i try to login to the account it says wrong password/login filed when the acc works on mc

**Comment by ORelio** [comment]
Hello, try putting your password in the INI file to see if it helps. You can use sftp, nano or vim for this. As suggested by TNTUP the easiest way of running MCC on a VPS is using the screen utility as this allows you to disconnect from your VPS without closing the MCC instance.

**Comment by BlueDemonic** [comment]
how do i setup console cleint on a Linux vps from ovh

**Comment by TNTUP** [comment]
@BlueDemonic use mono :)

**Comment by ORelio** [comment]
See the [MacOS tutorial](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-tools/1263927-win-mac-linux-minecraft-console-client-1-8-0?page=31#c623) on the Minecraft Forum. The only difference is for installing mono. Use `apt-get install mono-complete` as root instead, followed by `mozroots --import --ask-remove` for HTTPS certificates. Also, check that your `mono --version` is between 4.0 and 4.2 inclusive, otherwise this can cause issues. Lower versions can crash or malfunction for various reasons, higher versions will reject Mojang's current HTTPS certificate because the root certificate still uses `sha-1` as a signature algorithm (which is being deprecated).

**Comment by Vermello** [comment]
for some reason every time the server reboots my alts do not log back in the server (i play on saicopvp)

**Comment by Jumpyy123** [comment]
I need help, I don't have a clue what i'm doing and I just bought a VPS.
