### ISSUE TITLE
Cannot move down on server

### ISSUE THREAD

**Issue by ReOp14** [ORelio/Minecraft-Console-Client#195]
So a few weeks ago on the minecraft forums, I told that an anti-cheat on a server wouldn't let MCC fall down (will just teleport back up), I'm not sure if there is a way to fix this but for this server called "Mineplex" (or us.mineplex.com). i'm trying to make a bot to say things in chat for every lobby. But.. to type in chat you must move 1 block away from spawn, I think the problem is that the client is moving down instead of falling down which seems like a bug, is there anyway you can fix this ORelio?

The script works like this: it types /server Lobby-4 then it tries to type in chat but the server says you must move out of spawn to chat. And yes movement is on in the options. This only happens on that server, not any other server so it is in fact the server.

**Comment by ORelio** [comment]
Hello,

Worked a bit on that but cannot seems to find why movements are not accepted. Even a slight step down is rejected and the player disappears.

Falling it the same thing as moving down network-wise, but maybe Mineplex is expecting exact vanilla falling in term or coordinates. Will see how falling is actually implemented in Minecraft, there must be something useful in it that I missed.

**Comment by ReOp14** [comment]
Yeah, its definitely the way it moves down. Mineplex is expecting vanilla gravity.

**Comment by ORelio** [comment]
After some research, found this in Minecraft source code, `EntityLivingBase.java` :
````java
//...
    if (!this.worldObj.isRemote || this.worldObj.isBlockLoaded(blockpos$pooledmutableblockpos) && this.worldObj.getChunkFromBlockCoords(blockpos$pooledmutableblockpos).isLoaded())
    {
        if (!this.func_189652_ae())
        {
            this.motionY -= 0.08D;
        }
    }
    else if (this.posY > 0.0D)
    {
        this.motionY = -0.1D;
    }
    else
    {
        this.motionY = 0.0D;
    }
}

this.motionY *= 0.9800000190734863D;
//...
````
Seems like each tick, if falling, vertical motion speed gets `-= 0.08` bonus, and regardless of falling status, global speed has a `0.9800000190734863` multiplier.

Tried to implement fallling in MCC using the same algorithm:

````C#
//ref double motionY
if (goal == Move(start, Direction.Down))
{
    //Use MC-Like falling algorithm
    double Y = start.Y;
    Queue<Location> fallSteps = new Queue<Location>();
    fallSteps.Enqueue(start);
    while (true)
    {
        double motionPrev = motionY;
        motionY -= 0.08D;
        motionY *= 0.9800000190734863D;
        Y += motionY;
        if (Y < goal.Y)
        {
            motionY = motionPrev;
            break;
        }
        else fallSteps.Enqueue(new Location(start.X, Y, start.Z));
    }
    if (fallSteps.Count == 0)
        fallSteps.Enqueue(goal);
    return fallSteps;
}
else
{
    motionY = 0; //Reset motion speed
    //Regular MCC moving algorithm
    double totalStepsDouble = start.Distance(goal) * 8;
    int totalSteps = (int)Math.Ceiling(totalStepsDouble);
    Location step = (goal - start) / totalSteps;

    if (totalStepsDouble >= 1)
    {
        Queue<Location> movementSteps = new Queue<Location>();
        for (int i = 1; i <= totalSteps; i++)
            movementSteps.Enqueue(start + step * i);
        return movementSteps;
    }
    else return new Queue<Location>(new[] { goal });
}
````
While testing on a local server without anti-cheat plugins, with this algorithm, fallling seems very natural, exactly like a Minecraft client, while other movements are as before.

While trying on Mineplex however that does not change anything and the client gets rejected (well, more exactly the player does not fall and disappears).

While debugging packets on a local server falling 1 block down gives the following:
````
[C -> S] Location: 213,215559066258, 78,               264,999817405595
[C -> S] Location: 213,215559066258, 78,               264,999817405595
[C -> S] Location: 213,215559066258, 78,               264,999817405595
[C -> S] Location: 213,215559066258, 77,9215999984741, 264,999817405595
[C -> S] Location: 213,215559066258, 77,7663679939575, 264,999817405595
[C -> S] Location: 213,215559066258, 77,5358406250446, 264,999817405595
[C -> S] Location: 213,215559066258, 77,231523797587,  264,999817405595
[C -> S] Location: 213,215559066258, 77,               264,999817405595
[C -> S] Location: 213,215559066258, 77,               264,999817405595
[C -> S] Location: 213,215559066258, 77,               264,999817405595
````
That does not seems very different from values calculated from the algorithm.
Also tried alternative "Player position and look" packet instead of "Player position", no success.

So currently, don't know how to fix this, sorry.

**Comment by ReOp14** [comment]
Oh that is unfortunate, thanks for taking your time on this, that is a lot of stuff I don't understand yet! Here was a flaw I found on Mineplex's Anticheat, while using a different modded client, the player may teleport up to 10 blocks up and down and the anticheat wont teleport you back. So maybe if you tried adding a teleport command like /tp (x y z) or /tp (~-5) (or how many blocks the player is above the ground) which could teleport the player down a number of  blocks. 

All I need is the player to land on the ground then it could type /move south easily without any frustration. Oh also, you can't see players that have not left the spawn platform yet, they stay invisible because of less rendering.

**Comment by ORelio** [comment]
There is probably a toughter check performed on login, then the actual anticheat that is more permissive.

**Comment by ReOp14** [comment]
Ok, well ill close this thread, feel free to open the thread if you ever find a solution!

**Comment by ReOp14** [comment]
Hey, another server I go on I can not use movements because the account gets kicked for flying instantly. The server has NoCheatPlus (/plugins) and other servers I find also get kicked.

Not trying to advertise, but the server is Blockmania.com (also known as the namemc.com server)
You can easily see the account is flying 1 block in the air and gets kicked in game.
The NoCheatPlus is very common on most servers and the bot can't handle movements, can you look for a fix?

**Comment by ORelio** [comment]
I'll take look later, hope it will not be as unsuccessful as for Mineplex.

**Comment by ORelio** [comment]
Tried out the algorithm above on BlockMania, that does not seems to work either :disappointed:

**Comment by ReOp14** [comment]
Oh thats unfortunate, what do you think the problem is?

**Comment by ORelio** [comment]
No idea, I'd be fixing it if I knew :sweat:

**Comment by ReOp14** [comment]
Is it possible to look at the exact code for falling in like 1.10 jar file?

**Comment by ORelio** [comment]
Already did that, see above.

**Comment by ReOp14** [comment]
Oh, I thought you just found it on the wiki.

**Comment by ORelio** [comment]
Well the issue is not fixed to I don't mind if it stays open.

**Comment by Pokechu22** [comment]
HiImJosh was having a similar issue in the #mcdevs channel (see [log file 093](https://logs.rom1504.fr/parts2/093.txt)), and said:

```
[10:44] <HiImJosh> Oh figured out, the landing was wrong
```

Maybe that's what's happening here.

**Comment by ORelio** [comment]
Thanks. Well, seems like source code for NoCheat would contain some element of reponse. I'll dig it later.

**Comment by ReOp14** [comment]
@ORelio Still looking for a fix if possible, I'm also still looking at other people's threads and your doing great work responding to them. 🥇

**Comment by ORelio** [comment]
Okay, so, tried again to dig the issue, and found several interesting things 😄

First, landing in MCC was wrong indeed. Thanks @Pokechu22 for the hint!
After looking at packets sent by MCC and parsing the `OnGround` field I got the following:
````
//MCC 1-block fall v1
[S -> C] Login successfull
[C -> S] Location: 231,5, 73,875, 282,5, True
[C -> S] Location: 231,5, 73,75, 282,5, True
[C -> S] Location: 231,5, 73,625, 282,5, True
[C -> S] Location: 231,5, 73,5, 282,5, True
[C -> S] Location: 231,5, 73,375, 282,5, True
[C -> S] Location: 231,5, 73,25, 282,5, True
[C -> S] Location: 231,5, 73,125, 282,5, True
[C -> S] Location: 231,5, 73, 282,5, True
[C -> S] Location: 231,5, 73, 282,5, True
````
The second coordinate is the Y-coordinate. `True` means that client tells the server that feets are on the ground. Ground calculation in MCC was wrong as it was rounded to block: `>= 1` block over the ground would say `False` but `< 1` block above the ground is `True`. So MCC concludes that `0.875` height is on the ground -> `True`. On the opposite side, vanilla Minecraft says `True` to OnGround for `0.000` height **only**:
````
//Vanilla 1-block fall
[S -> C] Login successfull
[C -> S] Location: 231,467646703222, 74, 283,512601844705, (look), False
[C -> S] Location: 231,467646703222, 74, 283,512601844705, (look), False
[C -> S] Location: 231,467646703222, 73,9215999984741, 283,512601844705, False
[C -> S] Location: 231,467646703222, 73,7663679939575, 283,512601844705, False
[C -> S] Location: 231,467646703222, 73,5358406250446, 283,512601844705, False
[C -> S] Location: 231,467646703222, 73,231523797587, 283,512601844705, False
[C -> S] Location: 231,467646703222, 73, 283,512601844705, True
[C -> S] Location: 231,467646703222, 73, 283,512601844705, True
````
So, to fix this issue, I changed the `OnGround` value to match vanilla behavior, and got the following:
````
//MCC 1-block fall v2
[S -> C] Login successfull
[C -> S] Location: 231,536276042023, 73,875, 283,44141139337, False
[C -> S] Location: 231,536276042023, 73,75, 283,44141139337, False
[C -> S] Location: 231,536276042023, 73,625, 283,44141139337, False
[C -> S] Location: 231,536276042023, 73,5, 283,44141139337, False
[C -> S] Location: 231,536276042023, 73,375, 283,44141139337, False
[C -> S] Location: 231,536276042023, 73,25, 283,44141139337, False
[C -> S] Location: 231,536276042023, 73,125, 283,44141139337, False
[C -> S] Location: 231,536276042023, 73, 283,44141139337, True
[C -> S] Location: 231,536276042023, 73, 283,44141139337, True
````
However that is not enough, so for a closer match to vanilla fall, it was also necessary to implement vanilla falling using motionY, as described [before](https://github.com/ORelio/Minecraft-Console-Client/issues/195#issuecomment-244944585):
````
//MCC 1-block fall v3
[S -> C] Login successfull
[C -> S] Location: 231,435742344936, 73,9215999984741, 283,500876447371, False
[C -> S] Location: 231,435742344936, 73,7663679939575, 283,500876447371, False
[C -> S] Location: 231,435742344936, 73,5358406250446, 283,500876447371, False
[C -> S] Location: 231,435742344936, 73,231523797587, 283,500876447371, False
[C -> S] Location: 231,435742344936, 73, 283,500876447371, True
[C -> S] Location: 231,435742344936, 73, 283,500876447371, True
````
Finally, to perfectly match Minecraft vanilla, it seems like we need to use `Player position and look` packet for the first 2 updates instead of `Player position`, without moving. So I also added handling for that, player look is retrieved from spawn location packet, then sent back 2 times with the same exact coordinates. Then, normal moving behavior occurs:
````
//MCC 1-block fall v4
[S -> C] Login successfull
[C -> S] Location: 231,435742344936, 74, 283,500876447371, (look), False
[C -> S] Location: 231,435742344936, 74, 283,500876447371, (look), False
[C -> S] Location: 231,435742344936, 73,9215999984741, 283,500876447371, False
[C -> S] Location: 231,435742344936, 73,7663679939575, 283,500876447371, False
[C -> S] Location: 231,435742344936, 73,5358406250446, 283,500876447371, False
[C -> S] Location: 231,435742344936, 73,231523797587, 283,500876447371, False
[C -> S] Location: 231,435742344936, 73, 283,500876447371, True
[C -> S] Location: 231,435742344936, 73, 283,500876447371, True
````
So now MCC should fall exactly like Minecraft vanilla, great!
Lets test it on Mineplex... _oh noes_, my bot disappears 😭
Oh, wait, let's see `/move get`... coordinates are right... what's wrong...
Let's try `/move north` just in case... _omg it just got visible! IT WORKS™_ 😎

Moved around for a bit in spawn, and could type commands & chat, apparently movement is now fixed!
Please grab latest development build to try it out, there are probably some bugs that were introduced in movement handling because that required many changes here and there :wink:

**Comment by ReOp14** [comment]
Ill try it soon and provide feedback, just need some extra free time. Thanks so much this makes me very happy that I can use more options now.

**Comment by ReOp14** [comment]
Once again, thanks so much. You worked very hard on this and i'm very glad for this executable.

**Comment by TNTUP** [comment]
Is there a way to revert this commit by myself and supporting 1.12 at the same time? Like, removing the changed code idk if it would work

**Comment by Pokechu22** [comment]
If you've cloned the project via git (and didn't just download it as a source zip), you can run `git revert a344ac4101af99d3dd9a4e48c3a12a6c8e989c28` to undo the commit locally (though if there are merge conflicts, then it'll be more complicated).
