### ISSUE TITLE
Option to change chat colors

### ISSUE THREAD

**Issue by theonlygusti** [ORelio/Minecraft-Console-Client#216]
In light-themed terminals this app becomes unreadable:

![](http://i.cubeupload.com/Jd99Ay.png) ![](http://i.cubeupload.com/D1LARx.png)

I think there should be an option in the `.ini` file to change the output colors of formatted chat messages. E.g., you are able to say that if a message is received from the server that should be colored white, print it to the terminal in a black color.

**Comment by theonlygusti** [comment]
So, my idea of how this feature would look as a section in the `MinecraftClient.ini` file:

```ini
[ChatColors]
black=Black
dark_blue=DarkBlue
dark_green=DarkGreen
dark_aqua=DarkCyan
dark_red=DarkRed
dark_purple=DarkMagenta
gold=DarkYellow
gray=Gray
#...
```

so basically, minecraft's [JSON chat colors](http://minecraft.gamepedia.com/Formatting_codes) on the left are assigned a [C# console color](https://www.dotnetperls.com/console-color) output on the right, which means I can change, for example, the output of white:

```ini
white=DarkGray
```

**Comment by ORelio** [comment]
Hello,

As you are saying yourself, you are using a themed terminal. If your theme displays unreadable colors, I think the theme itself seems faultly and should be improved. Most terminal applications would allow you to customize colors so I'd advise to improve your theme instead :smiley:

Example with Gnome terminal:

![term_colors](https://cloud.githubusercontent.com/assets/1128206/20037706/e16b3c6a-a425-11e6-91c0-b30c9a01517c.png)

The good thing is that instead of requesting changes in all apps you run in your light-themed terminal, everything would be readable without any change besides fixing your theme. :wink:

**Comment by theonlygusti** [comment]
No, I understand what I'm doing. You are outputting white text by default, which is understandable because that's what the server tells you to do. However, this causes problems on light terminals. Changing my terminal colors would fix this, but break _everything_ else.

**Comment by ORelio** [comment]
White text is suitable for black backgrounds.
So a light-themed theme should print white as black and black as white...
