### ISSUE TITLE
Block Data

### ISSUE THREAD

**Issue by tjmilh** [ORelio/Minecraft-Console-Client#244]
ORelio,

Looking to count the block types within the accounts render distance, is there currently a way to do that?
Is there a location where loaded block data is stored? I've looked through the Protocol18 file but couldn't quite tell if or where the block data is being stored.
I started played around with world.cs converting all loaded chunks into a ton of individual locations, but I get the feeling that's not going to be successful or efficient.  
Is there some way with getworld to select all the blocks I have loaded?
If not, is there maybe a way to set a range location?

Thanks,
TJ

**Comment by Pokechu22** [comment]
Use chunks instead of individual locations - there's an [indexer](https://msdn.microsoft.com/en-us/library/6x16t2tx.aspx) for that purpose.  It doesn't look like you can _directly_ access the list of loaded chunks, though; you just can get an individual chunk directly.

Once you have a `ChunkColumn` you can then use another indexer to get a chunk section (16x16x16 cube) within it.  That'll give you a `Chunk`, which in turn has another indexer.

So apart from getting the list of loaded chunks (which I'm instead using a radius of 10 chunks around a hardcoded position (it doesn't seem like `GetCurrentLocation` is exposed to bots either)), you can do this fairly easily.  Something like this (untested):

```csharp
World world = GetWorld();
for (int chunkZ = -10; chunkZ <= 10; chunkZ++) {
    for (int chunkX = -10; chunkX <= 10; chunkX++) {
        ChunkColumn column = world[chunkX, chunkZ];
        if (column == null) {
            continue;
        }
        for (int sectionY = 0; sectionY < ChunkColumn.ColumnSize; sectionY++) {
            Chunk chunk = column[sectionY];
            for (int y = 0; y < Chunk.SizeY; y++) {
                for (int z = 0; z < Chunk.SizeZ; z++) {
                    for (int x = 0; x < Chunk.SizeX; x++) {
                        Block block = chunk[x, y, z];
                        // Do something with the block
                    }
                }
            }
        }
    }
}
```

**Comment by ORelio** [comment]
You can get world and current location from bots, at least in development builds:
````C#
/// <summary>
/// Get the current Minecraft World
/// </summary>
/// <returns>Minecraft world or null if associated setting is disabled</returns>
protected Mapping.World GetWorld();

/// <summary>
/// Get the current location of the player
/// </summary>
/// <returns>Minecraft world or null if associated setting is disabled</returns>
protected Mapping.Location GetCurrentLocation();
````
After that, if you want to process all blocks, you need to iterate as @Pokechu22 said.
Take care, accessing unloaded chunks may raise exceptions or return null values.
See [ChatBot.cs](https://github.com/ORelio/Minecraft-Console-Client/blob/Indev/MinecraftClient/ChatBot.cs#L562)

**Comment by ORelio** [comment]
Seems like initial question has been answered, feel free to reopen if needed ;)
