### ISSUE TITLE
Sounds 🔊

### ISSUE THREAD

**Issue by ReOp14** [ORelio/Minecraft-Console-Client#265]
Hey ORelio, I was wondering, if it was possible to trigger a sound file, like an mp3, from a script or command.
I know about console.beep(); but I was more interested in an actual custom made sound from a mp3 that I would create myself. Found a sample sound: [download](http://download1979.mediafireuserdownload.com/pnq3bzeba72g/56ri6ot5ed0u3k3/sample.mp3). If you actually add this feature, thank you very so much, and could you make the mp3 files be added to a folder named Sounds located in the folder itself? C:\Users\reop\Desktop\MCC by ORelio\Sounds\ I already have SO MANY scripts located in the folder, its getting hard to find a script that I would need to edit. Keep up the great work 👍

**Comment by ORelio** [comment]
I'm not aware of a portable way of doing that, i.e. that work on both Windows, Mac and Linux. The only portable way is `Console.Beep()`, that's why it is used. However if your script is designed to operate on Windows only, that could be done by calling Windows Media Player under the hood, for instance:

````C#
System.Media.SoundPlayer player = new System.Media.SoundPlayer(@"c:\mywavfile.wav");
player.Play();
````
Source: https://stackoverflow.com/questions/3502311/

**Comment by ORelio** [comment]
Oh, also, you may create a `Scripts` directory and place your scripts there. MCC will find them.

**Comment by ReOp14** [comment]
Is this a chatbot or script addon? Chatbots are annoying to setup and edit every update of MCC.

**Comment by ORelio** [comment]
This should work in both scripts and ChatBots.
You do not need to edit & recompile MCC in order to add your ChatBot.
Editing MCC with your bot is only needed for debugging & testing.
Once your ChatBot is ready, wrap it in a script instead: [`sample-script-with-chatbot.cs`](https://github.com/ORelio/Minecraft-Console-Client/blob/Indev/MinecraftClient/config/sample-script-with-chatbot.cs).

**Comment by ReOp14** [comment]
Oh this is awesome! Thanks. Also glad to know about the Scripts directory, I do wish you can have more sub-folders in the Scripts folder though. I also forgot about the script chatbot extention, thanks for reminding me.
