### ISSUE TITLE
Login authentication failed.

### ISSUE THREAD

**Issue by iToasters** [ORelio/Minecraft-Console-Client#271]
I used to have this issue quite often but it would soon fix itself. I am now creating this thread because it didn't self fix this time, and I've waited over 24 hours. I tried restarting my computer as well.
Here's the message (I have the newest dev-build with debugmessages enabled) **and yes it is the correct password. I can login with the regular minecraft launcher just fine
https://gyazo.com/a3289ce00bc96ecbec1a368d562943fe

*I've looked at other threads and no, my password doesnt have any special characters like %$#

**Comment by ORelio** [comment]
This seems related to #232 and not to your password complexity.

**Comment by TheSnoozer** [comment]
Since this seems to be a very old issue, I would suggest to download the latest development build (https://ci.appveyor.com/project/ORelio/minecraft-console-client) and try if the problem is still present.

For now it seems that the issue was fixed and thus I'm going ahead and close this as part of an issue cleanup. Feel free to reopen if the issue is still present with the latest version.
