### ISSUE TITLE
Chat messages with hover data?

### ISSUE THREAD

**Issue by MattCowley** [ORelio/Minecraft-Console-Client#275]
Is there a way to access chat messages with hover data?
If not any chance it could be added.

Love all the work you do, thanks <3

**Comment by ORelio** [comment]
That would be feasible, the main issue is that we are displaying messages to a console without mouse cursor support, so we could print everything, but as hover data can be multiline, that would be really spammy, or print nothing, as MCC does currently. Not really convenient 😕

**Comment by MattCowley** [comment]
I was thinking more a scripting way to access it. Maybe a function similar to the current text one, but passes the full text data into it?

**Comment by ORelio** [comment]
Oh, yes, that would be possible, but how would you represent that data?

Currently, chat messages are parsed and converted as [JSONData](https://github.com/ORelio/Minecraft-Console-Client/blob/Indev/MinecraftClient/Json.cs), which is simply the object corresponding to the string (pretty ugly). Then, [ChatParser](https://github.com/ORelio/Minecraft-Console-Client/blob/Indev/MinecraftClient/Protocol/Handlers/ChatParser.cs) converts the JSONData to an old-school `§cChat Message`. Your ChatBot could receive either the raw JSON string (pretty useless as is) or the JSONData (pretty cumbersome to use, that's why it is immediately converted afterwards) or the old-school, converted, chat message (very easy to parse, that's what is currently given to the ChatBot).

One alternative way would be extracting hover messages while parsing chat messages, like what is done for links: https://github.com/ORelio/Minecraft-Console-Client/commit/1180c06b1f565828ec8602a31b9a853de499bcbc#diff-b62622a02e984301df17bd8a5743d74aR217 but instead of printing it we pass it to the bot. Not sure if that would be useful, however.

**Comment by MattCowley** [comment]
I think a data format is probably better as it can provide everything and so it can be handled by the end dev as they want.

Is there a way to intercept the chat messages at higher levels?
If not could you implement either stage of the JSON chat data so it's accessible when scripting?

Thanks, Matt <3

**Comment by ORelio** [comment]
After thinking about it more toroughly, here you are. There is now an extra `GetText(string, string)` variant which gives the raw json string as second argument. This way, you can use `Json.ParseJson()` on it or do whatever you want with it. It's up to you :)

**Comment by MattCowley** [comment]
Sorry to disturb again, thank you so much first of all. Is it possible to cast the JSONData to a standard dict?

**Comment by MattCowley** [comment]
Nope ignore me, .Properties is a dict.

**Comment by ORelio** [comment]
Exactly. This class is not much documented, but yes, simply check the `type` field from your `JSONData` object.
 -> `DataType.String`? -> then read the `StringValue` field
 -> `DataType.Array`? -> then use the `DataArray` field
 -> `DataType.Object`? -> then use the `Properties` field
Other fields are left null/empty when populating the class.
