### ISSUE TITLE
Quick question: How to add a delay in a script?

### ISSUE THREAD

**Issue by MattIPv4** [ORelio/Minecraft-Console-Client#278]
How to add a delay in a script?

**Comment by ORelio** [comment]
Use [`wait`](https://github.com/ORelio/Minecraft-Console-Client/blob/Indev/MinecraftClient/config/README.txt#L71) on standard scripts and [`Thread.Sleep`](https://msdn.microsoft.com/en-us/library/system.threading.thread.sleep(v=vs.110).aspx) on C# scripts.

**Warning:** Because ChatBot callbacks are called on the main thread, `Thread.Sleep` will hang MCC when used inside a ChatBot. Use a tick counter in `Update()` for instance, if you need to wait some time.

**Comment by MattCowley** [comment]
Not sure how to implement this well...

On a certain chat message, I need it to wait 30 seconds, and then run a further bit of script. A 30 second thread.sleep crashes mcc so what's the best way to do it?

**Comment by ORelio** [comment]
As said above, **do not** use `Thread.Sleep()` in a ChatBot.
````C#
public class MyBot : ChatBot
{
    private int myCounter = 0;
    private bool counting = false;

    public override void GetText(string text)
    {
        if (/* My text is what I want */)
        {
            counting = true;
            myCounter = 0;
        }
    }

    public override void Update()
    {
        if (counting)
        {
            //10 ticks per second
            myCounter++;
            if (myCounter == 30)
            {
                counting = false;
                myCounter = 0;
                //We are here around 30 seconds after your message
            }
        }
    }
}
````

**Comment by MattCowley** [comment]
Just gonna jump onto this with another question (I know I have so many). Is there a way to do eval() in C# similar to JS or PHP? If not, whats the best way to send the string to another thing to be eval'ed?

**Comment by ORelio** [comment]
That's actually what does [CSharpRunner](https://github.com/ORelio/Minecraft-Console-Client/blob/Indev/MinecraftClient/CSharpRunner.cs) to run your script.
As you can see this is not straightforward as your script needs to be compiled.
An easier way is generating a script file and launching it so that it will be compiled for you.

**Comment by MattCowley** [comment]
I'm trying to add an eval command to my bot. Is there anyway within C# to eval a string on the fly? Like mainly basic math and comparisons.

**Comment by ORelio** [comment]
Not to my knowledge, plus, remote eval seems a risky idea, remember that server admins can impersonate you in the RemoteControl bot or wherever you process input from the server, so adding remote C# execution ability would put your computer at risk.

**Comment by MattCowley** [comment]
Could system.data be added to the runner? I can't seem to use it as a fully qualified name?

**Comment by ORelio** [comment]
Maybe there is a library to include, currently, referencing libraries is not supported.
