### ISSUE TITLE
Incorrect password?

### ISSUE THREAD

**Issue by ItzThatKidBrian** [ORelio/Minecraft-Console-Client#279]
Im using a script that is using mono, the password is correct because I tested it and it works but it still says this

`Console Client for MC 1.4.6 to 1.9.0 - v1.9.0 - By ORelio & Contributors
Connecting to Minecraft.net...
Minecraft Login failed : Incorrect password.
Not connected to any server. Use '/help' for help.
Or press Enter to exit Minecraft Console Client.
`
plz help
-thanks

**Comment by ORelio** [comment]
Please use `debugmessages=true` in your INI file to show more information.

**Comment by TheHeat361** [comment]
Same issue, tell me if you fixed

**Comment by ORelio** [comment]
I'm still waiting for a debug output from [dev build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts) showing more information.
You should get a dump of the JSON request, please check the request is properly formatted.
I can assist you in this but that's a bit difficult without disclosing the password.
You may use a temporary password which has the same issue, then put back your usual password.

**Comment by TheHeat361** [comment]
Using dev build with debug messages on, not getting any text besides the incorrect password text in original post here

**Comment by TheHeat361** [comment]
I fixed the issue by purchasing a vps from a different hosting company, known to allow mojang logins. I think the issue is in the hosting company itself, not console client

**Comment by ORelio** [comment]
Strange, you should get a [Login request](https://github.com/ORelio/Minecraft-Console-Client/blob/550beda7c4749cd99a0494cef6a92c3241610dee/MinecraftClient/Protocol/ProtocolHandler.cs#L226) line if `debugmessages=true` in your INI file. But yes, some host provider being blacklisted by Mojang is likely since some individuals with a VPS there may have launched some attacks against auth server and got the whole range blacklisted.

**Comment by kraftee** [comment]
Getting the same issue, is there anything we can do to resolve it besides paying for a vps?
