### ISSUE TITLE
Crashing Upon Logging into a server.

### ISSUE THREAD

**Issue by dowgs** [ORelio/Minecraft-Console-Client#307]
I've downloaded the latest dev build of the console client and whenever I search it up in the downloads section of file explorer and launch it, it crashes. However, when I look through my downloads the client opens up. After inputting my username and password, the console client window closes without leaving anything.
Error Log when I search it up:
https://gyazo.com/6f6883e5e6dfad08e33094557656afd9

**Comment by Pokechu22** [comment]
Looks like it's being launched with the current directory set to System32.

You specifically say you're searching for it; that suggests you're using explorer's search.  It seems feasible that in search, there is no set current directory, so it uses system32 (which acts sort of as a default directory, but also is not writable).  You probably could solve that by opening downloads, right-clicking it, and selecting "create shortcut" (shortcuts embed current directory information).

For the second issue: I've never seen that.  What happens if you open a command window and then run it from there?  (Windowskey+R, type `cmd`, then type `cd Downloads` and then `MinecraftClient.exe`)

**Comment by dowgs** [comment]
https://gyazo.com/ccd3a6dc633e1bf26942bba9c4006267
I enter my info and the server name and it goes back to downloads. I also tried making a shortcut for console client in the downloads section and it worked until I tried to join a server and it closed.

**Comment by Pokechu22** [comment]
Alright, that's odd.  Can you set `debugmessages` to `true` in `MinecraftClient.ini`?  (That should add more information)
