### ISSUE TITLE
Console Client on a VPS not displaying commands when logged on to the server.

### ISSUE THREAD

**Issue by svxderg** [ORelio/Minecraft-Console-Client#311]
Hi.
I bought a uBuntu 16.04 VPS, tried turning on the console client with a auto-reconnect script, I thought everything was working the accounts were afking till the server rebooted. Then i tried executing commands on it and nothing popped up.
Here's a screenshot:http://prntscr.com/ggygog
Some of the commands work like /help or /server skeleton.

but scripts don't work, /f commands don't work while, u cant /msg i believe and u cant do stuff like that.
Thanks for your help.

**Comment by svxderg** [comment]
nvm i kind of fixed it i had to like spam enter a few times eks dee

**Comment by ORelio** [comment]
Maybe there was a small problem with the keyboard reading function, well, at least your issue is solved :slightly_smiling_face:

**Comment by svxderg** [comment]
that was server's fault, console client barely works on saicopvp now, only a few commands work as I said, I think they somehow patched it? idk :D the client works fine on other servers tho, thanks! <3

**Comment by TheSnoozer** [comment]
I know that particular server. It has an crappy anti-cheat system that checks your `brandinfo`. By default it is set to `mcc` and when the server detects that client, it simply will ignore all commands sent by the player. 

Set it to
```
brandinfo=vanilla
```
inside `MinecraftClient.ini` and try again (that's the brand the is sent by the default client - see https://wiki.vg/Plugin_channels#minecraft:brand)


See also:
https://github.com/ORelio/Minecraft-Console-Client/issues/589#issuecomment-436445428

Worked fine for me and thus closing this issue. Feel free to reopen if you still have any problems with this specific problem. Otherwise please open a new issue.
