### ISSUE TITLE
AutoRelog doesn't work

### ISSUE THREAD

**Issue by PollefeysC** [ORelio/Minecraft-Console-Client#318]
My AutoRelog doesn't work eventhough it's enabled. I know there is a file with messages to rejoin on, but I would like it to reconnect on every kick message possible. This is because Hypixel kickmessages are often crammed with random numbers and seem to be different often. Any way of enabling it to reconnect on EVERY kick message? Thanks in advance.

**Comment by stanleypowers** [comment]
I'm interested in this too

**Comment by ORelio** [comment]
That would not be as good as it seems since a mod kicking your for whatever reason would also trigger a relog. You could get banned easily just because you didn't take the time to set a proper keyword in a text file. The AutoRelog bot works by matching _keywords_. This means you just need to put `restarting` and it will match `The server is restarting S0mER4nD0mStr1ng`.

**Comment by iNordic** [comment]
Okay, could you then possible help me to find out Hypixel's kick message? I can not find it anywhere, and would then need a keyword for it (it doesn't say it in the client, it just seems to end)

**Comment by stanleypowers** [comment]
Could you make it compatible with regex also?
