### ISSUE TITLE
Tab completion

### ISSUE THREAD

**Issue by ghost** [ORelio/Minecraft-Console-Client#335]
Tab completion doesn't work with commands after /send.

**Comment by TheSnoozer** [comment]
Since this seems to be a very old issue, could you perhaps try to download the latest development build (https://ci.appveyor.com/project/ORelio/minecraft-console-client) and see if the problem is still present?

**Comment by flcmc** [comment]
This is still an issue. When entering a command normally, the client offers auto completion after pressing tab. For example /tp f<tab> would provide the users starting with f as tab completions. But if you attempt to send the same command with the internal /send there is no auto completion. You might not consider this an issue because you could just send the command normally, but the reason I made this issue was for the "/send" command on many bungee servers.

**Comment by ORelio** [comment]
Indeed, there is no tab-completion because `/send` is an internal MCC command so if using `/send /mycommand<tab>` the server will not know what is `/send` and won't provide autocomplete suggestions.

**Comment by ORelio** [comment]
About tab completion for `/send`, have you tried to set `internalcmdchar=\`? This will change all MCC commands to `\command` instead of `/command` so that MCC's `\send` would not prevent your server `/send` command from using TAB completion.
