### ISSUE TITLE
"Incorrect password" on VPS, debug printing empty lines.

### ISSUE THREAD

**Issue by JasonMill** [ORelio/Minecraft-Console-Client#349]
Hey,

I recently checked out the Console Client and haven't been able to get it work. I'm using OVH VPS with ubuntu 16.04. My issue is that when I try to log in, it says "Minecraft login failed : Incorrect password." Even though I know for a fact that the password is indeed correct. I've looked through multiple reports here and yet haven't been able to find the help that I needed to fix this problem. I went into my MinecraftClient.ini file and changed the debugmessages to true and all it does is add 3 empty lines before it says that the login failed again.

Also I suppose it is to be noted that my mono is currently version 5.4.1.6, I read that the recommended version was 4.0-4.2. Any idea if this could be the reason why it isn't working and if so, any idea how i could downgrade the mono from 5.4 to 4.2?

Best regards,
Jason M

**Comment by JasonMill** [comment]
Got it some what working due to a change of VPS host. Don't know why it worked but apparently it just didn't want to work with OVH. Now however, when I log in to the server, it disconnect randomly after like 10 secs. Any help?

**Comment by ORelio** [comment]
OVH VPS seems blacklisted by Mojang login servers. Regarding silent disconnection, this usually depends on Mono version and the exact cause hasn't been identified y et. Try a recommended version.

**Comment by JasonMill** [comment]
It works on some servers, but on some it still gets disconnected after a while (in 2 to 10s). I tried to use this on my windows 10 PC with the console GUI. When i start it and login, it will log in into the server but also pop up with this message 'The SMTP server requires a secure connection to the client or the client was not authenticated. The server response was: 5.5.1 Authentication Required.' After a while it will disconnect again, just like without using the gui and using the normal exe instead. Any idea how could I fix this?

**Comment by ORelio** [comment]
Are you sure you downloaded MCC from a reliable location? Seems like your GUI was recompiled by someone with a feature that tries to send something by email... Your Minecraft credentials for instance. I'd suggest changing your Minecraft password (although email sending seems to have failed...).

Could you host the executables (MCC and GUI) somewhere and/or tell me where you downloaded them so that I can take a look and see what they do exactly.

Also, get the latest, clean MCC dev build, from here: https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts

**Comment by JasonMill** [comment]
This is most likely the one that I tried: http://www.mediafire.com/file/gswx7dku52dwb1g/ConsoleClient-Tutorial.rar , I couldn't find the GUI anywhere else and saw some people using it on few videos so wanted to give it a shot. Anyways, I've changed my password and such now and wont use the GUI anymore. But I still have the issue of not being able to stay logged in on some servers, Do you have any idea why this is happening?

**Comment by JasonMill** [comment]
Found out that this same thing happens to users who use MineChat. Could possibly be that the server has somehow blocked the usage of MineChat and Clients like that, don't know for sure but just a guess.

**Comment by Pokechu22** [comment]
That wouldn't make sense, since the incorrect password message would come from MCC when it attempts to connect to Mojang's auth servers:

https://github.com/ORelio/Minecraft-Console-Client/blob/b1a66791a1f76a6819f07cf77884eb412d4a094f/MinecraftClient/Program.cs#L253-L263

It's possible that your account [has triggered Mojang's lockout](https://help.mojang.com/customer/en/portal/articles/781529-login-failed) from too many failed logins &mdash; the launcher would work fine since it caches the session token, but if you haven't logged in successfully with MCC yet (and if session caching hasn't been enabled in MCC) that can happen.

**Comment by ORelio** [comment]
After taking a look at the provided MediaFire link, it contains original untouched binaries from stable release v1.8.2, so that should not be this one which is causing the issue.

Regarding login issues, as @Pokechu22 says, there is probably a temporary or permanent blacklist applied on the login servers, either due to too many logins in a short time span, or based on the location, e.g. OVH IP range.

**Comment by JasonMill** [comment]
Yea, I already said I got it to work when I changed the VPS. The problem I was having after getting it to properly log in was that some servers seemed to be timing out players who were using something like MineChat or ConsoleClient. I was wondering if there was a way to get around with this. Anyways, I suppose I got my issue solved so this can be closed.
