### ISSUE TITLE
an error occured while attempting to connect to this ip

### ISSUE THREAD

**Issue by Tobi92222** [ORelio/Minecraft-Console-Client#357]
it says that when im trying to join a server in cosole client, but it not saying that when im join in normal mc. idk how to fix it, so i can join with console client, hope somebody can help me

https://gyazo.com/4a44fe2ec743296a92643940b59d7212

**Comment by ORelio** [comment]
You are using an old version without support for DNS SRV records (special domain name redirection used by some Minecraft servers). Just upgrade to the latest version. Download link on main page on the repository.

**Comment by Tobi92222** [comment]
but do i need to download mono then?

**Comment by Tobi92222** [comment]
https://gyazo.com/1593458e68fa8a5d0bdbe1f78325b778 beacsue it is like this

**Comment by Tobi92222** [comment]
??

**Comment by ORelio** [comment]
You're downloading the source code. You may compile it yourself since you have Visual Studio. Open it and use F6 or the Build button, then you get it in MinecraftClient > bin subdirectory. Or get the [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts).

**Comment by TheSnoozer** [comment]
Since this issue is inactive for quite a while I'm closing it as part of an issue cleanup. Feel free to reopen if you still have any problems in getting this sorted.
