### ISSUE TITLE
"Failed to connect to this IP"

### ISSUE THREAD

**Issue by Zulkey** [ORelio/Minecraft-Console-Client#364]
Hello, I'm usingthe Console Client on a Linux vServer. I can connect to every server, but there's a Server, I play a lot on at the moment. When i want to connect to the server it always gets me the "Failed to connect to this IP" error.  Is there a way to fix that? I tried to put a port after the ip (Serverip.IP:25565) but that doesn't work too.
I'd be thankful if some1 could help me.

**Comment by gtaEPIC** [comment]
I am having the same issue too!

**Comment by TheSnoozer** [comment]
I have experienced this a couple of times and would blame it on the servers (https://github.com/ORelio/Minecraft-Console-Client/issues/489#issuecomment-439757113). Essentially from my understanding the server claims to support versions which are in fact not supported. This will render the `mcversion=auto` useless and results in the `Failed to ping this ip` problems.

If this does not solve the issue, feel free to reopen. Otherwise please open a new issue.
