### ISSUE TITLE
[Suggestion] localhost support

### ISSUE THREAD

**Issue by PrismaticYT** [ORelio/Minecraft-Console-Client#367]
It would be nice to connect to LAN worlds via localhost or your IP to make use of the singleplayer internal server.

**Comment by Pokechu22** [comment]
This should already be doable, if the world is already open; just specify `localhost:<port>` (the game should put the port into chat after starting LAN).  Localhost itself definitely works (I use MCC a lot with a local test server).

Determining which port to use/finding other singleplayer worlds on the local network would be much harder though (I don't know how LAN works other than that it's something with multicast)

**Comment by TheSnoozer** [comment]
It works fine with every version I tested so far and thus I'm closing this as part of an issue cleanup.
Feel free to reopen if you still have problem in getting this setup.

Also try to use 127.0.0.1 instead of localhost....should be the same, but there might be cases where this might not always be the case.

**Comment by YTPSDanDie** [comment]
I got this but get an error saying "This version is not supported".

**Comment by ORelio** [comment]
That means the server version you launched on your computer is not supported yet... Try a previous version.
