### ISSUE TITLE
Bot crashes randomly after running it for quite a while

### ISSUE THREAD

**Issue by CarbonNeuron** [ORelio/Minecraft-Console-Client#370]
After about 12 hours of the bot running, it disconnects from the server and doesn't even know about it.

**Comment by ORelio** [comment]
Maybe it is related to #372. Not sure what is causing this.

**Comment by CarbonNeuron** [comment]
Hmm... Maybe if we could make it do /reco if no chat messages have been received for let's say 10 minutes

**Comment by CarbonNeuron** [comment]
Know anyway this could be possible?

**Comment by CarbonNeuron** [comment]
I've actually gotten into modifying your code to better suite me. The librarys you wrote are so useful. A really long while ago I was trying to do big things with the scripting things. Now I made it so if you talk to it and give it a password, it'll put you on the bot owners list, really useful when you're running 50+ alts and don't want to copy a bot owners file to all of them. I want it to figure out if they won the lottery. I can publish code later for what I have. I get an error saying that the text was not in the right format, I blelieve this is due to the number being a float($230,000.00) I am already trimming off the "$" and the comma, but I thought the .00 would be fine.

**Comment by ORelio** [comment]
Beware, server admins can see your password in the logs. So they can add themselves to bot owners and perform any actions a bot owner can do.
Regarding what you want to do:
 - You can write a chatbot that captures chat messages to log the last time a message was successfully retrieved, then on update, trigger a reconnect if the last time is too old
 - The formatting error may be caused by the Culture (i.e. language/regional settings) which will cause the parser to expect `00,00` with a comma instead of `00.00` for instance. You can get around this by using the InvariantCulture. See https://stackoverflow.com/a/23131455
