### ISSUE TITLE
cannot use chat before you move

### ISSUE THREAD

**Issue by NoName1102** [ORelio/Minecraft-Console-Client#377]
i play on a server where you cant do any chat commands before you move so i cant just do /server factions. i know there is a move command but i cant get it to work as a script so it does it automatically when i start up the client.

**Comment by TeamGameRevolution** [comment]
Do /spawn

**Comment by ORelio** [comment]
Simply [schedule](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/config/README.txt#L192) a [script](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/config/sample-script.txt) on server join using a [tasks](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/config/sample-tasks.ini) file.

**Comment by TheSnoozer** [comment]
For now it seems that the issue was answered and thus I'm going ahead and close this as part of an issue cleanup. Feel free to reopen if you don't get it to work and also make sure to download the latest development build (https://ci.appveyor.com/project/ORelio/minecraft-console-client) before you try again ;)
