### ISSUE TITLE
/move

### ISSUE THREAD

**Issue by Zharki** [ORelio/Minecraft-Console-Client#381]
I get the problem "you cant do commands until you have moved atleast 1 block."
Can someone explain how i get it to move 1 block. I dont know what /move means i have read that on many other posts and all i see is /move but i typed that and it does nothing please help

**Comment by Pokechu22** [comment]
`/help move`

> ```
> move <get|up|down|east|west|north|south|x y z>: walk or start walking.
> ```

**Comment by TheGurpple** [comment]
How do /move with “walk” or “start walking” ?

**Comment by ORelio** [comment]
Unfortunately you cannot move forward indefinitely. You can only move one block at a time, or to specific coordinates through pathfinding.

**Comment by Gamer745** [comment]
I have a different issue with /move 
So when I have a block thats not full but it can still move through (like string) it doesnt move forward. I guess because it thinks its a full block. Im using /move (direction)  is there a setting to fix this? Also with path finding/ cords it just goes around it even though it could go through or in my case activate a pressure plate by standing on it instead it just goes around or doesnt move any further.

**Comment by rokplays** [comment]
it says i moved but when I check the console of the server I haven't moved!
