### ISSUE TITLE
Remote Control issue

### ISSUE THREAD

**Issue by DarkCobra18** [ORelio/Minecraft-Console-Client#388]
Hi.
I have a problem I have tried remote control on servers and it works perfectly but on servers with a ranking system it does not work and I think it is because it does not detect my name when having the range.
When I send / tell Bot it goes like this https://gyazo.com/f8ee4297507b6e5680f2a0b1f4bfe081

You could help me?, I would appreciate it very much

**Comment by ORelio** [comment]
Yes you need to define a custom chat format, as per [detecting chat messages](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/config/README.txt#L164).
I'd suggest this regex for the chat format shown in your screenshot:
````
^\[(?:\[[^\]]+\] )([A-Za-z0-9_]+)(?: <[^>]+>) -> yo\] (.*)$
````
I wrote it so that the `[Manager]` and `<Trapea2>` parts are optional so it'll work if they are missing.
See https://regex101.com/r/BDRuVo/1 for a live example of the regex.

**Comment by DarkCobra18** [comment]
Today I have tried it and it still does not work This is my configuration: https://gyazo.com/b9d353801bcb0b87e0c529ad71c767ef

**Comment by DarkCobra18** [comment]
ok I have already solved it thanks for the help

**Comment by ORelio** [comment]
OK good :)
