### ISSUE TITLE
Can the Console Client use plugins?

### ISSUE THREAD

**Issue by Malvagio87** [ORelio/Minecraft-Console-Client#398]
My goal is to relay a specified chat channel from in game to discord.  I do this currently by using https://github.com/Gjum/Chat-to-Discord but i'd much rather not have to have a gui based mc client open all the time to do this and thus started poking around with your console client.  As i am a novice when it comes to this stuff im simply asking is there a way to run mc based plugins via the console and if not is there a way to relay in game chat to a discord channel using webhooks like the above plugin does?  Thanks in advance for taking a look at this.

**Comment by Pokechu22** [comment]
MCC cannot run mods written for forge, as it isn't written in Java.

You _can_ write scripts for MCC, but you'd have to set it up yourself (find something for the discord API in C#, and use that).  I haven't done anything like that myself, so I can't really help you with that.

**Comment by TheSnoozer** [comment]
The idea here is related to https://github.com/ORelio/Minecraft-Console-Client/issues/258.
I'm closing this as part of an issue cleanup and mainly being tracked in the referenced ticket.
Feel free to reopen if you have any further questions regarding this specific issue. Otherwise i would recommend to open a new issue.
