### ISSUE TITLE
TerrainMove bug?

### ISSUE THREAD

**Issue by WytePvP** [ORelio/Minecraft-Console-Client#401]
So look, 
Im not too good with all this but, when I change the terrainmovements from false to true the console crashes with a couple paragraphs popping up for a few seconds before the crash. Can you help?
I changed the command from:
terrainandmovements=false #uses more ram, cpu, bandwidth
To:
terrainandmovements=true #uses more ram, cpu, bandwidth

I tried to AntiAFK and that command worked, I changed the seconds the command was typed and all, and it all worked, but the terrain movements is what I really need at it crashes the game, help please!

Version used: v1.9.0 for Minecraft 1.4.6 to 1.9.0 :

**Comment by Pokechu22** [comment]
Please, update to [the latest build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts); you're using one that's several years old.  Even if you don't need 1.12.2 support because the server you're playing on is horribly outdated, there have been other fixes that also affect older versions of the game.
