### ISSUE TITLE
Random Disconnection

### ISSUE THREAD

**Issue by Kingofweirdos01** [ORelio/Minecraft-Console-Client#426]
I keep randomly getting disconnected every 2 min and then when the account relogs it keeps giving a incorrect password message even though the password is correct and I have ensured that it is correct. It is rather annoying because it makes it so I can't afk

**Comment by ORelio** [comment]
Make sure your Mono version is equal or greater to 4.0 to reduce disconnections. Too many logins will lead to the Incorrect Password error due to rate limiting, make sure session cache is enabled in INI file. Also just in case, make sure you have the latest MCC version as per download instructions on the repository's main page.
