### ISSUE TITLE
Using custom authentication and session server

### ISSUE THREAD

**Issue by Forever008** [ORelio/Minecraft-Console-Client#429]
Hello!! We cannot go to an unofficial server. To start, you need to use your own parameters --session, --uid, --access Token . How to replace on your own? Tried to edit the file SessionCache.db, but failed to open it. Sorry for my English.

![console](https://user-images.githubusercontent.com/38894170/39494177-111a3768-4d9e-11e8-8637-b3293e7a6cde.png)

**Comment by ORelio** [comment]
Are you sure your server is not requiring a modded client? Because even started with these arguments, the official client would try to use the official session servers when joining the server.

**Comment by Forever008** [comment]
The server uses its own launcher with its authorization. And uses its own session, uid, Access Token. I think if you pass these parameters to Minecraft-Console-Client then I get to go to the server.

**Comment by ORelio** [comment]
I'm not sure that would work, but try using the latest [development build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts) while making sure disk session cache is enabled? It should create a `SessionCache.ini` in which you can set your own uuid and access token. However, I think that the official session servers won't accept this unless they originate from an official Minecraft account.

**Comment by Forever008** [comment]
I have successfully replaced the uuid and sessionID that way.
![c](https://user-images.githubusercontent.com/38894170/39663233-4007fcea-5078-11e8-98a1-913b413f02da.png)

But it didn't work. Having studied the code in detail, I realized that uuid and sessionID is sent to the server "https://sessionserver.mojang.com/session/minecraft/join"
![post-minecraft-console-client](https://user-images.githubusercontent.com/38894170/39663248-7a95461a-5078-11e8-8557-9841a5ee0f73.png)

Then I checked the POST and Get requests of the client that uses my server.
![post-get-java](https://user-images.githubusercontent.com/38894170/39663259-a475c0e0-5078-11e8-997a-eaf8728ca1a8.png)

Then I tried to replace the server with "http://ex-server.ru/exUUIDAuth.php?action=join"
![join](https://user-images.githubusercontent.com/38894170/39663271-d86dd586-5078-11e8-9d45-dda610faace6.png)

But the Post request is not sent, I suspect that this is due to the fact that "http://ex-server.ru" uses http.
Am I right or wrong? How to send an http request to http://ex-server.ru/exUUIDAuth.php?action=join?

**Comment by Forever008** [comment]
The replacement of the code I get the error CS1061. I don't know C# and don't understand this error, can't fix.
![cs1061](https://user-images.githubusercontent.com/38894170/39674345-054849c6-5153-11e8-950a-baa105de5508.png)

**Comment by ORelio** [comment]
There is no `GET` in Mojang authentication protocol so they probably put further changes in their modified version of the authentication protocol. You might want to adapt [SessionCheck](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/Protocol/ProtocolHandler.cs#L375) to do the request(s) you want, since you have a sample request & response in your screenshot. You have [DoHTTPSGet](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/Protocol/ProtocolHandler.cs#L405) and [DoHTTPSPost](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/Protocol/ProtocolHandler.cs#L428) available for that, you can edit headers as required, and you already have the modified DoHTTPSRequest which skips TLS and sends a plain HTTP request. :slightly_smiling_face:

**Comment by TheSnoozer** [comment]
As OReilo mentioned I don't think this will ever be implemented. Closing as won't fix.
