### ISSUE TITLE
Cannot coonect to the server: This version is not supported

### ISSUE THREAD

**Issue by aeqo** [ORelio/Minecraft-Console-Client#434]
https://gyazo.com/1720800e3d99fc671bd230fb12d95da3

whats happening?

**Comment by TheSnoozer** [comment]
Another thing to mention is that if you have ``mcversion=auto`` configured, try to set it to a fixed version like ``mcversion=1.8.0``. Some servers claim to support protocols that they don't support and with ``auto`` enabled this might result in such a problem.

Since this issue is quite old and has been answered, I'm closing it as part of an issue cleanup.
Feel free to reopen if you still have a problem with this specific problem. Otherwise please open a new issue.
