### ISSUE TITLE
Everything I have to type to get running on VPS

### ISSUE THREAD

**Issue by MattPlaysYT** [ORelio/Minecraft-Console-Client#440]
Hello everyone, I require some help. I know there’s some things you need to type into your vps console like mono get and other stuff like that. Wanted to see if someone can send me the full list of commands I have to do in order to get my vps running!

**Comment by TobiichiAmane** [comment]
**1.** First of all, you need to install mono: **[Official document of how to install mono](https://www.mono-project.com/download/stable/#download-lin)**
**2.** With mono installed, download the pre-compiled exe [here](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts) as described in README.md. 
**3.** Make sure you put the exe and all the dependencies in the same directory owned by you, and use **`chmod +x [exe file name]`** to mark the file as a executable. 
**4.** Use **`mono [exe file name]`** to run it. 
Good luck!

**Comment by MattPlaysYT** [comment]
Do you have a discord, so if I can talk to you 1 on 1

**Comment by TobiichiAmane** [comment]
No need for that. Just post your system info of your VPS, your tried steps and your console output here. I think I can tell you what to do.

**Comment by TheSnoozer** [comment]
General stuff I wold recommend:
```
sudo apt-get install dirmngr screen htop wget apt-transport-https
```

what you need is as outlined `mono` for a linux system (follow the instructions on https://www.mono-project.com/download/stable/#download-lin):
```
apt install mono-devel
```

Since this is quite old I'm closing this as part of an issue cleanup. Feel free to reopen if you have a more specific question on how to get things sorted. Otherwise I would recommend to open a new issue.
