### ISSUE TITLE
Failed to ping IP

### ISSUE THREAD

**Issue by Scoopipoop** [ORelio/Minecraft-Console-Client#463]
I downloaded the latest fix for it and its still not working...

http://prntscr.com/jme8t4

**Comment by ORelio** [comment]
I'll check what's wrong with the server ping request. Meanwhile, you can manually specify your server version, either when prompted, either in config.

**Comment by Barnehhh** [comment]
@ORelio I found before that when it comes to mcversion=auto, the fast srvrecords setting in the ini seems to throw that exception before successfully connecting to a server. (Switching the timeout to 10 seconds rather than 5 fixes it in most cases) Trying it for that specific server though with the 10 second time it throws this. 

https://i.imgur.com/dpgKknO.png

**Comment by RacistTimmy** [comment]
Highly suggest Aline mc version to the server version of mc, Auto doesn't help ahlot for me.

**Comment by TheSnoozer** [comment]
see also https://github.com/ORelio/Minecraft-Console-Client/issues/489#issuecomment-439757113

As described in most cases this seems to be a problem when `mcversion=auto` is in place. Try to set it to a specific version like ```mcversion=1.8.0``` inside the ```MinecraftClient.ini```

Closing this as part of an Issue Cleanup. Feel free to reopen if you still have a problem with this specific problem. Otherwise I would recommend to open a new issue.
