### ISSUE TITLE
Moving over rough terrain

### ISSUE THREAD

**Issue by CarbonNeuron** [ORelio/Minecraft-Console-Client#466]
So, when I join into my server, it requires the player to go and walk into a Class portal before they are allowed to really do anything. The path to the portal however has a slab that you must go down. And also a carpet to walk over. Is there any way I could write a bot, maybe with the c API script feature, to go over this terrain? I feel like when it trys to go down the slab, it Should just fall.. but instead gets rubberbanded back. I can post a picture of the server spawn when I am done with class.

**Comment by CarbonNeuron** [comment]
Actually, Console client doesn't seem to handle gravity anymore? I will try out different minecraft versions

**Comment by CarbonNeuron** [comment]
I found the reason why they don't fall. 
I posted a pull request to fix the issue. It is really small, seems like it was an oversight.
https://github.com/ORelio/Minecraft-Console-Client/pull/467

**Comment by CarbonNeuron** [comment]
Huh... Thats weird... It stopped working again. It worked and it was handling stairs and stuff correctly too.. Hm

**Comment by CarbonNeuron** [comment]
https://gyazo.com/efb5ce96722bd3c841eb8c409ce4b399
I turned that option off. The client is right infront of me. it still has the coords from the hub server

**Comment by CarbonNeuron** [comment]
Hold on a second... Where is it getting those values?? That is no where near its location. And it definitely is not the location of a hub..
https://gyazo.com/b302f04b970e6a041d732ecda4fc4cb8
Thats the coords of the hub.

**Comment by CarbonNeuron** [comment]
https://gyazo.com/e4604b62fbcdb2c238194dea3d3510ff
Heres a picture of it in the hub, Everything looks right, untill you see its Y-value. It's way off

**Comment by CarbonNeuron** [comment]
Ok. This is strange. Suddenly my other other accounts start working?? what!!? This is so weird...

**Comment by CarbonNeuron** [comment]
It probably is because of when the bots spawn in for the first time, they are at Y=81.5 And on ground specifys that there should be no block below them, in one block.

**Comment by ORelio** [comment]
OK, so to explain why you are facing your issue: The server sends terrain data, then it is up to the client to interpret that data and move appropriately. The server will not make you fall, the client (MCC) has to do it. To do it, MCC has to compute the ground level. Currently, MCC only checks which blocks are solid and which blocks are not, then move appropriately to the edge of the block. However, if the block is not a full block but a slab or a carped, MCC does not have size information and treat them as full blocks. This will not work if the server has some anti-cheat measures because the server will think MCC is trying to fly.

So put it shortly, if you are willing to fix this issue I'd suggest to add block thikness information to [Material.cs](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/Mapping/Material.cs) such as a `getBlockThickness()` method that would return 1 unless the block is a slab, carpet, and so on, then it would return the correct thickness. And finally, adapt [Movement.cs](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/Mapping/Movement.cs#L33) so that MCC falls to the correct height. I'd gladly merge your pull request :slightly_smiling_face:

**Comment by Voltikenzi** [comment]
> OK, so to explain why you are facing your issue: The server sends terrain data, then it is up to the client to interpret that data and move appropriately. The server will not make you fall, the client (MCC) has to do it. To do it, MCC has to compute the ground level. Currently, MCC only checks which blocks are solid and which blocks are not, then move appropriately to the edge of the block. However, if the block is not a full block but a slab or a carped, MCC does not have size information and treat them as full blocks. This will not work if the server has some anti-cheat measures because the server will think MCC is trying to fly.
> 
> So put it shortly, if you are willing to fix this issue I'd suggest to add block thickness information to [Material.cs](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/Mapping/Material.cs) such as a `getBlockThickness()` method that would return 1 unless the block is a slab, carpet, and so on, then it would return the correct thickness. And finally, adapt [Movement.cs](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/Mapping/Movement.cs) so that MCC falls to the correct height. I'd gladly merge your pull request 🙂

Im pretty confused on how i would code in this data, could you give an example on how I would add this in?
