### ISSUE TITLE
Auto-Respawn?

### ISSUE THREAD

**Issue by CarbonNeuron** [ORelio/Minecraft-Console-Client#482]
When the alts die, they cannot send chat messages, I dont know if the server sends the message, or if mcc does, but the message is "Cannot send chat message". Is there a way to when this is received the bot can respawn?

**Comment by CarbonNeuron** [comment]
I also am having an issue where the bots just.... Stop? They keep saying that they are sending the anti afk message, but are not connected to the sever anymore. They dont get a disconnected message either, making me think that they just miss the disconnect packet. Most of the time I can fix it by reboot my proxy, triggering them to reboot. But sometimes its like their threads fall asleep and dont respond untill I force /reco on them, or have to reboot the program

**Comment by Pokechu22** [comment]
The "cannot send chat message" is a server thing (ish) that happens when you try to send a chat message while dead (or when chat's disabled).  I believe you have to use `/reco` to respawn... but the server should also tell the client when it's dead (though I don't recall if there's a specific packet, or entity metadata).

Actually, I do remember seeing once or twice something like "you are dead" upon death, and it looks like that code still exists:

https://github.com/ORelio/Minecraft-Console-Client/blob/b1a66791a1f76a6819f07cf77884eb412d4a094f/MinecraftClient/Protocol/Handlers/Protocol16.cs#L155-L158

… but only for the 1.6 protocol.  Implementing it for newer versions would be harderer, because entity metadata (which does seem to be what that is) is a bit more complex and has changed a fair amount between versions.  It also looks like there isn't a bot event for when that happens.

**Comment by CarbonNeuron** [comment]
The command is /respawn to respawn. Could we set up like auto reply to the message with /respawn?

**Comment by ORelio** [comment]
Use the AutoRespond bot?

**Comment by CarbonNeuron** [comment]
Is it a message that it sees though?

**Comment by Pokechu22** [comment]
"cannot send chat message" is generated by the server, so yes, it should be seen.

**Comment by CarbonNeuron** [comment]
Will try when I get home

**Comment by CarbonNeuron** [comment]
This does work, Thanks!

**Comment by adrielalfeus03** [comment]
but how
i try when i died
it will send /respawn
but client said unknown command``

[Match]
match=Goodbye Cruel
actionother=/respawn

**Comment by Yugnat2412** [comment]
It still doesn't work for me, it doesn't recognize the "cannot send text message" message :(
