### ISSUE TITLE
Any fix to blacklisted ip ?

### ISSUE THREAD

**Issue by Superbicz** [ORelio/Minecraft-Console-Client#488]
Hey there i been using console clients to afk my alts and recently i been getting this problem they will run perfectly fine until a server crashes making them relog or if i Relog all cc and restart them i get this

https://gyazo.com/825cef13107fe7ecb570edeb88d78b44

i heard i can bypass with vpn or something this makes afking no possible.

**Comment by ORelio** [comment]
Make sure you deleted SessionCache.db, have set sessioncache=disk in config and you use the latest developpement build.

**Comment by Nate278** [comment]
I've done both of these things. I still cannot connect to the server due to a blacklisted IP or invalid login credentials even though I've been typing in my password and username correctly. Any fix? @ORelio

**Comment by gandiber** [comment]
Same thing is happening to me, and the same proxy and account works with another bot called OQMineBot.

**Comment by TheSnoozer** [comment]
The reason for this issue is that mojang 'temporarily' blacklisted your IP. In most cases the reason for this message is that the authentication failed too many times in a row. Usually your IP will be unblacklisted within 1 hour. If you are using a VPN turn it off and try again (after waiting one hour).

If the problem persists contact Mojang.

Feel free to reopen if you have any further questions regarding this particular issue.

**Comment by ORelio** [comment]
This happens when performing many authentication attempts, regardless of whether they succeed or not. So using the session cache is essentials to avoid making any useless authentication attempt. Session cache is enabled by default on recent builds, unless you use a configuration file from a previous version. In that case, set `sessioncache=disk` in config.
