### ISSUE TITLE
unable to auto respawn when dead

### ISSUE THREAD

**Issue by Blaze420z** [ORelio/Minecraft-Console-Client#549]
trying to auto respawn but it does not allow the commands to go thru when im dead
how do i get console client to auto respawn like a hacked client does please helpD;

**Comment by Blaze420z** [comment]
id i type the command in the console client it works but i would like it to auto respawn but i cant get it to cause commands wont go thru when you die inless you type it in manually

**Comment by ORelio** [comment]
Try using `AutoReponse` to detect the "you are dead" message, to run the `respawn` MCC command.

**Comment by Yugnat2412** [comment]
Hello, I'm struggling with the same issue here. Since there is a chat message config, I think the bot doesn't read the death message. I match 'Botname' with respawn, and when I say it in game with another account it works, but when it says 'Botname died' in chat, nothing happens. It probably has to do with this config for the bot to know what is a chat message and what isn't

**Comment by Yugnat2412** [comment]
I fixed it ! I didn't know actionother was for this kind of messages, it's actually not too hard. One thing is the bot sends a death message only when someone else kills it, I can't code a /killbot command it seems
