### ISSUE TITLE
Implement terrain and movements for 1.13

### ISSUE THREAD

**Issue by ElvisAlro** [ORelio/Minecraft-Console-Client#576]
Hello! I saw that in the server where i play there is a plugin for "move before chat" so i cant type /is go to go to my island! So i do /move north/east/west everything and nothing 2 minutes of moving and still cant chat. I know some of the players use console client but they dont tell me how to do it!
So what to do now?

**Comment by Mhowser** [comment]
Did you enable TerrainMovements in the configuration file?


On Oct 16, 2018 1:33 AM, "ElvisAlro" <notifications@github.com> wrote:

Hello! I saw that in the server where i play there is a plugin for "move
before chat" so i cant type /is go to go to my island! So i do /move
north/east/west everything and nothing 2 minutes of moving and still cant
chat. I know some of the players use console client but they dont tell me
how to do it!
So what to do now?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/ORelio/Minecraft-Console-Client/issues/576>, or mute
the thread

**Comment by ElvisAlro** [comment]
Yes i enable it !

**Comment by TheGurpple** [comment]
Do you play one pvpwars? And I as well have the same problem! If you figure it can you please tel me! Thanks

**Comment by ElvisAlro** [comment]
Yes pvpwars ! Im working on it but its hard! ur IGN ?

**Comment by TheGurpple** [comment]
TheGurpple, and I play on matrix !

**Comment by monkeysaww** [comment]
I'm having the same problem. Other players have been able to get past this because there are a lot of people on pvpwars that use this. My alt moves when I use /move <direction> but it never seems to satisfy that "You must move before chatting or using commands" Let me know if you guys figure it out. I play matrix too

**Comment by Mhowser** [comment]
TerrainMovement is not functional for versions 1.13 and up due to the new
"block flattening" code.

**Comment by ORelio** [comment]
Closing this one since #599 was the last step for 1.13 😉
