### ISSUE TITLE
Cant do any commands?

### ISSUE THREAD

**Issue by LordDakota** [ORelio/Minecraft-Console-Client#589]
When I join a server i can do '/server wither' to get into the server but i cant do '/tpaccept' any ideas? There are more commands that i cant do aswell. Thanks

**Comment by TheSnoozer** [comment]
You play saico?
If so this is due to their "anti-cheat" that checks what client you use.
By default the console client tells the server it is a console client (the option `brandinfo` inside your `MinecraftClient.ini`).

set it to
```
brandinfo=vanilla
```
and try again (that's the brand the is sent by the default client - see https://wiki.vg/Plugin_channels#minecraft:brand)

**Comment by TheSnoozer** [comment]
I'm closing this issue since I think I answered the question (and since I know that server, I know that fixed this particular problem in the past). If you still have an issue in getting this setup, please reopen this. Otherwise I would recommend to open a new issue.
