### ISSUE TITLE
can't use the variable %username% in matches.ini

### ISSUE THREAD

**Issue by CdeJong** [ORelio/Minecraft-Console-Client#608]
`[Match]
regex=^.*((?!Koalert_|The_Lookalike)[a-zA-Z0-9_]{3,16}).*(?i)(hey|hello|hi)(?-i).*$
actionother=send /p $2 $1!
ownersonly=false`

This Code will react with `hello steve!` if steve says hello. to prevent a loop I added `(?!Koalert_|The_Lookalike)`. so that the code wouldn't react to those accounts (bots), but that is not efficient. Is there a way to ignore only the used account (in MCC)?

If it is not possible to do this at the moment, maybe add this variable in the future?

Thanks in advance,
 -Chris

**Comment by ORelio** [comment]
Better late than never:
If you need to use `actionother`, then it means MCC cannot detect chat messages properly. You need to define chat format regexes in config file to tell MCC how to parse chat from your server, then you can use `action` instead of `actionother` and have access to the sender as `$u` in your `action` field. Additionally, as long as usernames are detected properly, the bot will automatically ignore messages sent by itself.

**Comment by TheSnoozer** [comment]
Since this seems to be a very old issue and has been answered I'm going ahead and close this as part of an issue cleanup. Feel free to open a new issue if you still got a question or problem.
