### ISSUE TITLE
Chat Log/Remote Control Bot's do not support HeroChat

### ISSUE THREAD

**Issue by JamieSinn** [ORelio/Minecraft-Console-Client#63]
They do not support the message format.

Default Message format
[CHANNEL NICK, DEFAULT IS G] [Rank] User: Message
Eg.
[G] [Developer] JamieSinn: Message here.

mc.ecocitycraft.com for an example test server.

I'll comment with the logs of the errors soon

**Comment by ORelio** [comment]
Will take a look at this, thanks for your report.

**Comment by ORelio** [comment]
HeroChat should now be fully supported based on your commit 89ccc9d22d6c30ca0a466d47b1054330b9b203ee for private messages, and the sample message you provided above for public messages.

**Comment by ORelio** [comment]
Hello,
I'm reviewing chatBot message processing and noticed that `[Channel] [Rank] User: Message` syntax is detected as a private message instead of a public message as the associated code is in `isPrivateMessage` instead of `isChatMessage`. Is that intended, or should I move this code to detect this syntax as a regular chat message?

**Comment by JamieSinn** [comment]
You can move it if you'd like, I had it there just for what I was using it with

**Comment by ORelio** [comment]
Okay, thanks for your response I'll move it in `isChatMessage` as it seems more relevant.
