### ISSUE TITLE
ChatLog Bot crashes upon enable

### ISSUE THREAD

**Issue by JamieSinn** [ORelio/Minecraft-Console-Client#64]
Problem signature:
  Problem Event Name:	CLR20r3
  Problem Signature 01:	MinecraftClient.exe
  Problem Signature 02:	1.8.0.0
  Problem Signature 03:	54e7b24b
  Problem Signature 04:	mscorlib
  Problem Signature 05:	4.0.30319.34209
  Problem Signature 06:	534894cc
  Problem Signature 07:	4599
  Problem Signature 08:	25
  Problem Signature 09:	System.ArgumentException
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	1033
  Additional Information 1:	0a9e
  Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
  Additional Information 3:	0a9e
  Additional Information 4:	0a9e372d3b4ad19135b953a78882e789

Error in console:
http://prntscr.com/67qk0p

ini relevant areas.

[ChatLog]
enabled=true
timestamps=true
filter=all
logfile=chatlog-%username%-%serverip%.txt

chatbotlogfile=chatlog-%username%-%serverip%.txt

**Comment by ORelio** [comment]
Thanks for your detailed report! There was a crash because the app was trying to create a directory for storing your log file, but the directory was empty since your config specify a log file in the same folder. This is now fixed, meanwhile, a workaround could be changing logfile=chatlog[...] into logfile=logs\chatlog[...] :)
