### ISSUE TITLE
Mono + TriggerOnLogin / TriggerOnFirstLogin doesn't work

### ISSUE THREAD

**Issue by Tomoli75** [ORelio/Minecraft-Console-Client#644]
I can't tell whether mono isn't passing the argument, MCC doesn't understand it or whether the actual files are broken.

`[Task]
triggerOnFirstLogin=true
triggerOnLogin=true
triggerOnTime=false
triggerOnInterval=false
script=startup.txt`

`wait 5
move down
wait 10
send /join 10530
wait 5
move down
wait 40
send @%username%
wait 40
send @Leaving the game
wait 10
exit`

**Comment by Mhowser** [comment]
What Minecraft version is the server? If it's 1.13 move does not work
anymore due to the new world format.

**Comment by Tomoli75** [comment]
1.13.2, but the move line isn't needed.

**Comment by Tomoli75** [comment]
Oh and the move still works anyway :)

**Comment by AGuyNamedJens** [comment]
This client doesnt work on my raspberry PI, Whenever its in the hub of the server it wont do any bots..

No auto connect to skyblock, no auto messages...
Only does this in the skyblock server but when the skyblock reboots/client reconnects to the server, it won't work because its in the HUB again.. Any fix?

**Comment by Tomoli75** [comment]
Maybe make a new issue, not take over another?

**Comment by TheSnoozer** [comment]
Could you perhaps try to test this with the latest development build (https://ci.appveyor.com/project/ORelio/minecraft-console-client)?

**Comment by ORelio** [comment]
Should be fixed as per #629
