### ISSUE TITLE
Cant login multiple accounts at the same time

### ISSUE THREAD

**Issue by KOoRnFLaKes** [ORelio/Minecraft-Console-Client#658]
So i have 5 bots running 24/7 and when the server restarts they all relog at the same time and because of that 1 logs and the other 4 says the connection throttled or someting like that

**Comment by Mhowser** [comment]
The server sees multiple connection attempts from a single ip address
(yours) and it is set up to only allow one connection every X seconds. You
need to add a time delay in your bot script, typically 5 seconds is enough.

I don't remember the command to make a time delay in the script
unfortunately, but I am confident that is what you need to do.

**Comment by KOoRnFLaKes** [comment]
up

**Comment by TheSnoozer** [comment]
``wait`` is the command to wait a certain amount of seconds.

Eg.:
```
send /server <RealmName>
wait 10
```

**Comment by TheSnoozer** [comment]
Since this seems to be a very old issue and has been answered I'm going ahead and close this as part of an issue cleanup. Feel free to open a new issue if you still got a question or problem. Before you try again make sure to download the latest development build (https://ci.appveyor.com/project/ORelio/minecraft-console-client).
