### ISSUE TITLE
Cant log more than 1 alt

### ISSUE THREAD

**Issue by Kakaze302** [ORelio/Minecraft-Console-Client#690]
Already checked the settings and all of them seem fine. When I start the console client 1 account gets in the server but the others log a Network Error connecting to Minecraft.net already checked mojang status and the details all seem fine

**Comment by TheSnoozer** [comment]
Try:
1) download the latest development build (https://ci.appveyor.com/project/ORelio/minecraft-console-client)
2) set `debugmessages=true` inside your `MinecraftClient.ini`
3) instead of `mcversion=auto` inside your `MinecraftClient.ini` try to set it to a fixed version like one you know is being used by the server e.g. `mcversion=1.8.0`
4) Post error messages (if available)
