### ISSUE TITLE
Scripts do not work on Ubuntu

### ISSUE THREAD

**Issue by marvic2409** [ORelio/Minecraft-Console-Client#700]
When I try to do a script with automated commands and login, it does not run because the script wont write into mono

**Comment by TheSnoozer** [comment]
Can you provide more context? Are you trying to use MCC-Scripts like [this](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/config/sample-script-with-chatbot.cs), or using the AutoRespond or ScriptScheduler with it's `task.ini`?

**Comment by TheSnoozer** [comment]
Since this seems to be a very old issue and there was no response I'm going ahead and close this as part of an issue cleanup. Feel free to open a new issue if you still got a question or problem. Feel free to reopen if you don't get it to work and also make sure to download the latest development build (https://ci.appveyor.com/project/ORelio/minecraft-console-client) before you try again ;)
