### ISSUE TITLE
Cant Connect / not supported version (1.13)

### ISSUE THREAD

**Issue by SeichiSenpai** [ORelio/Minecraft-Console-Client#701]
Im new to Console client but im already having trouble such as not being able to connect to 1.13 servers , even though i did change the ver in the minecraftclient notepad also i typed the specific ver and its still not working as intended heres a screen shot
![image](https://user-images.githubusercontent.com/49830039/56467105-88f7b680-6444-11e9-8846-38dcfc69927b.png)

**Comment by ORelio** [comment]
You are not the latest version, this version can only run up to MC 1.9.0. Grab latest version here: [development builds](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts). Just added an additional warning to the [releases](https://github.com/ORelio/Minecraft-Console-Client/releases) section since you are not the first one heading to that section without reading the repository's README displayed on the [main page](https://github.com/ORelio/Minecraft-Console-Client). Feel free to reopen if it still does not work with latest version 😉
