### ISSUE TITLE
Multiple AVs and Firefox detecting virus as malware.

### ISSUE THREAD

**Issue by Fiiily** [ORelio/Minecraft-Console-Client#707]
Not as unknown or something, Firefox straight up states that the program **is a virus** and **will** cause unintended effects. Copy obtained from https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts and VirusTotal here: https://www.virustotal.com/#/file/b0a1b23c264cde2468d1678c4a40e87d55bcf6d4f9e03bf6366a536dd18811d8/detection

Multiple AVs seem to be flagging Minecraft Console Client as an "Ursu" trojan.

**Comment by ORelio** [comment]
Hi,

Thanks for reporting this. This comes as a surprise because artifacts are generated by AppVeyor from the source code hosted here on GitHub, no third party including myself is producing the binaries.

It is too early to tell whether it is a false positive or an actual infection, since AppVeyor might have been compromised.

Will look into this.

**Comment by ORelio** [comment]
Update:

I can confirm that last few dev builds from AppVeyor are detected by Windows defender to be infected by a Trojan, while manually compiled build is not. There is definitely something on their side.

The latest dev build, launched today when implementing #599 seems to be clean, with only 1 detection due to the new exe being (obviously) unknown to the AV: https://www.virustotal.com/#/file-analysis/ZWI3ZWM1OGMxNWYyMzVjYTg1ZTI0YzdlOTRmMjY2NzI6MTU1NjIyNzIyMw==

I hope AppVeyor will not be caught again infecting dev builds with trojans. If this happens again, I think I will look for a different dev build service.

Thanks again for reporting this.

**Comment by Fiiily** [comment]
What the fuuuck? It's not a one-strike-out sort of situation for your CI service propagating malware using your software?

**Comment by ORelio** [comment]
In a professional context, for sure. However, this is a hobby project and we're using AppVeyor for free, so, well, we get what we pay for. Apart from this issue 2 weeks ago, AppVeyor has been working well for the last 4 years with no malware in the produced executables.

**Comment by TheSnoozer** [comment]
also to add: Antivirus software can be wrong too. It can detect a file as virus, but the actual file is harmless. Even worse it can tells you a file is safe, but in fact it's a virus. Usually an antivirus gives you an indicator, but that can be simply wrong.

If you don't trust the build system: clone the sources, read & understand the code offline, ensure it contains no virus, build it from source yourself. The steps needed to build are even listed in the `console`-Tab of the build system (https://ci.appveyor.com/project/ORelio/minecraft-console-client)
