### ISSUE TITLE
Factionbots.com Violation of license

### ISSUE THREAD

**Issue by CarbonNeuron** [ORelio/Minecraft-Console-Client#709]
Here is a conversation I had with the developer of Factionbots. They are modifying parts of this code and selling it. Which is a violation of the license of this project. 
![Violation](https://user-images.githubusercontent.com/16768821/56755014-18a6a900-6754-11e9-97d1-8b4494570e3f.png)

**Comment by ORelio** [comment]
Hi,
Thank you for reporting this.
To make it clear, I have set for this project a license that does allow commercial use.
However, improvements and bug fixes made to the core program must be published free of charge. This includes changes made to existing files and potential new filed created as a dependency for them. So in MCC, this includes improvements such as support for new MC versions, packets (e.g. inventory), additions to the chatbot API, but not custom bots and config files that the author is free to sell without publishing anything.
I need to properly review the license details before taking any actions.

**Comment by CarbonNeuron** [comment]
It does look like the person has made additions like inventory handling. They are violating the TOS of their hosting provider aswell.

**Comment by CarbonNeuron** [comment]
Also, by looking at the CDDL-1.0 license, they are allowed to sell it. ASLONG as they provide Source code with every executable. 

> 3.1. Availability of Source Code.

Any Covered Software that You distribute or otherwise make available in Executable form must also be made available in Source Code form and that Source Code form must be distributed only under the terms of this License. You must include a copy of this License with every copy of the Source Code form of the Covered Software You distribute or otherwise make available. You must inform recipients of any such Covered Software in Executable form as to how they can obtain such Covered Software in Source Code form in a reasonable manner on or through a medium customarily used for software exchange.

**Comment by CarbonNeuron** [comment]
If this is a violation that you would like to take action on, You can file an infringment claim with paypal
https://www.paypal.com/us/webapps/mpp/ua/infringementrpt-full
for the account factionsbot@gmail.com

**Comment by xPenguinx** [comment]
> It does look like the person has made additions like inventory handling. They are violating the TOS of their hosting provider aswell.

We have not made any additions

**Comment by ORelio** [comment]
Hi @xPenguinx,
Let me clarify the reasoning behind choosing CDDL-1.0 for Minecraft Console Client:
 - I do not want to refrain people from using MCC for commercial purposes. You can, the license allows it and I encourage you to do so.
 - However, in exchange from having the project source code free of charge and the ability to make profit from it, we expect commercial developers to contribute back to the community by helping us to maintain and expand the project. Since you'll likely have to implement additional packets and update for new Minecraft versions, it seems legitimate to contribute that back to the project, and actually, the license requires you to do so by publishing the modified code if you publish or sell your binaries. Plus, it will make your work easier as you'll have less code to reinsert in newer MCC versions and the community will maintain/improve it.
 - The added value in your commercial program, which is the bot included in your modified MCC build that automates things and people are willing to pay for, is not included in the previous requirement. Keep it closed source and continue selling it as you wish. Seems a fair deal to me 😉

**Comment by xPenguinx** [comment]
> Hi @xPenguinx,
> Let me clarify the reasoning behind choosing CDDL-1.0 for Minecraft Console Client:
> 
> * I do not want to refrain people from using MCC for commercial purposes. You can, the license allows it and I encourage you to do so.
> * However, in exchange from having the project source code free of charge and the ability to make profit from it, we expect commercial developers to contribute back to the community by helping us to maintain and expand the project. Since you'll likely have to implement additional packets and update for new Minecraft versions, it seems legitimate to contribute that back to the project, and actually, the license requires you to do so by publishing the modified code if you publish or sell your binaries. Plus, it will make your work easier as you'll have less code to reinsert in newer MCC versions and the community will maintain/improve it.
> * The added value in your commercial program, which is the bot included in your modified MCC build that automates things and people are willing to pay for, is not included in the previous requirement. Keep it closed source and continue selling it as you wish. Seems a fair deal to me 😉

Thanks for replying! As for contributing to the project, I have been learning and figuring out the protocol and willing to contribute.
