### ISSUE TITLE
Buildpack for Heroku

### ISSUE THREAD

**Issue by masterco465** [ORelio/Minecraft-Console-Client#711]
Are you able to link the buildpacks that I can use to deploy the console client onto heroku so that the client can afk my account 24/7. I tried several different "dotnet" and "mono" buildpacks (you stated those as system requirements in minecraftforum) but kept getting errors.

Buildpacks
**dotnetcore:** https://github.com/jincod/dotnetcore-buildpack
**Mono:** https://github.com/AdamBurgess/heroku-buildpack-mon

**Error**
 _-----> App not compatible with buildpack: https://github.com/jincod/dotnetcore-buildpack
       More info: https://devcenter.heroku.com/articles/buildpacks#detection-failure
 !     Push failed_

Any insights? Appreciate any advise

**Comment by ORelio** [comment]
Hi,
I am not familiar with cloud computing deployments and have not tried to automatically deploy MCC. Seems like the error is caused by the .NET image not being compatible with the cloud service rather than MCC itself. Anyway, if you can deploy a Linux image having Mono installed and MCC binaries & config on the disk image, it _should_ work. For instance, Ubuntu with `mono-runtime libmono-reflection-cil ca-certificates-mono` packages 🤔

**Comment by josephisticated** [comment]
> Are you able to link the buildpacks that I can use to deploy the console client onto heroku so that the client can afk my account 24/7. I tried several different "dotnet" and "mono" buildpacks (you stated those as system requirements in minecraftforum) but kept getting errors.
> 
> Buildpacks **dotnetcore:** https://github.com/jincod/dotnetcore-buildpack **Mono:** https://github.com/AdamBurgess/heroku-buildpack-mon
> 
> **Error** _-----> App not compatible with buildpack: https://github.com/jincod/dotnetcore-buildpack More info: https://devcenter.heroku.com/articles/buildpacks#detection-failure ! Push failed_
> 
> Any insights? Appreciate any advise

have you been able to do it?
