### ISSUE TITLE
VirusTotal suspcious

### ISSUE THREAD

**Issue by shyamdesai03** [ORelio/Minecraft-Console-Client#713]
Just want you to know that the past few versions (This version is the one fixing issue #710) that I've been detecting viruses. Hopefully you can resolve the issue

https://imgur.com/a/wuatixj

**Comment by ORelio** [comment]
Hi,

For your information, development builds are generated by AppVeyor from the source code hosted here on GitHub, no third party including myself is producing the binaries.

As far as I know, the "low score" report means that the executable is not well known to the Antivirus, which is normal for a fresh dev build. This cannot be resolved because it is normal behavior.

This does not mean you should blindly trust an AppVeyor build, I encourage you to keep scanning them, but you should worry only if your VirusTotal result looks like this:

![image](https://user-images.githubusercontent.com/1128206/56867543-a5689580-69e6-11e9-8861-9d3f77542f93.png)

The red signal here is that many AntiVirus are triggering and/or some signatures specifically flag the file because it contains a Trojan (not because of an unknown/low-score program).

(Screenshot from #707 when a build had a Trojan included due to an infection on AppVeyor).
