### ISSUE TITLE
Relay messages to Discord

### ISSUE THREAD

**Issue by masterco465** [ORelio/Minecraft-Console-Client#715]
"Yeah, all you need to do is to integrate a c# discord module into the project. Then, write a chatbot that overrides the gettext thing. Which should tell the discord client to post.
 If you're just looking for a one way communication, say bot to discord, it's alot easier because discord offers an endpoint for webhooks. Which just need you to make an http request to them in order to post a message. 

The only issue with this is discords rate limiting. If the server sends alot of chat messages, you will be rate limited."

_Originally posted by @CarbonNeuron in https://github.com/ORelio/Minecraft-Console-Client/issues/620#issuecomment-453364756_

Can anyone provide a guide to hook up Console Client to webhooks? Not too sure how to approach this, any help would be appreciated.

I'd say the script in Issue #694 might have been close to solving it, maybe @EchoesNetwork can upload his script?

**Comment by EchoesNetwork** [comment]
Hey!

My script uses Python to send a webhook to Discord. It has no input for chat or anything. I’ll happily post it here if you’re still interested, but #694 is still unresolved as I haven’t been able to get it to work. 

I am also very interested in learning to use Discord webhooks with MCC solely in C# so I’ll keep an eye on this thread! Thanks for making it! 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by shyamdesai03** [comment]
> Hey!
> 
> My script uses Python to send a webhook to Discord. It has no input for chat or anything. I’ll happily post it here if you’re still interested, but #694 is still unresolved as I haven’t been able to get it to work.
> 
> I am also very interested in learning to use Discord webhooks with MCC solely in C# so I’ll keep an eye on this thread! Thanks for making it!
> 
> Sent with [GitHawk](http://githawk.com)

Yah! That would be appreciated

**Comment by JordanAuthxr** [comment]
> Hey!
> 
> My script uses Python to send a webhook to Discord. It has no input for chat or anything. I’ll happily post it here if you’re still interested, but #694 is still unresolved as I haven’t been able to get it to work.
> 
> I am also very interested in learning to use Discord webhooks with MCC solely in C# so I’ll keep an eye on this thread! Thanks for making it!
> 
> Sent with [GitHawk](http://githawk.com)

Id like to see your script too please, thanks in advance!

**Comment by EchoesNetwork** [comment]
My script utilizes a pip module called discord-webhook. You can find documentation on it here:
[https://pypi.org/project/discord-webhook/](https://pypi.org/project/discord-webhook/)

I used a sample script from this page to relay messages to my MC server's discord whenever the server went down, and my script looks like this (with the webhook redacted of course):

`from discord_webhook import DiscordWebhook, DiscordEmbed

webhook = DiscordWebhook(url='YOUR WEBHOOK GOES HERE')

# create embed object for webhook
embed = DiscordEmbed(title='ECHOES ANARCHY has crashed!', description='The server will automatically restart within two minutes. If this does not happen, ping an admin.', color=242424)

# set author
embed.set_author(name='Python Downtime Monitor', url='https://echoesmc.com/wiki/bots', icon_url='https://echoesmc.com/wp-content/uploads/2018/12/transparent-server-icon.png')\

# set footer and timestamp
embed.set_footer(text='This message was produced without the help of any plugins, mods, or server wrappers whatsoever.')
embed.set_timestamp()

# add embed object to webhook
webhook.add_embed(embed)

webhook.execute()`

It's this same script I was attempting to trigger with my MCC client, using the following MCC script:

`//MCCScript 1.0

MCC.SendText("launching uptime.py");
System.Diagnostics.Process.Start("/usr/bin/python3 root/bots/uptime.py");
MCC.SendText("done.");`

However, I can never get MCC to actually execute another program, even if it's just a simple bash script. It always either says the file cannot be found, or doesn't respond at all when I try to trigger it with the `script` command.

**Comment by ORelio** [comment]
Looks good! With a ChatBot you could catch chat messages and pass them to your script 👍
Just edited your comment so that the code uses the GitHub code formater.

**Comment by EchoesNetwork** [comment]
That worked! My bot can now trigger the Python script just fine. Any idea how I'd pass the chat messages from the chat bot to Python?

**Comment by ORelio** [comment]
Sure. Start from [sample-script-with-chatbot.cs](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/config/sample-script-with-chatbot.cs) and launch your script from there. The only thing that you must take care of is command injection, e.g. players typing `"; evil-command;` in chat to execute something evil when MCC is calling your script. I'd advise to call your script this way:

```csharp
System.Diagnostics.Process.Start(
    "/usr/bin/python3",
    "root/bots/uptime.py"
        + " '" + username.Replace("\\", "⧵").Replace("'", "ꞌ")
        + "' '" + message.Replace("\\", "⧵").Replace("'", "ꞌ")
        + "'"
);
```

The trick here is to use [single quotes](https://stackoverflow.com/questions/6697753/difference-between-single-and-double-quotes-in-bash) around username and chat messages to reduce amount of bash special characters in argument string, and replacing the remaining escape characters with similar-looking Unicode characters ([Reverse Solidus Operator](https://unicode-table.com/en/29F5/) and [Saltillo](https://unicode-table.com/en/A78C/)). I think this way should be safe. 🤔

**Comment by EchoesNetwork** [comment]
Alright, I did some googling on how to go about this and I'm quite confused.

My first thought was to try and replace the text in my Python webhook script `relay.py` with the variables message and username from the C# chatbot. In retrospect it sounds kinda clunky to read and write from one file just to update some strings each time a new chat message appears, but here's the code I added just in case I was onto something:

`StreamReader reading = File.OpenText("relay.py");
string str;
while ((str = reading.ReadLine())!=null)
{
      if (str.Contains("mcchat"))
      {
          StreamWriter write = new StreamWriter("relay.py");
          string chat = File.ReadAllText("relay.py");
          chat = text.Replace("mcchat", "message");
          File.WriteAllText("relay.py", chat);
      }
}`

I got the idea to do this from [here](https://stackoverflow.com/questions/13509532/how-to-find-and-replace-text-in-a-file-with-c-sharp). It didn't work, so I moved onto another idea. I then attempted declaring variables in my Python script `relay.py` like so:
`from discord_webhook import DiscordWebhook
	mcchat=""
	mcusername=""
webhook = DiscordWebhook(url='WEBHOOK GOES HERE', username="mcusername", content='mcchat')
webhook.execute()`

And then after reading [this](https://stackoverflow.com/questions/50413721/pass-multiple-arguments-from-c-sharp-to-python) and [this](https://gist.github.com/creativcoder/6df4d349447ff1416e68) I attempted adding this line to my new C# script `DiscordRelay.cs`:

`string arg = string.Format("/root/bots/relay.py {mcchat} {mcusername}", message, username);`

I thought this would identify the variables mcchat and mcusername in the Python script and replace them with the variables message and username already declared in `sample-script-with-chatbot.cs`. I got an error about the variable arg never being used, though, so my next thought was to take the code you provided to deter command injection and modify it to include these two new lines:

`+ "message" + arg.Replace("mcchat")
+ "username" + arg.Replace("mcusername")`

In case some broader error I'm unaware of is what's causing this, here is `DiscordRelay.cs` in its entirety:
`//MCCScript 1.0

MCC.LoadBot(new DiscordBot());

//MCCScript Extensions

public class DiscordBot : ChatBot
{
    public override void Initialize()
    {
        LogToConsole("Sucessfully Initialized!");
    }

    public override void GetText(string text)
    {
        string message = "";
        string username = "";
		string arg = string.Format("/root/bots/relay.py {mcchat} {mcusername}", message, username);
        text = GetVerbatim(text);
 if (IsChatMessage(text, ref message, ref username))
        {
            System.Diagnostics.Process.Start(
    "/usr/bin/python3",
    "/root/bots/relay.py"
        + " '" + username.Replace("\\", "⧵").Replace("'", "ꞌ")
        + "' '" + message.Replace("\\", "⧵").Replace("'", "ꞌ")
        + "'"
		+ "message" + arg.Replace("mcchat")
		+ "username" + arg.Replace("mcusername")
);
        }
    }
}`
This produced the error `System.InvalidOperationException: No overload for method 'Replace' takes '1' arguments`. So I'm not sure if this is the proper thing to do in order to pass the arguments from the chatbot to the Python script. Any help would be appreciated! Thanks in advance.

**Comment by ORelio** [comment]
I think you are over complicating it. In the example I gave you, the username and message are passed as first and second arguments to your Python script. To retrieve command-line arguments, simply do the following:
````python
import sys

username = sys.argv[1]
message = sys.argv[2]

# do what you want with username and message
````
The error message you got is caused by calling `arg.Replace("mcchat")`. It expects the `search` and `replace` arguments, e.g. `"aaabbb".Replace("a", "c")` will give `cccbbb`. You must specify 2 arguments.

**Comment by EchoesNetwork** [comment]
Thanks so much! it finally works. @shyamdesai03 and @JordanAuthxr if you havent figured it out yet here are the scripts necessary:

For anyone curious about how to do this in the future, here's a copy of the script `DiscordRelay.cs` and `relay.py`

**DiscordRelay.cs:**

```c
//MCCScript 1.0

MCC.LoadBot(new DiscordBot());

//MCCScript Extensions

public class DiscordBot : ChatBot
{
    public override void Initialize()
    {
        LogToConsole("Sucessfully Initialized!");
    }

    public override void GetText(string text)
    {
        string message = "";
        string username = "";
        text = GetVerbatim(text);
 if (IsChatMessage(text, ref message, ref username))
        {
            System.Diagnostics.Process.Start(
    "/usr/bin/python3",
    "/root/bots/relay.py"
        + " '" + username.Replace("\\", "⧵").Replace("'", "ꞌ")
        + "' '" + message.Replace("\\", "⧵").Replace("'", "ꞌ")
        + "'"

);
        }
    }
}

```

**relay.py:**

```py
import sys 
from discord_webhook import DiscordWebhook

username = sys.argv[1]
message = sys.argv[2]
webhook = DiscordWebhook(url='Webhook goes here', content="<"+username+"> "+message)
webhook.execute()

```

Remember that in order for `relay.py` to function, you have to install the pip module discord-webhook. See this page for details: [https://pypi.org/project/discord-webhook/](https://pypi.org/project/discord-webhook/)

**Comment by shyamdesai03** [comment]
This is fantastic! Thanks for your support and input @EchoesNetwork & @ORelio. Any chance to integrate this with the official build?

**Comment by ORelio** [comment]
@EchoesNetwork Congrats 👍

@shyamdesai03: Likely not, since it involves an external Python script it cannot be included as a built-in bot inside MCC. But you can already load this ChatBot into an existing build with `/script`:
```
/script DiscordRelay.cs
```
You can auto-load it on login by using `ScriptScheduler` (see [config](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config)), provided you adjusted the Python script, installed it on your system, and adjusted the Python script location into `DiscordRelay.cs`.

**Comment by masterco465** [comment]
> I think you are over complicating it. In the example I gave you, the username and message are passed as first and second arguments to your Python script. To retrieve command-line arguments, simply do the following:
> 
> ```python
> import sys
> 
> username = sys.argv[1]
> message = sys.argv[2]
> 
> # do what you want with username and message
> ```
> 
> The error message you got is caused by calling `arg.Replace("mcchat")`. It expects the `search` and `replace` arguments, e.g. `"aaabbb".Replace("a", "c")` will give `cccbbb`. You must specify 2 arguments.

I'm getting this error while executing relay.py with python on Ubuntu 19.04
`File "relay.py", line 4, in <module>
    username = sys.argv[1]
IndexError: list index out of range`

**Comment by ORelio** [comment]
@masterco465 Seems like no arguments were passed to the script. Usage:
```bash
python3 relay.py 'username' 'chat message'
```

**Comment by masterco465** [comment]
The script doesn't work on some servers due to chat formatting. On this one server, only special messages are picked up such as %item% which displays the object held in hand but normal messages are not relayed.
https://imgur.com/a/mXN6U2g

**Comment by ORelio** [comment]
@masterco465: For these, you need to define custom chat formats inside `MinecraftClient.ini`.
Given your screenshot I'd say `public=^ (?:[^ >]+ )([A-Za-z0-9_]+)> (.+)$`
See https://regex101.com/r/VfYAjG/1

**Comment by masterco465** [comment]
> @masterco465: For these, you need to define custom chat formats inside `MinecraftClient.ini`.
> Given your screenshot I'd say `public=^ (?:[^ >]+ )([A-Za-z0-9_]+)> (.+)$`
> See https://regex101.com/r/VfYAjG/1

Thank you so much! It works perfectly

**Comment by EchoesNetwork** [comment]
Hey, I'm having problems with players typing @everyone and @here on my server and it being relayed to the Discord. I've tried adding a flter to DiscordRelay.cs to fix this. My filter looks like this, but it doesn't work:

 + "@here" + message.Replace("\\", "⧵").Replace("@", "&")
 + "@everyone" + message.Replace("\\", "⧵").Replace("@", "&")

I'm not sure what I'm doing wrong. This should replace the @ with an &, right?

**Comment by slaapkopamy** [comment]
Hi there,

I have a question, how does the scripts works? Since im not really coming out with the reading of the scripts or better say it says it does something but there is nothing coming in my discord channel where the webhook is made.. So can someone explain me how it works or give me an example?

By the way is there any error log files from it in windows so i can check it out why it don't send anything?
