### ISSUE TITLE
Logging account script

### ISSUE THREAD

**Issue by ventrillion** [ORelio/Minecraft-Console-Client#748]
Having trouble figuring out a script where I can log say 50+ accounts on to a server and afk them for voting rewards. After I log around 8 accounts they just go to "New Window" and stop logging to minecraft. Any thing you could come up with? I don't need any reconnect scripts or commands done. Just need to have 50+ Console Clients running :-) Thanks in advance

**Comment by ventrillion** [comment]
Is there a way to use a new proxy every account or every couple accounts?

**Comment by ORelio** [comment]
Hi,

You have two different issues in one thread, do not hesitate to create multiple issues if they are different. Nevertheless, regarding login issues, you cannot perform too many logins from the same IP address or you'll get temporarily blacklisted, I guess. See #699, #719, #731... You can hopefully solve this by making sure `sessioncache=disk` is set in config, and logging in small batches of accounts. Once all accounts are entered in the session cache, you should be able to login more accounts at a time.

Regarding proxy. I cannot see a legitimate use case for using a random proxy. Looks like a feature that would benefit spammers trying to circumvent IP bans put by server staff rather than a feature that would help users, to login when the official session server is blacklisted on your hotel, university or your VPN is blacklisted by Mojang; since in that case you would only need one proxy.
