### ISSUE TITLE
AutoResponder issues

### ISSUE THREAD

**Issue by yoshim3to** [ORelio/Minecraft-Console-Client#759]
I'm having issues with the autoresonder, or more like it's not working at all. I play a prisons server and I'm trying to get my alt account to invite certain people to my gang whenever said people message the alt "inv". However, it's just simply not working. The console client is receiving the message, but not responding to it, and I'm not sure why. Below I have put my matches.ini file and my chat log.
Matches file
> [Match]
match=[Sovereign Prison] [Yoshim3to -> me] inv
actionother=send /g invite Yoshim3to

Chat Log
> (!) Rested XP has 10 mins remaining - 1.5x XP
[Sovereign Prison] [Yoshim3to -> me] inv
Nlck has broken a Fractured Heroic Atheos G-Kit
(!) Rested XP has 5 mins remaining - 1.5x XP

I've made sure my AutoResponder is enabled in my config file, so I'm assuming it's something I'm doing wrong with the type of action. It's probably something very obvious, but please bear with me. Any help is appreciated. Thanks!

**Comment by ORelio** [comment]
Hi, for your information it seems like you need to adjust chat formats in config file so that MCC can properly detect your chat messages and process them accordingly in AutoRespond. Your private message should be processed with `actionprivate`, not `actionother` and only `inv` (the message sent in private) should be tested against your `match` string.

See also [README](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config), #579 and #712
