### ISSUE TITLE
Can't connect to this IP

### ISSUE THREAD

**Issue by LintRoll** [ORelio/Minecraft-Console-Client#762]
Console Client keeps coming up with "can't connect to this IP"
Solutions i tried: Change the #mcversion , Change the delay , Re-downloaded, Reset VPS

If anyone could help me set this up on Ubuntu 
Discord: Lint#8449

**Comment by SipriusPT** [comment]
Are you trying to connect through a DNS entire? Is that DNS pingable? Minecraft server port is the default one? What version is on your Minecraft server?

**Comment by LintRoll** [comment]
> Are you trying to connect through a DNS entire? Is that DNS pingable? Minecraft server port is the default one? What version is on your Minecraft server?

im trying to login to a server. I have console client on a vps

**Comment by TheSnoozer** [comment]
Try:
1) download the latest development build (https://ci.appveyor.com/project/ORelio/minecraft-console-client)
2) set `debugmessages=true` inside your `MinecraftClient.ini`
3) instead of `mcversion=auto` inside your `MinecraftClient.ini` try to set it to a fixed version like one you know is being used by the server e.g. `mcversion=1.8.0`
