### ISSUE TITLE
How to log in in multiple account without like opening like 8 console?

### ISSUE THREAD

**Issue by huizichin** [ORelio/Minecraft-Console-Client#767]
How to log in in multiple account without like opening like 8 console?

**Comment by Exeton** [comment]
There isn't a way to do this without opening multiple consoles afaik. I might add this functionality to my fork, and can let you if I do.

**Comment by Shuaib08** [comment]
You can use the screen method... You can see how to do this [here](https://youtu.be/I3OAYEe7Rlw?t=457)

**Comment by TheSnoozer** [comment]
Indeed screens is the way to go.
Not sure if the youtube video suggests it, but I'd also recommend to use screen along with the `-S` option that allows to give your screen a sessionname. Usually i set this to my alt name. When trying to return to an alt via `screen -s` the sessionname will also be displayed and thus makes it a lot easier to find out the right screen for the right alt if you have more.


Since I would consider that the issue as answered I'm going ahead and close this as part of an issue cleanup. Feel free to reopen if you don't get it to work and also make sure to download the latest development build (https://ci.appveyor.com/project/ORelio/minecraft-console-client)
