### ISSUE TITLE
Rasberry Pi 4 Issues

### ISSUE THREAD

**Issue by DustyDust1543** [ORelio/Minecraft-Console-Client#776]
Hi, Im using Raspbian on a rasberry pi 4 and I am trying to get alts runing 24/7. Please note that MinecraftClient.exe does run. 

On my windows machine, I run a .bat file with the following script:

START /MIN MinecraftClient.exe email password server
timeout 30

One line for each alt. How can i get this working on my rasberry pi. 

I also tried making a folder for each account, with the plan of having to open each client individually, instead of running the script. So in the config file, i wrote the login info and server ip. But when i run the client it just ask for the login and ip, as if the fields were empty. Is there a fix to this?

If anyone knows a fix or another way to run clients on the rasberry pi 4 with autorelog and antiafk please let me know.

**Comment by TheSnoozer** [comment]
that could be done on linux too with using screen.

Example:
```bash
screen -dmS InGameName bash -c "mono MinecraftClient.exe email password server"
sleep 30
```
What this does is essentially opening a screen (a background terminal session) for each alt.

With using such an approach please note that if you share a server with other people they might see your password and login credentials in the 'process tab'.


Basic usage: https://www.rackaid.com/blog/linux-screen-tutorial-and-how-to/

what you might need is:
- Reattach to Screen (`screen -r`)
- Detaching From Screen (`“Ctrl-a” “d”`)

The -S and InGameName part in the command is optional, but helps you to `reattach` to a specific alt and in the end of the day is just for better management for multiple clients (e.g. so you can find the right alt).

**Comment by DustyDust1543** [comment]
> With using such an approach please note that if you share a server with other people they might see your password and login credentials in the 'process tab'.


So I want to use alts on a public server with 300 players. Will they see my credentials

**Comment by TheSnoozer** [comment]
Sorry I wasn't clear enough:
Everyone who has access to the server where you RUN the client/command might have visibility to your credentials (via the "taskmanager"). Since it seems that you will run those on your local raspberry pi everyone who has access to this raspberry might have visibility to your credentials. 

players on the public (minecraft) server will not see your credentials.

**Comment by DustyDust1543** [comment]
> Sorry I wasn't clear enough:
> Everyone who has access to the server where you RUN the client/command might have visibility to your credentials (via the "taskmanager"). Since it seems that you will run those on your local raspberry pi everyone who has access to this raspberry might have visibility to your credentials.
> 
> players on the public (minecraft) server will not see your credentials.

Ah ok thank you. It seems like this is similar to this guys tutorial on using a vps https://www.youtube.com/watch?v=I3OAYEe7Rlw .

**Comment by TheSnoozer** [comment]
Yes, by a quick look that's pretty much what you need. 
The advantage of using screen really boils down that you can disconnect from the VPS/PI and the alt stays logged in. 
I personally use WinScp+Putty, but there are many different tools to achieve the same....

I'm going ahead and close, since I think your question was answered - feel free to open a new issue if you have any other problem :-)
