### ISSUE TITLE
Doesn't work on 1.8.7 servers

### ISSUE THREAD

**Issue by error-dan-overflow** [ORelio/Minecraft-Console-Client#79]
http://gyazo.com/9d9b9eed2e99d548bb8ccab08f647f96

**Comment by ORelio** [comment]
It works with 1.8.7 but some servers incorrectly report themselves as older versions. So Minecraft Console Client will switch eg to 1.7.2 mode because the server told it to do so. Please retry with the latest [dev build](https://ci.appveyor.com/project/ORelio/minecraft-console-client/build/artifacts). If the issue persists, please provide a sample of the "Server version" line with version info retrieved from the server.

**Comment by error-dan-overflow** [comment]
The dev buid worked! Thanks.
