### ISSUE TITLE
Proxy

### ISSUE THREAD

**Issue by Mouro001** [ORelio/Minecraft-Console-Client#80]
Doesnt work with proxy
http://i.imgur.com/VcWDPUg.png

**Comment by Mouro001** [comment]
i added my username and password to the proxy and now it connects, but i recieve another error.
"
Proxy destination 172.17.1.3 on port 8080 responded with a 502 code - Bad Gateway.  If you are connecting to a Microsoft ISA destination please refer to knowledge based article Q283284 for more information.  Server response: Proxy Error ( The specified Secure Sockets Layer (SSL) port is not allowed. ISA Server is not configured to allow SSL requests from this port. Most Web browsers use port 443 for SSL requests.  )
Proxy destination 172.17.1.3 on port 8080 responded with a 502 code - Bad Gateway.  If you are connecting to a Microsoft ISA destination please refer to knowledge based article Q283284 for more information.  Server response: Proxy Error ( The specified Secure Sockets Layer (SSL) port is not allowed. ISA Server is not configured to allow SSL requests from this port. Most Web browsers use port 443 for SSL requests.  )
An error occured while attempting to connect to this IP.
Failed to ping this IP.
"

**Comment by ORelio** [comment]
Hello,
Seems like the proxy you are using works with Minecraft Console Client, but the proxy refuses to forward your connection because you are trying to connect to a non standard distant port ie 25565 (Minecraft Server) instead or 80 (HTTP) or 443 (HTTPS). Not every proxy will work with MCC, either because it's not supported by the proxy library used in MCC, or because it has some limitations like port restrictions (like here) or some timeouts for making request (eg auto close connection after X seconds): proxies are usually made and optimized for web browsing.

**Comment by ORelio** [comment]
Noting new since then, closing, feel free to reopen if needed ;)
