### ISSUE TITLE
Loop in console client script

### ISSUE THREAD

**Issue by Miniller** [ORelio/Minecraft-Console-Client#806]
Okay so this is not really an issue. I just don't know where else could I ask my questions. Sorry for this.
So, 1st question. How do I create a loop? How I do it currently, is in a .txt file, I have the **script xyz.txt** thing and it keeps repeating itself. But I just can't stop it now. (Or can I? please tell me how) 
2nd: More actions under 1 [Match]? I don't want to keep creating more Matches for the same thing, it just doesn't feel comfortable for me.
3rd: Wait X seconds? How it works. The wait thing kinda confuses me. When I put wait 100, it won't wait 100 seconds, neither 100 miliseconds. 
4th: A documentation on every possible thing, in one word, the API. I like MCC so much I think it worth the time learning the whole API and doing cool things. please help

**Comment by TheSnoozer** [comment]
Hi,
1) since this client is built for C# this is more like a question of `how to loop through the content of a file`
Perhaps try the following within a .cs-script:
```
string[] lines = File.ReadAllLines(file);
foreach (var s in lines)
{
  LogToConsole(s);
}
```

using google will provide you potentially way more help and examples than I can do.

2) There is no problem in creating multiple matches, see https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/config/sample-matches.ini

each new Match, must start with a `[Match]`

3) 
```
wait <time> : wait X ticks (10 ticks = ~1 second. Only for scripts)
```
e.g.
```
wait 50
send /server realm
wait 50
send /server realm
....
```

4) perhaps try to take a look at https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/config/README.txt
and the sample-scripts residing in https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config if you want to dig even deeper I'd recommend https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/ChatBot.cs that has some more detailed documentation about the API

if you got a more concrete question I can provide you with a more concrete answer ;-)

**Comment by Miniller** [comment]
Thank you very much. However I can't manage to get the C# thing to work.
[MCC] [Script] Script 'crafttroll.cs' failed to run (InvalidScript).
[MCC] [Script] System.IO.InvalidDataException: The provided script does not have a valid MCCScript header
I get this
The script is:
		//MCCScript 1.0

/* This script demonstrates how to use methods and arguments */

for (int i = 0; i < 5; i++) 
{
	MCC.SendText("Hello")
}
what can I do

**Comment by TheSnoozer** [comment]
For some scripts the MCC Client requires a specific script format.
See https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/config/sample-script-pm-forwarder.cs
or https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/config/sample-script.cs

The "slowness" could perhaps be related to the in-build spam prevention. E.g.
https://github.com/ORelio/Minecraft-Console-Client/blob/877e50579db20a5f756fee41259cdf2b06d012eb/MinecraftClient/Settings.cs#L80

IMHO there is no reason to have multiple messages delivered fast.

Using
```
//MCCScript 1.0

MCC.LoadBot(new ExampleScript());

//MCCScript Extensions

public class ExampleScript : ChatBot
{
    public override void GetText(string text)
    {
        text = GetVerbatim(text);
        LogToConsole("Got Text: " + text);
        for (int i = 0; i < 5; i++) {
            LogToConsole("i=" + i);
            SendText("i=" + i);
        }
    }
}
```
sends a message every ~5 seconds.

Maybe you picked a bad example to measure the performance.

**Comment by ORelio** [comment]
If you need a very simple loop without using C# you have 2 options using regular txt scripts:
 - Add `script <scriptname>` as last instruction so that the script relaunch itself when in reach the end
 - Use ScriptSheduler with a short time interval to launch the script frequently
