### ISSUE TITLE
Adding right click, left clicking interacting protocols

### ISSUE THREAD

**Issue by jakeau** [ORelio/Minecraft-Console-Client#808]
Was wondering if there was a place I could contact you about MC protocols. Cheers.

**Comment by Mhowser** [comment]
Wiki.vg has all the documentation for mc protocols

**Comment by ORelio** [comment]
Related: #502 #205 and #183
Documentation: https://wiki.vg/Protocol
If you have any question on how MCC handles packet or how a packet works, feel free to ask 😉

**Comment by jakeau** [comment]
Cheers for the help.

I am attempting to implement this IOT click a button. I am testing it by attacking the sender.
https://wiki.vg/Protocol#Use_Entity

`        public void SendUseEntity(int target, int type = 0, float x = 0, float y = 0, float z = 0, int hand = 0)
        {
            handler.SendUseEntity(target, type, x, y, z, hand);
        }

        public bool SendUseEntity(int target, int type = 0, float x = 0, float y = 0, float z = 0, int hand = 0)
        {
            byte[] yawpitch = new byte[0];
            PacketOutgoingType packetType = PacketOutgoingType.UseEntity;


            try
            {
                SendPacket(packetType, dataTypes.ConcatBytes(
                    dataTypes.GetVarInt(target),
                    dataTypes.GetVarInt(type),
                    dataTypes.GetFloat(x),
                    dataTypes.GetFloat(y),
                    dataTypes.GetFloat(z),
                    dataTypes.GetVarInt(hand)));
                return true;
            }
            catch (SocketException) { return false; }
        }

`

I am being disconnected from the server. I am using varInt Target as the playerID of the player it wishes to attack. I believe this is wrong, what are the target value and the best way to obtain it. 

Cheers.

**Comment by ORelio** [comment]
If not already the case, I'd suggest to run a vanilla server on your own computer since an anti-cheat plugin may interfer with your work (you'll make it right later, get it working first on vanilla even if it's not fully correct) and the console may show useful error messages.

Regarding the packet itself: make sure the ID of your target is right, visible, and you are looking at it. You may need to enable terrain and movements. You may also want to examine packet content sent by a vanilla client. To do this, I just added for you a [tool](https://github.com/ORelio/Minecraft-Console-Client/tree/master/DebugTools) previously developed for issues such as #195. It's a man-in-the-middle proxy that can intercept and display packets from a Vanilla client as long as encryption is disabled (offline mode servers only). Just need to add the relevant parsing code.
