### ISSUE TITLE
How to run MONO on 4 x RaspBerry wired as cluster using MPI technology ?

### ISSUE THREAD

**Issue by jorgenfhlarsen** [ORelio/Minecraft-Console-Client#812]
Hi

I am currently building a cluster of 4 x RaspBerries.

Basic ideas is to boost performance running MONO on the cluster.

I need ideas and guidance.

Thank you in advance.

**Comment by ORelio** [comment]
Hi, I am not familiar with the clustering technology used, but a single Pi should be able to run MCC with a single account, and likely some additional instances as well. So you could distribute MCC instances across the different Pi you have instead of running a single MCC instance across several Pi.
