### ISSUE TITLE
Automatic Execution of command

### ISSUE THREAD

**Issue by Batx** [ORelio/Minecraft-Console-Client#818]
Hey, i saw your auto reconnect function, but in my case when the server restarts, the player gets just sent back to the lobby server with a in chat message which says server is restarting please rejoin in 30 seconds.
Is it possible to make him do /server1 or anything after he sees a specific message in chat? Or when he gets sent to the lobby will your auto reconnect function work anyways?

Regards
Batx

**Comment by TheSnoozer** [comment]
You could try to use the `match`-Feature of the client (examples in https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/config/sample-matches.ini).

Perhaps something along the lines of

matches.ini
```
[Match]
match=--------------------[Hub]--------------------
actionother=script joinyourrealm
```

joinyourrealm.txt
```
wait 50
send /server realm
wait 50
send /server realm
```

Note:
`wait <time> : wait X ticks (10 ticks = ~1 second. Only for scripts)`

You might want to adjust the wait time, or just repeat the above multiple times. The problem here really is that you have no easy way to verify if the server was started so the easiest is to just try to join multiple times.

**Comment by Ansh51** [comment]
What do i do if i want the script to loop 
I.e the script should be sending /tpy player1 forever cuz iam too dumb to figure out anything else

**Comment by ORelio** [comment]
Just put that in AntiAFK. But the right way of doing so is through RemoteControl or AutoRespond.
User manual is [here](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config).

**Comment by Ansh51** [comment]
> Just put that in AntiAFK. But the right way of doing so is through RemoteControl or AutoRespond.
> User manual is [here](https://github.com/ORelio/Minecraft-Console-Client/tree/master/MinecraftClient/config).

I tried autorespond but it dosent capture the text comming from the server and it never accepts thats why i had to do the spamming option
