### ISSUE TITLE
Implementing 1.15 support

### ISSUE THREAD

**Issue by EchoesNetwork** [ORelio/Minecraft-Console-Client#834]
Hi there,

I've tried to implement 1.15 support to MCC. I don't really know C# very well, so it doesn't work 100%, but I have gotten the client to login successfully. The issue that I've run into is that the client just won't crash in order for me to see what packet IDs are still mismatched. Attached are the updated versions of`ProtocolHandler18PacketTypes.cs`, `ProtocolHandler.cs`, and `Program.cs`, pasted into .txt files that I've made (GitHub won't allow me to upload them with the .cs extension, for some reason). The way I've made these updates is very unprofessional to say the least, but I have changed what packet IDs I can be sure differ from 1.14.4 to 1.15. Any assistance in furthering this would be greatly appreciated!

[Program.txt](https://github.com/ORelio/Minecraft-Console-Client/files/3953219/Program.txt)
[ProtocolHandler.txt](https://github.com/ORelio/Minecraft-Console-Client/files/3953220/ProtocolHandler.txt)
[ProtocolHandler18PacketTypes.txt](https://github.com/ORelio/Minecraft-Console-Client/files/3953221/ProtocolHandler18PacketTypes.txt)

**Comment by ORelio** [comment]
Hi, thanks for your work, and also thanks for notifying me that 1.15 is out since I'm not playing Minecraft anymore. I have reviewed your files:

 - Program.txt: Changes are OK 👍 
 - ProtocolHandler.txt: Same 👍 
 - ProtocolHandler18PacketTypes.txt: Packet types are incorrect.

Beware not to mistake clientbound IDs with serverbound IDs, for instance chat message packet can be from server to client or from client to server, and the ID is different. In 1.15, client-to-server IDs were not updated while all IDs used by MCC for server-to-client packets were updated.

Also some packet layout have changed, so changes need to be reflected in Protocol18.cs, Material.cs and Palette115.cs (mainly to add a few fields and bee-related blocks).

I'm updating MCC right away as 1.15 changes are not too demanding.
