### ISSUE TITLE
Console Client stupid me xD

### ISSUE THREAD

**Issue by YTPSDanDie** [ORelio/Minecraft-Console-Client#860]
I have a CC by oRelio and I can’t seem to work out the matches.ini file I have discord for messaging if you can help. Thank you kind Regards, D.

**Comment by YTPSDanDie** [comment]
@ORelio hi

**Comment by ORelio** [comment]
Hi, I cannot help you on Discord nor understand your issue. Please elaborate.

**Comment by YTPSDanDie** [comment]
Trying to setup command to console client. So can send these commands but
unsure how to do this.

**Comment by fs-s** [comment]
@YTPSDanDie send me discord link I try to help you.

**Comment by YTPSDanDie** [comment]
Discord: PSDanDie#7646

**Comment by YTPSDanDie** [comment]
Thank you

> @YTPSDanDie send me discord link I try to help you.

**Comment by ORelio** [comment]
In order to setup custom commands with AutoRespond:
1) Make sure chat format is properly detected (try [sample-script-with-chatbot](https://github.com/ORelio/Minecraft-Console-Client/blob/master/MinecraftClient/config/sample-script-with-chatbot.cs) it should print the messages in chat as "public" or "private", if not, adjust chat format regexes in config)
2) Add yourself as bot owner in config `botowners=`
3) Add matches with `ownersonly=true` and `actionprivate=<your MCC command>`

Remark: You can also use the RemoteControl bot for easy remote control.
