### ISSUE TITLE
Silent disconnect still not fixed

### ISSUE THREAD

**Issue by SkittyChips** [ORelio/Minecraft-Console-Client#879]
I saw apparently the silent disconnect bug is fixed in the latest client. I'm currently using the latest client but I got a silent disconnect and nothing happened. How do I get it to reconnect?

**Comment by ORelio** [comment]
You are not alone, see #854 and #869 for instance - The fix attempt was in #802.

**Comment by Rimo0** [comment]
Hello,

It seems that I found a sollution for this issue on linux.

My test platform is Linux version 4.19.97-v7+ (dom@buildbot) (gcc version 4.9.3 (crosstool-NG crosstool-ng-1.22.0-88-g8460611)) #1294 SMP Thu Jan 30 13:15:58 GMT 2020

I also have the problem that the mono disconnected silently on my Raspberry Pi 2B, I tried to find a way to run MCC without mono,now I find that the program called AnyExec which works well.

AnyExec will pack net framework and the .net program together so that we can run directly.

Website:[AnyExec](https://linuxdot.net/)

By using this program,I can run MCC directly without installing mono.

I hope it helps.

**Comment by ReinforceZwei** [comment]
I got the same problem when I was AFK testing my own development build.
The client disconnected silently after 7 hours. I was told the reason is connection timeout.
I was still able to use the command prompt and sending client side command after disconnected.
A disconnect handler kicked in immediately when I try to use a server side command (sending out packet to server)
Maybe the timeout detector is not working properly?
Or there are some problems with the mono threading?

I am using Raspberry Pi 4 running raspbian buster and mono 6.8.0.105

**Comment by ORelio** [comment]
All these issues seems to occur on Mono for Raspberry Pi, never found out the exact cause or a reliable workaround 😕

**Comment by Mhowser** [comment]
Would it be possible to have a separate branch of MCC for Linux that does not need Mono to function?

**Comment by ORelio** [comment]
@Mhowser Just like Minecraft needs Java, MCC needs a .NET runtime. Adjustments were made to make MCC work on Mono (otherwise it would crash since .NET support in Mono was incomplete), but apart from that, you can use another .NET runtime. Alternative ways of running MCC would be actual Microsoft .NET framework (.NET 5 with Linux support [is scheduled for November 2020](https://devblogs.microsoft.com/dotnet/introducing-net-5/)), or maybe compiling to a native executable (never tested, and cannot find the issue where someone told about that).

**Comment by CarbonNeuron** [comment]
This happens to me aswell if the clients don't receive chat messages for a few hours. Like if there is no one talking in chat. I'm on windows not raspberry pi. However, I haven't updated my build in a while because of my modifications.

**Comment by ORelio** [comment]
@CarbonNeuron The only modification that might help you is in #802 if your build is newer, there should not be any improvement that would help.

**Comment by ORelio** [comment]
Should be fixed as per #1219 thanks to @ReinforceZwei's findings 🙏
