### ISSUE TITLE
Minecraft Forge Compatibility

### ISSUE THREAD

**Issue by bearbear12345** [ORelio/Minecraft-Console-Client#9]
Forge Compatability -
  http://wiki.vg/Plugin_channel#FML 
  http://wiki.vg/Protocol#0xFA

**Comment by ORelio** [comment]
Hello,
During a few days, I made some research about Forge's protocol,
by reading, understanding and testing some code
* From BungeeCord's repository:
  - [ForgeServerHandler.java](https://github.com/SpigotMC/BungeeCord/blob/master/proxy/src/main/java/net/md_5/bungee/forge/ForgeServerHandler.java)
  - [ForgeConstants.java](https://github.com/SpigotMC/BungeeCord/blob/9cf57ca929934fb58463a1e654e81ec72451d894/proxy/src/main/java/net/md_5/bungee/forge/ForgeConstants.java)
* From the Forge repository:
  - [FMLNetworkHandler.java](https://github.com/maxbwheeler/minecraft-mods/blob/master/src/cpw/mods/fml/common/network/FMLNetworkHandler.java)
  - [FMLHandshakeMessage.java](https://github.com/MinecraftForge/FML/blob/master/src/main/java/net/minecraftforge/fml/common/network/handshake/FMLHandshakeMessage.java)
  - [FMLPacket.java](https://github.com/maxbwheeler/minecraft-mods/blob/master/src/cpw/mods/fml/common/network/FMLPacket.java)
  - [FMLProxyPacket.java](https://github.com/MinecraftForge/FML/blob/master/src/main/java/net/minecraftforge/fml/common/network/internal/FMLProxyPacket.java)
  - [NetworkDispatcher.java](https://github.com/MinecraftForge/FML/blob/master/src/main/java/net/minecraftforge/fml/common/network/handshake/NetworkDispatcher.java)

So here is what I understood from my studies:

* The FML client will add a FML tag in the handshake packet: `"\0FML\0"`
  - This can easily be added in MCC into [this line](https://github.com/ORelio/Minecraft-Console-Client/blob/c957ed0efd09cf27a69445a7baa92e7434021a3e/MinecraftClient/Protocol/Handlers/Protocol18.cs#l460): `getServerHost() + "\0FML\0"`
  - This tag is discarded by the vanilla server and the login procedure will work properly
  - Without this tag, the vanilla client will be kicked when joining a Forge server

* Once a FML client has been detected by the Forge server
  - The Forge server will [register](http://wiki.vg/Protocol#Plugin_Message) `FML|HS`, `FML` and some more channels for the mods
  - It will send a [mod list request](https://github.com/maxbwheeler/minecraft-mods/blob/master/src/cpw/mods/fml/common/network/ModListRequestPacket.java) FML packet, using the `FML` channel
  - It will [switch](https://github.com/MinecraftForge/FML/blob/master/src/main/java/net/minecraftforge/fml/common/network/handshake/NetworkDispatcher.java#l407) to a FML wrapper [handling](https://github.com/MinecraftForge/FML/blob/master/src/main/java/net/minecraftforge/fml/common/network/internal/FMLProxyPacket.java#l70) a custom packet layout
  - It will wait for the [mod list response](https://github.com/maxbwheeler/minecraft-mods/blob/master/src/cpw/mods/fml/common/network/ModListResponsePacket.java) from the FML client

* Once the client has sent its mod list, the server will either
    - Accept the ongoing connection by sending an end of handshake packet
    - Kick the client with a list of missing or outdated mods

So, to implement FML handling we have to
* Add FML tag when logging in
* Handle FML handshake
    - Handle Mod list request
    - Handle custom packet layout
    - Handle missing mods list
    - Retry logging in after faking the mod list

This would be really long and complcated since I have no idea how their custom packet layout works, how to send or read FML packets, mod request/responses, and so on.

Forge handling seems too much a hassle for such a small amout of servers, it's long, it not documented at all, and its a different protocol than the official Minecraft protocol.

**Comment by Aragas** [comment]
Please advise. Have stuck on LoginSuccess & SetCompression packets. Don't get anything more, don't understand why. Not PluginMessage. That is a bit strange. I'm currently reading sources provided by you, but no clue right now.
* Are sending "\0FML\0". I saw int FML_HASH, can mimic it. I thought it was used on LoginStart packet, but not sure about it.

**Comment by ORelio** [comment]
Well, despite sombe issue with some Forge variants such as `KCauldron`, seems like this issue can finally be closed. After almost 3 years :laughing:

**Comment by bearbear12345** [comment]
Yaaay!!! That persistence haha!

I myself quit MC around 2014, but good to see you still working hard on this @ORelio!

**Comment by ORelio** [comment]
Well that's also not so bad to ne able to move on ^^
