### ISSUE TITLE
Proxy Issue

### ISSUE THREAD

**Issue by IchUseKomplexe** [ORelio/Minecraft-Console-Client#919]
I have the Problem, that the console client crashes often using a Proxy. It's a german paid proxy and It's fast enough. Still after some time the bot looks like frozen and if I type something after some seconds it says connection to server lost or so. Also Autorelog does not work if it freeze like this

**Comment by ReinforceZwei** [comment]
Hi, what operating system are you using?
If it is Linux, please take a look at #879

**Comment by ORelio** [comment]
Although your proxy is a paid proxy, it is likely intended for HTTP. One of the main issue is that they may enforce a connection timeout, which would cut your connection to the server after a certain amount of time. A premium proxy should have a very large timeout, though, otherwise you wouldn't be able to download large files. Additionally, MCC may experience timeouts on Mono for Mac/Linux.

**Comment by IchUseKomplexe** [comment]
I will test a Mono alternative and btw. do you know how I can use a proxy on my normal Minecraft?

**Comment by ORelio** [comment]
AFAIK this is not possible on vanilla Minecraft but some mods will likely allow this.

**Comment by IchUseKomplexe** [comment]
Do you know mods?

Am Do., 2. Apr. 2020 um 17:11 Uhr schrieb ORelio <notifications@github.com>:

**Comment by ORelio** [comment]
Not for recent Minecraft versions.
